### ISSUE TITLE
multiple package installs in one like npm

### ISSUE THREAD

**Issue by jh3y** [atom/apm#112]
Hey,

This might have come up before or maybe I am missing something but it would be nice to be able to install multiple packages at once like;

```
apm install linter linter-jshint language-jade
```

instead of having to run each one at a time.

This is available in `npm` and can save a lot of time for people if they have various packages installed. Also it means you could store what you have installed in a config file so that if you set up a new environment you can reference/use it.

@jh3y

**Comment by MegaJsTeam** [comment]
if globa?

npm install -g yo -g gulp
