### ISSUE TITLE
Escaping issue in converting snippets of textmate language bundle.

### ISSUE THREAD

**Issue by s-shin** [atom/apm#136]
Backslash to escape "$" is also escaped.

For example,

```
    <string>for (my \$${1:var} = 0; \$$1 &lt; ${2:expression}; \$$1++) {
    ${3:# body...}
}
</string>
```

(https://github.com/textmate/perl.tmbundle/blob/master/Snippets/for.plist)

is converted to

```
  'For Loop':
    'prefix': 'for'
    'body': 'for (my \\$${1:var} = 0; \\$$2 < ${3:expression}; \\$$4++) {\n\t${5:# body...}\n}\n'
```

(https://github.com/atom/language-perl/blob/master/snippets/language-perl.cson)

but it is expected that `\$${1:var}` is converted to `\$${1:var}` or `$${1:var}`, not `\\$${1:var}`.

**Comment by ecampii** [comment]
escaping \ also isnt working.

**Comment by 50Wliu** [comment]
@ecampii That's not related to this issue, but use `\\\\` to get a backslash to show up.
