### ISSUE TITLE
ELIFECYCLE errors for several packages, seemingly due to old npm version

### ISSUE THREAD

**Issue by ceeeKay** [atom/apm#142]
(Note I'm on CentOS 6.5 so I'm not sure if this will reproduce on the current/supported Ubuntu version. I'm hoping this input can help make the atom build more flexible/portable)

I was getting errors like this

```
1178 error scrollbar-style@0.4.0 install: `node-gyp rebuild`
1178 error Exit status 1
1179 error Failed at the scrollbar-style@0.4.0 install script.
1179 error This is most likely a problem with the scrollbar-style package,
1179 error not with npm itself.
1179 error Tell the author that this fails on your system:
1179 error     node-gyp rebuild
1179 error You can get their info via:
1179 error     npm owner ls scrollbar-style
1179 error There is likely additional logging output above.
1180 error System Linux 2.6.32-431.11.2.el6.centos.plus.x86_64
1181 error command "/build/atom/apm/node_modules/atom-package-manager/bin/node" "/build/atom/apm/node_modules/atom-package-manager/node_modules/npm/bin/npm-cli.js" "--globalconfig" "/build/atom/apm/node_modules/atom-package-manager/.apmrc" "--userconfig" "/home/user/.atom/.apmrc" "install" "--target=0.11.10" "--arch=x64" "--quiet"
1182 error cwd /build/atom
1183 error node -v v0.10.26
1184 error npm -v 1.4.4
1185 error code ELIFECYCLE
1186 verbose exit [ 1, true ]
```

But I found that if I use npm install <package> directly on the package that failed with an ELIFECYCLE error, it works. Through repetitions of `script/build`, `tail npm-debug.log`, and `npm install <package>`, I was able to progress to a further step in the build process after running this command (packages I needed combined to one line).

```
npm install scrollbar-style runas nslog pathwatcher oniguruma git-utils
```

I have npm v1.4.20 installed on my machine... The fact that I can get past these errors by simply running the npm install command makes me suspect perhaps there are issues with npm 1.4.4 (version that appears to be used in apm, as it shows up in npm-debug.log) that have been resolved since then.

**Comment by kevinsawicki** [comment]
Closing this out since hopefully it was fixed by https://github.com/atom/apm/pull/143 or further npm upgrades. Please comment if you are still experiencing it.
