### ISSUE TITLE
Too many bash and node process!

### ISSUE THREAD

**Issue by yongkangchen** [atom/apm#144]
Atom: 0.108.0
Mac os x 10.9.3
I found too many bash and node process in Activity Monitor. Event if i close atom.
every bash's parent process is: launchd(1)
every node's parent process is: bash

[look the process information](https://gist.github.com/yongkangchen/7360de46bf1c08c964ed)

**Comment by 50Wliu** [comment]
@yongkangchen Are you still experiencing this issue?

**Comment by damieng** [comment]
No response, closing.
