### ISSUE TITLE
Add SOCKS proxy support

### ISSUE THREAD

**Issue by lijunle** [atom/apm#173]
Although this [check-in](https://github.com/atom/apm/commit/5a4b99f631b658c32596b5c768929bb833493abf) add support for HTTP proxy and HTTPS proxy. It does not support SOCKS proxy. According to [this post](https://github.com/mikeal/request/pull/680#issuecomment-31963174), that is not too much work. How do you think about this?

**Comment by RickieL** [comment]
my solution for atom socks proxy as below
```
rickie-pc $ cat ~/.atom/.apmrc
strict-ssl = false
http_proxy = socks5://127.0.0.1:1997
https_proxy = socks5://127.0.0.1:1997
```

works for me.

**Comment by mdluo** [comment]
`~/.atom/.apmrc`

```
strict-ssl=false
http-proxy="http://localhost:8123"
https-proxy="http://localhost:8123"
```

**Comment by ahui132** [comment]
```
$ cat ~/.atom/.apmrc
strict-ssl = false
http_proxy = socks5://127.0.0.1:1997
https_proxy = socks5://127.0.0.1:1997
```
Not work for me.
`Unable to download https://www.atom.io/api/packages/vim-mode-plus/versions/0.93.0/tarball: connect ETIMEDOUT 50.17.240.35:443`

**Comment by hydrocode** [comment]
@ahui132  You can try this, 
`strict-ssl=false`
`http-proxy=socks5://127.0.0.1:1081`
`https-proxy=null`

**Comment by snowdream** [comment]
$ cat ~/.atom/.apmrc
strict-ssl=false
http_proxy=socks5:127.0.0.1:1080
https_proxy=socks5:127.0.0.1:1080

**Comment by Vitoom** [comment]
$vim ~/.atom/.apmrc
strict-ssl=false
http_proxy=socks5:127.0.0.1:1080
https_proxy=socks5:127.0.0.1:1080

**Comment by Vitoom** [comment]
remove all other contents

**Comment by ZiangYan** [comment]
On Mac you can use polipo to convert a socks5 proxy to http proxy, and then use the http proxy in ~/.atom/.apmrc. This solution works for me.

**Comment by HanslettTheDev** [comment]
On windows process is difficult just simply convert socks proxy to HTTP proxy or use proxifier for windows

**Comment by sunqb** [comment]
> On windows process is difficult just simply convert socks proxy to HTTP proxy or use proxifier for windows

agree with you !!!
