### ISSUE TITLE
apm ignores python versioning in npm config

### ISSUE THREAD

**Issue by ghost** [atom/apm#179]
apm install  atom-lint 
and 
apm install --python=python2.7 atom-lint

result in:
gyp ERR! stack Error: Python executable "python" is v3.4.1, which is not supported by gyp.
gyp ERR! stack You can pass the --python switch to point to Python >= v2.5.0 & < 3.0.0.

npm config list outputs:
; globalconfig /usr/etc/npmrc
python = "/usr/bin/python2"

which python2.7 outputs:
/usr/bin/python2.7

I was eventually able to get the linter installed by: 
export PYTHON=python2.7

but it appears that the switch and config are ignored.

**Comment by jokeyrhyme** [comment]
I can confirm that the following resolves Python3-related issues with apm:

```sh
echo "python=/usr/bin/python2" >> ~/.atom/.apmrc
```

**Comment by arijoon** [comment]
you can also do 
```sh
apm config set python /path/to/python2
```

**Comment by ioquatix** [comment]
This no longer seems to work :(

**Comment by ioquatix** [comment]
I found that you need to do the following:

In your `apm` script

    vim `which apm`

Comment out the line

    export npm_config_python="${binDir}/python-interceptor.sh"

Ensure you did `apm config set python /path/to/python2.7` and then it should work.

**Comment by kylebarron** [comment]
@ioquatix The hack works. But I'm guessing it'll be reset each time you update Atom.

**Comment by ioquatix** [comment]
@jokeyrhyme Your suggestion doesn't work. I'll make a PR.

**Comment by jokeyrhyme** [comment]
@ioquatix well, considering python2 is end-of-life 2020-01-01, Node.js and its entire ecosystem, including native modules, needs to be upgraded to python3 pretty soon

**Comment by ioquatix** [comment]
I looked into it briefly, and it seems like there is a pretty big cludge in the form of `python-interceptor.sh` and https://github.com/atom/apm/blob/1ac3c80a9e148127e08d7a7965bf8a38ccd27cd8/bin/apm#L34-L44 which ignores the user specified python env and instead basically breaks everything. I feel like the first step, and what I was thinking to make as a PR, would be to remove that cludge.

**Comment by Aerijo** [comment]
@ioquatix I would suggest discovering why that file was made in the first place, before attempting a PR. It may or may not be required now, I don’t know, but Chesterson’s fence would be a good principle to keep in mind.

**Comment by ioquatix** [comment]
Apparently it was made to fix the python version detection but it now seems completely broken.

**Comment by ioquatix** [comment]
This is still a problem, and my proposed fix above still works :p
