### ISSUE TITLE
Allow install via repo url and branch

### ISSUE THREAD

**Issue by dsandstrom** [atom/apm#183]
For those unfamiliar with Ruby Gemfiles, you can add `git`, `github`, and `branch` options to specify where to look for the gem.

I would like this ability in apm.  It would be useful when a package is broken and the maintainer is mia.  Or you would like to try a feature branch that has not been merged with master.

The only way I know how to do this now is to clone the repo and use `apm link`.

**Comment by amejia1** [comment]
This would be nice. I have need of allowing others to more easily try out a branch of an Atom package (https://github.com/amejia1/atom-xterm/tree/xterm.js_v3).

**Comment by UziTech** [comment]
> Perhaps allowing the apm develop command to specify a Git URL would make things easier?

@lee-dohm that would make it easier but for some reason the maintainers don't want to allow that

#767

**Comment by UziTech** [comment]
Would @atom be open to adding a `--branch` option to `apm install`?

I would be ok with making a pull request if I knew it wasn't going to be a waste of time.

**Comment by lee-dohm** [comment]
Thanks for pointing this out @UziTech. Since installing the `master` branch is already available directly via `apm install` and installing a branch is available by using `apm link`, no, I don't think that we would want to support a `--branch` option.

Since this is as implemented as we're going to have for the time being. I'm going to close this.

**Comment by UziTech** [comment]
Thanks for the explanation. So we shouldn't be trying to make apm easier for developers and streamline their workflow as long as there is a way to do something? Is apm not getting updated with new features because something else is going to replace it?

**Comment by lee-dohm** [comment]
No, there are no plans to replace apm with anything.

**Comment by UziTech** [comment]
Thank you for the response. I know you guys are busy with Atom, I love helping out wherever I can and staying in the loop makes it a lot easier.

**Comment by olsonpm** [comment]
Hmm - I don't understand the implication that branches are for development.  I just created an atom package where the default branch holds the source.  I use webpack to concatenate all the files and thus keep the built artifacts in a 'release' branch.  I will rename this branch to master for now to abide by atom's workflow, but a apm install `olsonpm/<package>#release` would be ideal

**Comment by UziTech** [comment]
@lee-dohm correct me if I'm wrong, but I think the idea is that apm is feature complete. Meaning everything apm is supposed to do can be done (even if it is not easy). And that the Atom team has more important things to work on. (i.e. Atom)

If you want to install a certain branch you can do the following:
 - Clone the repo
 - Checkout the branch
 - Run `apm link`

**Comment by Arcanemagus** [comment]
@olsonpm Note that the discussion in this thread is primarily about non-standard or unusual ways of installing a package. If you simply run `apm install package-name` or `apm install package-name@x.y.z` then apm will use the _tag_ that corresponds to the version publish on apm's package list. Note that there is no restriction on the branch where that tag lives, which means your prefered way of organizing your package works just fine for regular installs.

It's only when doing non-standard installs that these oddities start coming into play, and for most cases this is when you are developing, which is exactly what `apm link` is for.

**Comment by olsonpm** [comment]
So my misunderstanding was that I should be installing from a tag instead of a branch.  That makes sense to me if so, and I appreciate the explanation.
