### ISSUE TITLE
Cannot republish after transferring the repo

### ISSUE THREAD

**Issue by josa42** [atom/apm#188]
I transferred my repo and renamed it from `josa42/atom-linter-less` to `AtomLinter/linter-less`. Now I cannot not republish the plugin.

```
$ apm publish --tag v0.2.0
Creating new version failed: Git tag not found
```

I also tries to unpublish, but that fails too.

```
$ apm unpublish linter-less
Are you sure you want to unpublish linter-less? (yes) yes
Unpublishing linter-less ✗
Unpublishing failed: Unauthorized
```

Installation fails too:

```
$ apm install linter-less
Installing linter-less to /Users/josa/.atom/packages ✗
No releases available for linter-less
```

What am I supposed to do?

**Comment by 50Wliu** [comment]
This was a bug in apm's backend API. We think we've got it resolved now. 🤞

If you still want to unpublish your package, can you please try unpublishing again? If you've already run `apm login`, then this command should do the trick:

    apm unpublish your-package-name

If you still run into trouble unpublishing, please let us know.
