### ISSUE TITLE
APM Cannot Install Any Packages (Proxy Issue?)

### ISSUE THREAD

**Issue by YellowDarter** [atom/apm#190]
I have searched through the forum and done a fair amount of Google-ing before posting, but if this is a duplicate of something I was unable to find, I humbly request a link.

I am on Windows and am behind a corp. firewall.  I have installed Atom via Chocolatey (which automatically uses the proxy).  I am unable to search (or install) packages using the Atom GUI, so I decided to troubleshoot at the command line.  

Prior to making any changes, when I issue the command "apm install <package>" I got the error "failed: Request for package information failed: connect ETIMEDOUT".  However, having had similar issues with NPM when I originally installed, I configured the .apmrc file in the same manner as I had to configure my .npmrc file (per the instructions on this site).

My .apmrc file is located at c:\users<username>.atom.apmrc
I added (obviously with the "username", "password", etc fields specific to my real settings):
strict-ssl=false
http-proxy=http://username:password@proxyurl.com:port
https-proxy=http://username:password@proxyurl.com:port

Following this change, when I issue "apm install <package>" I now get another error I cannot get past, here is the output:
gyp info it worked if it ends with ok
gyp info using node-gyp@0.12.2
gyp info using node@0.10.30 | win32 | ia32
gyp http GET https://gh-contractor-zcbenz.s3.amazonaws.com/atom-shell/dist/v0.16.0/node-v0.16.0.tar.gz
gyp WARN install got an error, rolling back install
gyp

It looks like the GET above is failing, but when I try this address manually in a browser, it works correctly and the tar.gz file is downloaded.

In case it is helpful in troubleshooting here is a little more info:
apm -v output:
apm 0.93.2
npm 1.4.4
node 0.10.30
python 2.7.8
git 1.9.4.msysgit.0
visual studio

I have attempted the apm install commands from both admin and non-admin command shells.

NPM installations work without a hitch.  The .npmrc file is located at c:\users<username>.npmrc and has the following lines:
strict-ssl=false
proxy=http://username:password@proxyurl.com:port
http-proxy=http://username:password@proxyurl.com:port
https-proxy=http://username:password@proxyurl.com:port

Any help is very appreciated!

**Comment by AnthraxBass** [comment]
Hi ! I think that I have related issue: 

each time I'm trying to update the following file '%USERPROFILE%\.atom\.apm\.apmrc' with the value of my proxy, and to verify this by executing 'apm config get https-proxy' I can see that my proxy is being erased from the .apmrc. 

Is there a workaround?

**Comment by tborychowski** [comment]
@AnthraxBass,
Have you tried:
`apm config set https-proxy https://your-proxy:1234`
The correct path to the `.apmrc` file on windows seems to be: `%USERPROFILE%\.atom\.apmrc`.
This file doesn't exist initially and you need to create it (or use `apm config set ...`).
It was confusing for me too: there's a config file that should not be edited, but the file that should be edited, with the same name, is not there... ;-)

**Comment by sudoor** [comment]
I hava the same problem, 
```shell

$ apm install language-vue
Installing language-vue to /Users/Jarvis/.atom/packages
gyp info it worked if it ends with ok
gyp info using node-gyp@3.4.0
gyp info using node@6.9.5 | darwin | x64
gyp http GET https://atom.io/download/electron/v2.0.3/iojs-v2.0.3.tar.gz
gyp WARN install got an error, rolling back install
gyp ERR! install error
gyp ERR! stack Error: connect ECONNREFUSED 127.0.0.1:443
gyp ERR! stack     at Object.exports._errnoException (util.js:1022:11)
gyp ERR! stack     at exports._exceptionWithHostPort (util.js:1045:20)
gyp ERR! stack     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1087:14)
gyp ERR! System Darwin 17.6.0
gyp ERR! command "/private/var/folders/yx/kxdgj9hd05b3sh5r7b_v3tgw0000gn/T/AppTranslocation/0270C406-B4D5-46F3-B9CF-F1F56E86E088/d/Atom.app/Contents/Resources/app/apm/bin/node" "/private/var/folders/yx/kxdgj9hd05b3sh5r7b_v3tgw0000gn/T/AppTranslocation/0270C406-B4D5-46F3-B9CF-F1F56E86E088/d/Atom.app/Contents/Resources/app/apm/node_modules/node-gyp/bin/node-gyp.js" "install" "--runtime=electron" "--target=2.0.3" "--dist-url=https://atom.io/download/electron" "--arch=x64" "--ensure"
gyp ERR! cwd /Users/me/.atom
gyp ERR! node -v v6.9.5
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok
```
I have no proxy !
And I guess it's AWS's problem,  when installer exectute `REQUEST make request https://gh-contractor-zcbenz.s3.amazonaws.com/atom-shell/dist/v2.0.3/iojs-v2.0.3.tar.gz`,
but given `Failed to connect to gh-contractor-zcbenz.s3.amazonaws.com port 443: Connection refused`.

**Comment by farhank3389** [comment]
4 years later and still having this issue...

**Comment by Torreshan** [comment]
> 4 years later and still having this issue...

yes i am also behind a proxy....

**Comment by cataclysmic** [comment]
Is there any solution by now? I am sitting behind a proxy on Windows 10 running atom from folder. I can install using the commandline and apm after setting the proxy but when searching for packages `apm install search package` I get an error message.
