### ISSUE TITLE
win7 32 bit  build error 

### ISSUE THREAD

**Issue by huati365** [atom/apm#191]
when i run npm install command in apm/ folder : 

Desktop\apm\node_modules\git-utils>node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp
s" rebuild
Once in this solution generates a project. If you want to enable parallel generation, please add "/m" switch.
MSBUILD : error MSB3428: can no load  Visual C++ component “VCBuild.exe”。To solve this problem，1) install .NET Framework 2.0 SDK；2) install Microsoft Visual Studio 2005；

**Comment by kevinsawicki** [comment]
I believe this was a problem with the build chain needed to npm not being correctly installed.

I'd recommend following the instructions in the output: `To solve this problem，1) install .NET Framework 2.0 SDK；2) install Microsoft Visual Studio 2005`
