### ISSUE TITLE
Set registry path to http://...

### ISSUE THREAD

**Issue by olingerc** [atom/apm#197]
I'm one of those behind a complicated proxy. I got npm working after lots of research. My proxy does not allow https connections so I need the following to get npm to work

```
npm config set proxy MY_PROXY
npm config set registry "http://registry.npmjs.org/"
```

The important part is setting the registry.
How do I replicate this for apm? I tried lots of things in the .apmrc file but none of them worked. Does apm use the npm registry? Why does apm not simple take over the npm proxy settings? I'm sure there must be a reason

EDIT:
apm  0.96.0
npm  1.4.4
node 0.10.32
python 2.7.6
git 1.9.1

My ~/.apmrc

```
strict-ssl = false
proxy = http:/...
http-proxy = http://...
https-proxy = http://...
```

Thanks

**Comment by MisterFantastic** [comment]
I was having this issue in verison 1.3.1 running in windows platform. Hence I created a ~/.apmrc file in "~/users/.atom" folder. Then I added "strict-ssl = false" to fix it.
