### ISSUE TITLE
Native module (chokidar) with APM: Assertion failed: (handle->InternalFieldCount() > 0)

### ISSUE THREAD

**Issue by bpasero** [atom/apm#220]
I am not sure if this is the right place to file this issue, but I am starting here because I dont see the issue when using vanilla npm.

Setup:
- Atom Shell 0.19.4
- APM --version
   > apm  0.111.0
   > npm  1.4.4
   > node 0.10.33
   > python 2.7.6
   > git 2.1.2
- chokidar 0.11.1

To reproduce:
- unzip atom shell 0.19.4
- create a bare atom shell application as outlined at https://github.com/atom/atom-shell/blob/master/docs/tutorial/quick-start.md
- add a dependency to chokidar from the package.json

```
{
  "name"    : "your-app",
  "version" : "0.1.0",
  "main"    : "main.js",
  "dependencies": {
  	"chokidar": "*"
  }
}
```
- use chokidar from main.js

```
var app = require('app');  // Module to control application life.
var BrowserWindow = require('browser-window');  // Module to create native browser window.

var chokidar = require('chokidar');
var watcher = chokidar.watch("~/", { persistent: true, usePolling: false });
watcher.on("all", function(type, path) {
  console.log(type, path);
});

// Report crashes to our server.
require('crash-reporter').start();

// Keep a global reference of the window object, if you don't, the window will
// be closed automatically when the javascript object is GCed.
var mainWindow = null;

// Quit when all windows are closed.
app.on('window-all-closed', function() {
  if (process.platform != 'darwin')
    app.quit();
});

// This method will be called when atom-shell has done everything
// initialization and ready for creating browser windows.
app.on('ready', function() {
  // Create the browser window.
  mainWindow = new BrowserWindow({width: 800, height: 600});

  // and load the index.html of the app.
  mainWindow.loadUrl('file://' + __dirname + '/index.html');

  // Emitted when the window is closed.
  mainWindow.on('closed', function() {
    // Dereference the window object, usually you would store windows
    // in an array if your app supports multi windows, this is the time
    // when you should delete the corresponding element.
    mainWindow = null;
  });
});
```

- install chokidar using apm: "apm install ."
- run our app

As soon as you launch the app, you will find this on the command line:

➜  MacOS  ./Atom ~/Desktop/watchapp
Assertion failed: (handle->InternalFieldCount() > 0), function Wrap, file /Users/bpasero/.atom/.node-gyp/.node-gyp/0.19.4/src/node_object_wrap.h, line 77.
[1]    4859 abort      ./Atom ~/Desktop/watchapp

I am able to use chokidar with its native dependency (fsevents) on both node.js 0.10 and 0.11, but it fails when used from Atom. 

Any pointers to how to further debug this issue is welcomed.

I uploaded my full Atom app to reproduce without following the steps to here: https://drive.google.com/file/d/0B3qppHphwBz0eEp0UmF0QnVUeVU/view?usp=sharing

**Comment by kevinsawicki** [comment]
@bpasero are you still experiencing this issue?

**Comment by bpasero** [comment]
@kevinsawicki yes, I encourage you to try it out :)

**Comment by bpasero** [comment]
@kevinsawicki I just tried with latest (APM 0.120.0, node 0.10.x) and now I am getting a different error that you might know more about:

```
[1519:0117/104832:INFO:CONSOLE(8)] "Error: Module version mismatch. Expected 16, got 17.
    at Error (native)
    at Object.module.(anonymous function) [as .node] (/Atom.app/Contents/Resources/atom/common/lib/asar.js:422:20)
    at Module.load (module.js:363:32)
    at Function.Module._load (module.js:318:12)
    at Module.require (module.js:373:17)
    at require (module.js:392:17)
    at Object.<anonymous> (/node_modules/chokidar/node_modules/fsevents/fsevents.js:9:14)
    at Module._compile (module.js:468:26)
    at Object.Module._extensions..js (module.js:486:10)
    at Module.load (module.js:363:32)", source: /node_modules/chokidar/lib/fsevents-handler.js (8)
Error: Module version mismatch. Expected 16, got 17.
    at Error (native)
    at Module.load (module.js:363:32)
    at Function.Module._load (module.js:318:12)
    at Module.require (module.js:373:17)
    at require (module.js:392:17)
    at Object.<anonymous> (/node_modules/chokidar/node_modules/fsevents/fsevents.js:9:14)
    at Module._compile (module.js:468:26)
    at Object.Module._extensions..js (module.js:486:10)
    at Module.load (module.js:363:32)
    at Function.Module._load (module.js:318:12)
```

**Comment by bpasero** [comment]
@kevinsawicki did you guys do something about it? I think I dont see this anymore with APM 0.157

**Comment by maxbrunsfeld** [comment]
@bpasero so you're no longer seeing this? The last error that you reported was due to a node module compiled against the wrong version of V8. Usually when this happens, you just need to rebuild the node module. See the electron docs on using native modules: http://electron.atom.io/docs/v0.28.0/tutorial/using-native-node-modules/
