### ISSUE TITLE
Unpublishing fails with 'Unauthorized' when the package repository doesn't exist

### ISSUE THREAD

**Issue by olmokramer** [atom/apm#221]
I tried unpublishing a package of which I had already deleted the repository on github. It failed with message: 'Unpublishing failed: Unauthorized'. When I recreated the repository (I left it empty) unpublishing worked again.
To me it seems a bit strange that the github repo must exist when unpublishing a package...
Also I think the error message I got isn't very clear about the actual issue...

**Comment by saschaeggi** [comment]
Same problem here. The git repo doesn't exist anymore and I can't unpublish the package now. But it also didn't worked when I recreated the repo again.

**Comment by thedaniel** [comment]
This is a common problem. Package permissions are tied to repo permissions and we don't do a very good job of communicating that.

**Comment by beardedprojamz** [comment]
I don't know if anyone is manually deleting packages - but I have one - https://atom.io/packages/debugger-lines that also can not be unpublished because I removed the repo before unpublishing.

**Comment by thedaniel** [comment]
This week I'll go through and manually remove packages and fix up everything that might need fixing up in the database all at once.

**Comment by chuank** [comment]
I have a similar issue with my package (particle-offline-compile). Some help to manually remove this package is appreciated, as I'd like to share the work with others.

The unpublishing criteria seems to be very precise and possibly unforgiving of packages that fail during any publish attempt. In fact this was why I had to unpublish – apm login failed for me the first time as used an invalid application token for my 2FA-protected account, but it was a dead-end from there on.

The initial failure caused everything else to fail, including any attempts to unpublish it ('Unauthorised') – and I still have my repo up then (it's been removed now).

Perhaps it might be possible for users to send a 'wipe' request via apm to atom.io?

**Comment by danielbayley** [comment]
I have the same issue; I was just doing a test, so https://atom.io/packages/test needs to be deleted. But also having issues with authorisation in general (see #315).

**Comment by jasonrudolph** [comment]
> I tried unpublishing a package of which I had already deleted the repository on github. It failed with message: 'Unpublishing failed: Unauthorized'.

Thanks for reporting this issue. :bow: This should be resolved now. :sweat_smile:

If you were the owner of the package's repository on github.com and you've deleted the repository, you should be able to use `apm unpublish` to successfully unpublish the package. If you still run into an issue trying to unpublish the package, please let us know.
