### ISSUE TITLE
How do I tell APM which node version to use?

### ISSUE THREAD

**Issue by bpasero** [atom/apm#241]
I want to "apm install" the chokidar package which relies on the native fsevents module. When I run "apm install" the output is:

gyp info it worked if it ends with ok
gyp info using node-gyp@0.12.2
gyp info using node@0.10.33 | darwin | x64
0.18.0
gyp info ok

I am worried about the fact that gyp seems to use node 0.10.33 whereas in Atom the node version typically is 0.11.x. I believe this version mismatch is causing issues when executing the native module later in Atom.

When I run "node -v" from the same terminal though, I see that I run 0.11.14. Is there a way to tell APM to use the node 0.11 headers or does it not matter because APM has its own headers?

**Comment by kevinsawicki** [comment]
Closing out
