### ISSUE TITLE
apm Not functioning properly

### ISSUE THREAD

**Issue by wodaixin** [atom/apm#243]
![img](http://git-page.qiniudn.com/20141228021758.jpg)
![img](http://git-page.qiniudn.com/20141228022301.png)
![img](http://git-page.qiniudn.com/20141228022416.jpg)

and can't show in explorer

![img](http://git-page.qiniudn.com/20141228023255.jpg)

**Comment by 50Wliu** [comment]
@wodaixin Are you still experiencing this issue?

**Comment by Ben3eeE** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment https://github.com/atom/apm/issues/243#issuecomment-224081383. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
