### ISSUE TITLE
Update npm?

### ISSUE THREAD

**Issue by mnquintana** [atom/apm#245]
I noticed that apm is running npm 1.4.4 – a pretty old version of npm at this point (latest is 2.1.17) – is there a reason apm is still running on this old version?

**Comment by kevinsawicki** [comment]
The main reason is regressions, last time we tried to upgrade there were bugs in the current npm release (I assume they were fixed since then) and so we downgraded again.

I've been waiting for a compelling reason to upgrade since then and haven't seen one but I'm definitely open to the idea .
