### ISSUE TITLE
apm update requires npm package.json

### ISSUE THREAD

**Issue by mnquintana** [atom/apm#246]
Not sure if this is intentional, but `apm update` seems to just call `npm update`, which looks for a local `package.json`. I expected `apm update` to do what `apm upgrade` actually does (check for package updates and give you the option to update them). As a package consumer, the current behavior of `apm update` is really confusing – maybe it should just be an alias for `apm upgrade`?

**EDIT:** It looks like upgrading / updating packages is totally undocumented? https://atom.io/docs/v0.166.0/customizing-atom

```
$ apm update
Installing modules ✗
npm ERR! install Couldn't read dependencies
npm ERR! package.json ENOENT, open '~/package.json'
npm ERR! package.json This is most likely not a problem with npm itself.
npm ERR! package.json npm can't find a package.json file in your current directory.

npm ERR! System Darwin 14.0.0
npm ERR! command "/Applications/Atom.app/Contents/Resources/app/apm/node_modules/atom-package-manager/bin/node" "/Applications/Atom.app/Contents/Resources/app/apm/node_modules/atom-package-manager/node_modules/npm/bin/npm-cli.js" "--globalconfig" "/Applications/Atom.app/Contents/Resources/app/apm/node_modules/atom-package-manager/.apmrc" "--userconfig" "~/.atom/.apmrc" "install" "--target=0.18.0" "--arch=x64"
npm ERR! cwd ~
npm ERR! node -v v0.10.33
npm ERR! npm -v 1.4.4
npm ERR! path ~/package.json
npm ERR! code ENOPACKAGEJSON
npm ERR! errno 34
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     ~/npm-debug.log
npm ERR! not ok code 0
```

**Atom:** 0.166.0

**Comment by kevinsawicki** [comment]
`apm update` was just `apm clean` followed by `apm install`.

This was one of the earliest commands when Atom was just switching to node and rebuilding was really common.  Once things stabilized this command should have been removed since it is unintuitive and seldom used.

I've switched to now do what `apm upgrade` does, update out of date packages.
