### ISSUE TITLE
Can't perform a rebuild

### ISSUE THREAD

**Issue by stramel** [atom/apm#249]
I am working on a new plugin for Atom that has a dependency on [Shouqun/node-dbus][dbus]. When trying to test my application in Atom using the [instructions here][instructions]. It fails on the `apm rebuild` command

```console
$ apm rebuild
<SEE LINK BELOW FOR OUTPUT>
```
https://gist.github.com/stramel/579e6e9375c88007fc3e#file-error-log

[dbus]: https://github.com/Shouqun/node-dbus
[instructions]: https://atom.io/docs/v0.169.0/advanced/node-modules

**Comment by kevinsawicki** [comment]
Do you know if that library compiles against node 0.11? That is the version of node that Atom ships with those looks like v8 errors caused from API changes between node 0.10 and node 0.11.

Libraries typically use https://github.com/rvagg/nan to get things working across those versions.

**Comment by stramel** [comment]
It is compiled against an older version of node.  I will give the repository you suggested a shot. Thanks @kevinsawicki

**Comment by kevinsawicki** [comment]
Thanks, closing this out.
