### ISSUE TITLE
Problem installing my package from apm

### ISSUE THREAD

**Issue by travs** [atom/apm#251]
I'm not sure if this is an issue with my package, apm, or the npm version installed under apm, but there seem to be others who have the same problem.

Someone tried to install my Atom package and it [failed dramatically](https://github.com/travs/markdown-pdf/issues/20#issuecomment-69651673) on installing the dependencies :cry: 

[Someone already raised this](https://github.com/npm/npm/issues/7093) over in the npm repo, but to no avail. Maybe you guys have some insight?

* Changing the underlying npm version ahead of `1.4.4` is mentioned [here](https://github.com/atom/apm/issues/245) but with no real error to motivate it.
* A similar install error is mentioned in #227, but is not linked to a potential problem with the npm version, so I thought I would connect those ideas in this issue.

@kevinsawicki

**Comment by kevinsawicki** [comment]
@travs Thanks for linking to that npm issue.

Based on this comment, https://github.com/npm/npm/issues/7093#issuecomment-69273756 it seems like we should upgrade soon.
