### ISSUE TITLE
a confused problem for atom online update and install package

### ISSUE THREAD

**Issue by Cifer-Y** [atom/apm#254]
atom-version: 0.172
OS: Yosemite 10.10.1

I'm using global pac proxy, suddenly I can't update and install package in atom editor
from yesterday, such as:
  
![untitled - atom atom today at 09 17 30](https://cloud.githubusercontent.com/assets/4470516/5732686/410c1aea-9bd1-11e4-928e-735788e431df.png)

But when I tried `apm install --verbose color-picker`, the package was installed successfully.
So I tried to add `https-proxy =my_pac_address`and `http-proxy = my_pac_address`
to my `~/.atom/.apmrc`, but still bad......I'm very confused....

**Comment by kevinsawicki** [comment]
Does that error display for all packages you try and install from the settings view?

**Comment by Cifer-Y** [comment]
yes, all packages

**Comment by kevinsawicki** [comment]
If you `apm install color-picker` without the `--verbose` option, does it succeed?

**Comment by Cifer-Y** [comment]
Succeed, I tried color-picker and merge-conflict, `apm install` succeed

**Comment by kevinsawicki** [comment]
So are you only configuring your proxy settings via your `~/.atom/.apmrc` file or also via environment variables?

**Comment by Cifer-Y** [comment]
I have a global pac proxy setting for my Wi-Fi，and the terminal is using a start proxy function for proxy.
On regular situation, the proxy will auto work well for atom, it did well before yesterday, so I add the proxy settings in `~/.atom/.apmrc` try to make proxy work well for atom... but I failed

**Comment by kevinsawicki** [comment]
Just curious, are you starting Atom from the terminal, or from the dock?

**Comment by Cifer-Y** [comment]
I start atom from dock

**Comment by kevinsawicki** [comment]
Can you see if it behaves differently if you launch it from the terminal using the `atom` command?

**Comment by Cifer-Y** [comment]
no difference... same behaves

**Comment by Cifer-Y** [comment]
Is my ISP problem? I'am in China, as you know, China is a  magical country.......╮(╯_╰)╭

**Comment by Cifer-Y** [comment]
I will try to change an ISP later,  wait for my news~~~

**Comment by Cifer-Y** [comment]
Okay, jobs done! This issue can be closed. I config global proxy and atom specify proxy again and again, and now it is fine, the true reason still not found, but everything is awesome~~~~

**Comment by kevinsawicki** [comment]
Okay, closing out, thanks for the updates.
