### ISSUE TITLE
apm develop not working on Windows

### ISSUE THREAD

**Issue by AustP** [atom/apm#265]
Last week I used `apm develop` and it worked great. I tried to use it again today `apm develop tree-view` and these are the errors I saw:

	Cloning https://github.com/atom/tree-view mdone
	Installing modules failed
	> runas@1.1.0 install C:\Users\Aust\github\tree-view\node_modules\pathwatcher\node_modules\runas
	> node-gyp rebuild

	C:\Users\Aust\github\tree-view\node_modules\pathwatcher\node_modules\runas>node "c:\Users\Aust\AppData\Local\atom\app-0.174.0\resources\app\apm\node_modules\atom-package-manager\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild 

	npm http GET https://registry.npmjs.org/event-kit
	npm http GET https://registry.npmjs.org/minimatch
	npm http GET https://registry.npmjs.org/fs-plus
	npm http GET https://registry.npmjs.org/pathwatcher
	npm http GET https://registry.npmjs.org/underscore-plus
	npm http GET https://registry.npmjs.org/temp
	npm http GET https://registry.npmjs.org/atom-space-pen-views
	npm http 304 https://registry.npmjs.org/minimatch
	npm http 304 https://registry.npmjs.org/fs-plus
	npm http 304 https://registry.npmjs.org/underscore-plus
	npm http 304 https://registry.npmjs.org/event-kit
	npm http 304 https://registry.npmjs.org/temp
	npm http 304 https://registry.npmjs.org/pathwatcher
	npm http 304 https://registry.npmjs.org/atom-space-pen-views
	npm http GET https://registry.npmjs.org/underscore
	npm http GET https://registry.npmjs.org/mkdirp
	npm http GET https://registry.npmjs.org/rimraf
	npm http GET https://registry.npmjs.org/async
	npm http GET https://registry.npmjs.org/fuzzaldrin
	npm http GET https://registry.npmjs.org/grim
	npm http GET https://registry.npmjs.org/rimraf
	npm http GET https://registry.npmjs.org/space-pen
	npm http 304 https://registry.npmjs.org/underscore
	npm http 304 https://registry.npmjs.org/async
	npm http 304 https://registry.npmjs.org/rimraf
	npm http 304 https://registry.npmjs.org/mkdirp
	npm http 304 https://registry.npmjs.org/rimraf
	npm http GET https://registry.npmjs.org/lru-cache
	npm http GET https://registry.npmjs.org/sigmund
	npm http 304 https://registry.npmjs.org/fuzzaldrin
	npm http 304 https://registry.npmjs.org/space-pen
	npm http 304 https://registry.npmjs.org/sigmund
	npm http 304 https://registry.npmjs.org/lru-cache
	npm http GET https://registry.npmjs.org/nan/1.2.0
	npm http GET https://registry.npmjs.org/emissary
	npm http GET https://registry.npmjs.org/iconv-lite
	npm http GET https://registry.npmjs.org/q
	npm http GET https://registry.npmjs.org/runas
	npm http 304 https://registry.npmjs.org/iconv-lite
	npm http 304 https://registry.npmjs.org/q
	npm http 304 https://registry.npmjs.org/emissary
	npm http 304 https://registry.npmjs.org/grim
	npm http 304 https://registry.npmjs.org/runas
	npm http GET https://registry.npmjs.org/coffeestack
	npm http GET https://registry.npmjs.org/jquery
	npm http 304 https://registry.npmjs.org/coffeestack
	npm http 304 https://registry.npmjs.org/jquery
	npm http 304 https://registry.npmjs.org/nan/1.2.0
	npm http GET https://registry.npmjs.org/coffee-script
	npm http GET https://registry.npmjs.org/source-map
	npm http 304 https://registry.npmjs.org/source-map
	npm http 304 https://registry.npmjs.org/coffee-script
	npm http GET https://registry.npmjs.org/mixto
	npm http GET https://registry.npmjs.org/property-accessors
	gypnpm http 304 https://registry.npmjs.org/property-accessors
	npm http 304 https://registry.npmjs.org/mixto
	npm ERR! Error: ENOENT, lstat 'C:\Users\Aust\github\tree-view\node_modules\pathwatcher\node_modules\iconv-lite\encodings\tables\cp950.json'
	npm ERR! If you need help, you may report this *entire* log,
	npm ERR! including the npm and node versions, at:
	npm ERR!     <http://github.com/npm/npm/issues>

	npm ERR! System Windows_NT 6.1.7601
	npm ERR! command "c:\\Users\\Aust\\AppData\\Local\\atom\\app-0.174.0\\resources\\app\\apm\\node_modules\\atom-package-manager\\bin\\\\node.exe" "c:\\Users\\Aust\\AppData\\Local\\atom\\app-0.174.0\\resources\\app\\apm\\node_modules\\atom-package-manager\\node_modules\\npm\\bin\\npm-cli.js" "--globalconfig" "c:\\Users\\Aust\\AppData\\Local\\atom\\app-0.174.0\\resources\\app\\apm\\node_modules\\atom-package-manager\\.apmrc" "--userconfig" "C:\\Users\\Aust\\.atom\\.apmrc" "install" "--target=0.20.0" "--arch=ia32"
	npm ERR! cwd C:\Users\Aust\github\tree-view
	npm ERR! node -v v0.10.35
	npm ERR! npm -v 1.4.4
	npm ERR! path C:\Users\Aust\github\tree-view\node_modules\pathwatcher\node_modules\iconv-lite\encodings\tables\cp950.json
	npm ERR! fstream_path C:\Users\Aust\github\tree-view\node_modules\pathwatcher\node_modules\iconv-lite\encodings\tables\cp950.json
	npm ERR! fstream_type File
	npm ERR! fstream_class FileWriter
	npm ERR! code ENOENT
	npm ERR! errno 34
	npm ERR! fstream_stack c:\Users\Aust\AppData\Local\atom\app-0.174.0\resources\app\apm\node_modules\atom-package-manager\node_modules\npm\node_modules\fstream\lib\writer.js:284:26
	npm ERR! fstream_stack Object.oncomplete (fs.js:108:15)
	npm http GET https://registry.npmjs.org/amdefine
	npm ERR! runas@1.1.0 install: `node-gyp rebuild`
	npm ERR! Exit status 1
	npm ERR! 
	npm ERR! Failed at the runas@1.1.0 install script.
	npm ERR! This is most likely a problem with the runas package,
	npm ERR! not with npm itself.
	npm ERR! Tell the author that this fails on your system:
	npm ERR!     node-gyp rebuild
	npm ERR! You can get their info via:
	npm ERR!     npm owner ls runas
	npm ERR! There is likely additional logging output above.

	npm ERR! System Windows_NT 6.1.7601
	npm ERR! command "c:\\Users\\Aust\\AppData\\Local\\atom\\app-0.174.0\\resources\\app\\apm\\node_modules\\atom-package-manager\\bin\\\\node.exe" "c:\\Users\\Aust\\AppData\\Local\\atom\\app-0.174.0\\resources\\app\\apm\\node_modules\\atom-package-manager\\node_modules\\npm\\bin\\npm-cli.js" "--globalconfig" "c:\\Users\\Aust\\AppData\\Local\\atom\\app-0.174.0\\resources\\app\\apm\\node_modules\\atom-package-manager\\.apmrc" "--userconfig" "C:\\Users\\Aust\\.atom\\.apmrc" "install" "--target=0.20.0" "--arch=ia32"
	npm ERR! cwd C:\Users\Aust\github\tree-view
	npm ERR! node -v v0.10.35
	npm ERR! npm -v 1.4.4
	npm ERR! code ELIFECYCLE
	npm http 304 https://registry.npmjs.org/amdefine

apm -v output

    apm 0.120.0
    npm 1.4.4
    node 0.10.35
    python
    git 1.9.5.msysgit.0
    visual studio

**Comment by AustP** [comment]
Just tried this again with latest release. Still seeing the issue.

    apm 0.123.0
    npm 2.1.18
    node 0.10.35
    python
    git 1.9.5.msysgit.0
    visual studio

**Comment by kevinsawicki** [comment]
Do you have visual studio and python installed?

**Comment by AustP** [comment]
@kevinsawicki I don't have either installed.

**Comment by kevinsawicki** [comment]
> @kevinsawicki I don't have either installed.

This is probably the issue since `tree-view` has dependencies on libraries that have native code.

**Comment by AustP** [comment]
@kevinsawicki I've intalled Python 3.4.2. Will Visual Studio Express 2013 for Web suffice?

**Comment by kevinsawicki** [comment]
The Atom build requirements are here: https://github.com/atom/atom/blob/master/docs/build-instructions/windows.md#requirements

**Comment by AustP** [comment]
@kevinsawicki Thanks that was the issue. I didn't realize that for developing packages I would need to have the same requirements as building Atom. Perhaps you should add that to CONTRIBUTING.md? Thanks for your help.

**Comment by kevinsawicki** [comment]
>  Perhaps you should add that to CONTRIBUTING.md? 

Good point, there is an `apm install --check` command (I should have mentioned) that checks for native build tools that should probably be mentioned somewhere.
