### ISSUE TITLE
Add --no-dev flag to apm list

### ISSUE THREAD

**Issue by mnquintana** [atom/apm#267]
I just noticed that if you happen to have any Atom packages linked into dev mode, they are listed with `apm list` no matter what you do. This seems like kind of an essential flag to add, because without it, if you wanted to `apm install` from the output of, say, `apm list --installed --bare > my-packages.txt`, then it will always include invalid packages if linked into `dev`.

`apm list -pi`:

![screenshot 2015-01-22 07 30 26](https://cloud.githubusercontent.com/assets/823545/5855663/c8405192-a208-11e4-886b-79b844e2c551.png)

Although we could just add a `--no-dev` flag to *disable* listing dev packages, since the other boolean category flags (`--themes` and `--packages`) selectively *enable* listing dev packages, maybe it should also be an enabling flag? (So `--dev` instead of `--no-dev`) Maybe it makes more sense for it to be `--no-dev`, I'm not sure.

**Comment by kevinsawicki** [comment]
:+1:

**Comment by kevinsawicki** [comment]
Also added support for `apm list --no-links` as well

**Comment by mnquintana** [comment]
Looks awesome, thanks!
