### ISSUE TITLE
Replace optimist?

### ISSUE THREAD

**Issue by mnquintana** [atom/apm#268]
[Optimist has been deprecated for awhile now](https://github.com/substack/node-optimist#deprecation-notice), so it might be a good idea to move apm from optimist to one of its successors: [yargs](https://github.com/chevex/yargs) or [minimist](https://github.com/substack/minimist). (FWIW, yargs is billed as the official successor to optimist and seems much better maintained.)

**Comment by kevinsawicki** [comment]
Yeah, I've been using yargs for new stuff, just haven't updated any old stuff.

atom itself is still using optimist.

**Comment by mnquintana** [comment]
Would you mind if I took a crack at porting it over to yargs?

**Comment by kevinsawicki** [comment]
> Would you mind if I took a crack at porting it (apm) over to yargs?

Yeah, sounds good
