### ISSUE TITLE
Error After Renaming a Package

### ISSUE THREAD

**Issue by vinkla** [atom/apm#269]
As [discussed here](https://discuss.atom.io/t/error-after-renaming-a-theme/13993/7) I had problems renaming my color scheme. I tried to rename it from **broadcast-theme** to **broadcast-color-scheme** but with no success. In the end I renamed it back to its original name and now I want to remove the new one. Please help me remove it.

New: https://atom.io/themes/broadcast-color-scheme

**Comment by thedaniel** [comment]
Cool, I'll remove the old one. How did your package rename fail? Maybe we can get to the bottom of that issue as well.

**Comment by thedaniel** [comment]
Ah, I see from the thread on Discuss, this happened a few weeks ago. I understand if you don't recall the exact mechanism of the failure. On the bright side there have been some improvements to publishing since then, so maybe it's already been fixed ;)

**Comment by vinkla** [comment]
I renamed the repository here on GitHub then in the `package.json` file. Tried to publish it like before but it created a second one instead. Is it possible to rename a package or should it create a new one? Just asking if I ever try something similar in the future. I mean, if I've a package that needs to be renamed I don't want to lose the downloads or break it for current users.

**Comment by thedaniel** [comment]
yes, you can use `apm publish --rename` - see `apm help publish` for details

**Comment by vinkla** [comment]
Great. Thanks. I'll try it out!
