### ISSUE TITLE
apm install --production

### ISSUE THREAD

**Issue by reggi** [atom/apm#270]
Hey all I'm having trouble apm install is download dev-deps to my atom-shell app, how can I only install deps?

[From npm](https://docs.npmjs.com/cli/install)

> By default, npm install will install all modules listed as dependencies. With the --production flag, npm will not install modules listed in devDependencies.

**Comment by kevinsawicki** [comment]
Yeah, this option isn't support yet, but definitely should be added.

**Comment by reggi** [comment]
This does the same thing I guess `npm install -s --production && apm rebuild`
