### ISSUE TITLE
[Website] stars is case sensitive

### ISSUE THREAD

**Issue by ReactiveRaven** [atom/apm#273]
The stars api appears to be case sensitive, but github is not.

https://atom.io/users/reactiveraven/stars

https://atom.io/users/ReactiveRaven/stars

http://github.com/reactiveraven

http://github.com/ReactiveRaven

This lead to confusion when I was unable to pull new stars with `apm stars` on command line, which has since resolved itself and was most likely a caching issue.

**Comment by thedaniel** [comment]
That page is now case-insensitive. At some point in the near future I'll update it to make sure it uses the user-provided casing regardless of how the URL is capitalized (at the moment it just takes the URL param and throws it in the HTML)
