### ISSUE TITLE
Installing specific version / updating

### ISSUE THREAD

**Issue by Larivact** [atom/apm#275]
How do I
-install a specific version of apm?
-update to the latest version of apm?
Do I have to build it myself?

**Comment by thedaniel** [comment]
Atom editor updates should take care of keeping your apm up-to-date. If you want an old version and *really* don't want to build it yourself, [it's also on npm](https://www.npmjs.com/package/atom-package-manager)

**Comment by Larivact** [comment]
@thedaniel I installed the newest version of atom-editor. I got apm 0.123.0, correct me if I am wrong but the current version of apm is 0.127.0; and ```npm install -g atom-package-manager``` broke my apm
