### ISSUE TITLE
Error while installing

### ISSUE THREAD

**Issue by XadillaX** [atom/apm#276]
```bat
C:\Users\XadillaX>apm install vim-mode
Installing vim-mode to C:\Users\XadillaX\.atom\packages
gyp info it worked if it ends with ok
gyp info using node-gyp@1.0.2
gyp info using node@0.10.35 | win32 | ia32
gyp http GET http://127.0.0.1/atom-shell/dist/v0.20.0/node-v0.20.0.tar.gz
gyp http 200 http://127.0.0.1/atom-shell/dist/v0.20.0/node-v0.20.0.tar.gz
gyp
```

Above is all message.

```bat
C:\Users\XadillaX>apm -v
apm  0.123.0
npm  2.1.18
node 0.10.35
python 2.7.5
git 1.8.1.msysgit.1
visual studio 2012
```

> Because I'm in China, I download `node-v0.20.0.tar.gz` manually and let it be in http://127.0.0.1/atom-shell/dist/v0.20.0/node-v0.20.0.tar.gz.

**Comment by kevinsawicki** [comment]
I think you also need to host the `node.lib` file locally as well.

**Comment by kevinsawicki** [comment]
Closing this out, you might want to check out https://github.com/atom/apm/issues/174 for more details about using apm in China.
