### ISSUE TITLE
[Website] Show latest version release date for package detail on atom.io

### ISSUE THREAD

**Issue by mnquintana** [atom/apm#277]
It would be really helpful to show the release date for the latest version of a package on atom.io (or if not a date, time since the last release). This would make it a little easier to weed out packages that might not be maintained anymore. Maybe something like:

![screenshot 2015-01-26 18 36 38](https://cloud.githubusercontent.com/assets/823545/5910656/7c62e0b6-a58a-11e4-864c-0905544a387a.png)

**Comment by thedaniel** [comment]
I think that's pretty noisy in the package card, but it should definitely be on the detail page.

**Comment by thedaniel** [comment]
What if we put a date in a tooltip on the version number in the card?

**Comment by mnquintana** [comment]
Oops sorry, I realized that after I posted this. I meant on the detail page (the screenshot is from the detail page too).

**Comment by mnquintana** [comment]
@thedaniel That would be okay, but IMO the benefit of showing the date would be making it obvious / explicit at a glance when the last release happened, and making it a tooltip would make it not very obvious or explicit. I think there is enough whitespace in that stats row to keep it from looking too cluttered, but only on the detail page.

**Comment by zephraph** [comment]
I think showing the last updated date is pretty important. Seeing the version and downloads is great because it gives you a sense of maturity and popularity. It doesn't tell you the age of a package though. 

For example, I was looking for a terminal package the other day. There are several of them out there, but most of them are really dated and no longer work. The only way I found that out was because I took the time to install the packages, realized something didn't work, and then navigated to the GitHub page (where I could see it wasn't updated for x number of months). 

_When a package was last updated is an incredibly important statistic to me._

Personally, I like @mnquintana's mock up. I'd like to see it exactly like that. @thedaniel have you given this any more thought?

**Comment by thedaniel** [comment]
I haven't looked at it, I've been at HQ all week doing a bunch of planning
& meetings and non-coding work. Next week I plan to pick up all these
dropped threads and get to codin' and mergin'

**Comment by zephraph** [comment]
I created a sister issue for this in settings-view. I really, really think this would be useful man.

**Comment by thedaniel** [comment]
I really don't think this is important enough to be present in the package card as Atom stabilizes. How would you feel about replacing "latest version" with the publish date in the tooltip though?

**Comment by mnquintana** [comment]
@thedaniel I mean, I think that would certainly be better than nothing, but I strongly disagree that it isn't important enough to add to the package card. If you are looking for a new package, regardless of what it is, I think you always want to know at least the following:

- If it's any good (quality)
- If it's maintained

Right now, you can get a sense of "quality" by glancing at the downloads count (presumably if it's "popular" enough it doesn't suck, right?), but there is absolutely no way of knowing if a package is maintained right now from atom.io – you're going in completely blind. The only way is to click on Repo or Versions and shift context to GitHub. In fact, I would argue that showing the time since a package was last updated is actually more valuable than showing the version number, since the version number alone doesn't tell you anything about quality or if it's maintained (but I do think both should be shown). 

I'm all for reducing visual noise, but I don't think this would be adding noise, just value, and value that wouldn't quite be there if this were tucked away in an on-hover tooltip (since it should be as obvious as possible). I think we should be careful about just adding new things to the package card left and right, but I don't think this is necessarily going down a slippery slope of cluttering up the package card in the future.

**Comment by zephraph** [comment]
I completely agree with this. I was installing packages that hadn't been updated in forever and things were breaking. This would give _necessary_ visibility into the overall health of the package.

**Comment by thedaniel** [comment]
This issue was moved to atom/atom.io#10
