### ISSUE TITLE
Can't seem to get the apm command to work on Windows.

### ISSUE THREAD

**Issue by KamranMackey** [atom/apm#278]
There isn't any "Install Shell Commands" option in the Atom Windows build, and I was wondering how I add the "apm" and "atom" commands to my PATH.

**Comment by kevinsawicki** [comment]
If you installed Atom using the installer, it should be automatically added to to your path.

How did you install Atom?

**Comment by KamranMackey** [comment]
I installed Atom by installing it from source.

**Comment by kevinsawicki** [comment]
> I installed Atom by installing it from source.

Then you have to manually add it to your path if you want to use it from the command line.

**Comment by KamranMackey** [comment]
How do I add it to my PATH?

**Comment by kevinsawicki** [comment]
Add `ROOT_ATOM_DIRECTORY\resources\app\apm\bin` to your path, substitute the directory you installed Atom into for the `ROOT_ATOM_DIRECTORY` portion, such as `C:\Program Files\Atom`.

http://www.computerhope.com/issues/ch000549.htm for more details

**Comment by KamranMackey** [comment]
System path or user path?

**Comment by kevinsawicki** [comment]
User path

**Comment by KamranMackey** [comment]
I just did that, but it still says that apm isn't recognized. :disappointed:

**Comment by kevinsawicki** [comment]
Did you restart the command prompt?

**Comment by KamranMackey** [comment]
I never even had the command prompt open when I added apm to my path.

**Comment by kevinsawicki** [comment]
If you switch to the installer it will automatically add it for you, that is what I would recommend if you are unable to manually set it.

**Comment by KamranMackey** [comment]
Maybe if I restart Windows Explorer it might work? If that doesn't work then I'll just restart my computer.

**Comment by KamranMackey** [comment]
@kevinsawicki Okay, looks like the Atom Package Manager works now. I just had to restart my computer. Thanks a lot, Kevin! :smiley:

**Comment by kevinsawicki** [comment]
Awesome, glad to hear things are working now.

**Comment by KamranMackey** [comment]
Yeah, they are. Although it would be really nice if I could "Like" or "Star" your comments, Kevin...but it looks like GitHub hasn't added in that functionality yet. :disappointed: 

P.S. I know this comment is off-topic, but I just wanted throw that out there. :smile:

**Comment by igorpupkinable** [comment]
In case somebody needs this for newer Atom versions, the path to add is `ROOT_ATOM_DIRECTORY\resources\cli`
