### ISSUE TITLE
apm update do nothing and never terminate

### ISSUE THREAD

**Issue by abe33** [atom/apm#286]
I think this issue started at the end of the past week, neither `apm update` nor `apm upgrade` works for me. 
The commands starts and never terminate. I mean I can leave them for hours and I'll never get any output, and the command never exit. I think I had once a `socket hang up` error appearing, but only once doesn't help here to be sure that this is the issue.
What's weird is that some other commands like `apm starred` or `apm publish` that needs to be logged works - even if `publish` seems to suffer of the same problem from time to time - so its not an issue with me not being logged in `apm`.
The `apm install` command is also working properly.
Obviously it also affect Atom as I'm no longer notified of updates. The settings view is completely mute as well, no errors, just the `Checking for updates...` notification that stay here indefinitely.

I build Atom from the source everyday. I don't know if it can play here but it's worth mentioning. 
I'm currently running `0.178.0-4a17b4e`.

**Environment**

I'm running OSX 10.10.2.

Running `apm -v` gives: 

```
apm  0.134.0
npm  2.3.0
node 0.10.35
python 2.7.6
git 2.2.1
```

I didn't find any mention of a verbose option to get more output from `apm`. What can I try to debug this?

**Comment by kevinsawicki** [comment]
Are you using a proxy? Either via your `~/.atom/.apmrc` file or via proxy environment variables?

**Comment by abe33** [comment]
No, no proxy environment, no `.apmrc` file. I've also checked my firewall, but I didn't changed anything recently.

I must say I have this issue only at home, what can I try to test if it's an issue with my connection?

**Comment by kevinsawicki** [comment]
>  what can I try to test if it's an issue with my connection?

Does `apm featured` complete in a reasonable amount of time?

**Comment by kevinsawicki** [comment]
I just pushed a `--verbose` option to `apm upgrade`.

So if you want to clone this repo, run `npm install`, run `grunt`, then run `bin/apm upgrade --verbose` you should see lots of output as requests are made.

**Comment by abe33** [comment]
Ok, so, yesterday everything was working fine again, I just doesn't understand what happened during these few days.
If the situation occurs again I'll make sure to monitor my computer traffic and to use `--verbose`.

Thank you for the time you spent on this and sorry for the bother. I'll close this for now.
