### ISSUE TITLE
Package install fails

### ISSUE THREAD

**Issue by olmokramer** [atom/apm#289]
I'm getting this error: `No available version compatible with the installed Atom version: 0.177.0` after I ran `apm install distraction-free-mode`. I am indeed on Atom v0.177.0, and the `distraction-free-mode`s `package.json` has:
```json
"engines": {
  "atom": ">=0.174.0, <2.0.0"
}
```
So my version of atom should be compatible with the package and apm should install it. Installing it through the settings view in atom worked fine, though.

**Comment by izuzak** [comment]
It's a problem with the semver which is validated by apm, should be fixed by https://github.com/braver/distraction-free-mode/pull/1.

**Comment by olmokramer** [comment]
Good to know. Thanks for the information :)
