### ISSUE TITLE
engines.atom semver not validated before publishing a version of a package

### ISSUE THREAD

**Issue by izuzak** [atom/apm#291]
It's possible to publish a package version with an invalid `engines.atom` semver in the package.json, which causes problems like these https://github.com/atom/atom/pull/5417.

Wondering if we could+should validate that semver while publishing a package version (and perhaps other semvers listed in package.json?) and block publishing if the semver is invalid. :thought_balloon:

**Comment by kevinsawicki** [comment]
Sounds good
