### ISSUE TITLE
apm install error - plain npm works

### ISSUE THREAD

**Issue by mensinda** [atom/apm#294]
I want to write a plugin for atom and have a [dependency](https://github.com/saneki/node-toxcore/). Unfortunately [ffi](https://github.com/node-ffi/node-ffi/) (a subdependency) fails to build with apm while `npm install ffi` works.

As far as I know apm calls npm with some command line options, setting the chromium headers. Is it possible to use the default headers?

apm  0.136.0
npm  2.3.0
node 0.10.35
python 2.7.9
git 2.3.0

OS: Arch Linux (3.18.6-1-ARCH)

**Comment by kevinsawicki** [comment]
>  Is it possible to use the default headers?

For a native library to load within Atom or Atom Shell, it needs to be compiled against the v8 headers that Atom Shell ships with.

Can you include the output of the build error you are seeing?

**Comment by mensinda** [comment]
The compile error: https://gist.github.com/mensinda/7445c13f9b21ac2e5ce4

**Comment by kevinsawicki** [comment]
Looks like an issue with the [nan](https://github.com/rvagg/nan) version being used.

I think this might be addressed once https://github.com/rvagg/nan/pull/276 ships.

**Comment by mensinda** [comment]
Upgrading nan fixed some compile errors but compiling ffi still [fails](https://gist.github.com/mensinda/3f51326616be5e26c5a2).

It seems to be a ffi issue.

**Comment by paulcbetts** [comment]
@mensinda To work around this, I created some temporary npm packages:

* ffi-atom-shell
* ref-atom-shell
* ref-struct-atom-shell
* ref-array-atom-shell

**Comment by mensinda** [comment]
@paulcbetts Thank you! Your packages are working for me.
