### ISSUE TITLE
Package: The tern dependency range in the package.json file is invalid:

### ISSUE THREAD

**Issue by izuzak** [atom/apm#295]
_From @tststs on February 12, 2015 9:45_

I used to get a dependency for a package i'm working on via
<code>"tern": "git://github.com/marijnh/tern.git"</code>

There seems to be no way since 0.177 to publish a package with this type of dependency.
<code>The tern dependency range in the package.json file is invalid: git://github.com/marijnh/tern</code>

Per design or issue?

thx
tststs

_Copied from original issue: atom/atom#5513_

**Comment by izuzak** [comment]
Ahhh, I think I see what's causing problems for you -- as of [recently](https://github.com/atom/apm/pull/292), apm verifies that the semvers used in package.json are valid.

However, a dependency might be defined as a URL and a bunch of other things (I totally forgot about that):

https://docs.npmjs.com/files/package.json#dependencies

/cc @kevinsawicki

**Comment by MayhemYDG** [comment]
https://docs.npmjs.com/files/package.json#dependencies
I hope apm will support ALL types of valid dependencies at some point like npm?

**Comment by kevinsawicki** [comment]
> I hope apm will support ALL types of valid dependencies at some point like npm?

I believe it should

**Comment by basarat** [comment]
> I believe it should

But it doesn't. ref https://github.com/TypeStrong/atom-typescript/issues/163

**Comment by jordanbtucker** [comment]
URLs in the form of `github:user/repo` work. The `github:` protocol is required. See https://github.com/atom/apm/blob/v1.1.1/src/publish.coffee#L300
