### ISSUE TITLE
Upgrade to at least npm 2.5.1

### ISSUE THREAD

**Issue by LoneBoco** [atom/apm#296]
There was a regression in npm 2.3.0 that lead to it ignoring the various SSL parameters, so anybody that relied on specifying a custom CA, cert, key, disabling certificate checking, and possibly even using a proxy have been having issues installing packages.  This was fixed in npm 2.5.1, so it would be great if apm could upgrade the version of npm it uses.

**Comment by kevinsawicki** [comment]
Thanks for mentioning this, 2.5.1 will be included in the next Atom release, 0.180
