### ISSUE TITLE
package.json github dependency broken

### ISSUE THREAD

**Issue by mark-hahn** [atom/apm#301]
*This is somewhat important as I can't publish my package ...*

This is my package.json file ...

```
{
  "name": "view-tail-large-files",
  "main": "./lib/view-tail-large-files",
  "version": "0.1.11",
  "description": "View and tail files of any size.",
  "activationEvents": [],
  "repository": "https://github.com/mark-hahn/view-tail-large-files",
  "license": "MIT",
  "engines": {
    "atom": ">0.170.0"
  },
  "dependencies": {
    "fs-plus":           ">2.0.0",
    "underscore":        "^1.7.0",
    "underscore.string": "^2.3.3",
    "event-kit":         "^0.7.2",
    "emissary":          "^1.3.1",
    
    "vtlf-file-picker":  "mark-hahn/vtlf-file-picker#0.1.3",
    "vtlf-auto-open":    "mark-hahn/vtlf-auto-open#0.1.0",
    "vtlf-tail":         "mark-hahn/vtlf-tail#0.1.3"
  }
}

```

Each of these github dependency formats gives an error when I do `apm publish --tag 0.1.11`.  The first one has worked in the past and just now broke.

    The vtlf-file-picker dependency range in the package.json file is invalid: mark-hahn/vtlf-file-picker#0.1.3
    The vtlf-file-picker dependency range in the package.json file is invalid: mark-hahn/vtlf-file-picker
    The vtlf-file-picker dependency range in the package.json file is invalid: git://github.com/mark-hahn/vtlf-file-picker.git

windows 8,1
apm  0.137.0
npm  2.3.0
node 0.10.35
python 2.7.9
git 1.9.5.msysgit.0
visual studio 2013

Also, doing an npm update worked.

**Comment by mark-hahn** [comment]
Also, doing an `npm update` worked.

**Comment by mark-hahn** [comment]
closed in favor of https://github.com/atom/apm/issues/302

**Comment by basarat** [comment]
This flavor of dependency is still broken

**Comment by mark-hahn** [comment]
See #302.
