### ISSUE TITLE
Cannot unpublish package

### ISSUE THREAD

**Issue by xlaywan** [atom/apm#304]
The first publication was interrupted by the error. And now i cannot both unpublish package and push new version. On github repo is exists, but on atom.io there is only name, but not a readme and other files.

Package visible on atom.io but doesn't in Settings View -> Install.

Now I tried to create a new package, publish and unpublish were successful. Can someone manually remove transpiler package? I'll try to publish once more.

```
> apm unpublish
Are you sure you want to unpublish transpiler? (yes) yes
Unpublishing transpiler failed
connect ETIMEDOUT
```

```
> apm unpublish -f
Unpublishing transpiler failed
Unpublishing failed: Unauthorized
```

**Comment by thedaniel** [comment]
I'd ideally like to get to the bottom of this error but I will unpublish the package now. If this happens again, reopen the issue and we'll try to investigate further.

**Comment by xlaywan** [comment]
Again.

I deleted old repo from github. I deleted .git directory from project.
git init, add, commit, remote add, push
apm publish

```
> apm publish minor
Registering transpiler done
Preparing and tagging a new version done
Pushing v0.1.0 tag Username for 'https://github.com': xlaywan
Password for 'https://xlaywan@github.com':
done
Publishing transpiler@v0.1.0 failed
Creating new version failed: Not found
```

win7
apm  0.137.0
npm  2.3.0
node 0.10.35
python
git 1.9.5.msysgit.0
visual studio
