### ISSUE TITLE
Cannot install a package on Windows 8.1

### ISSUE THREAD

**Issue by kotfilemon** [atom/apm#306]
Hello,

I am having problems with installing anything on my windows 8.1 box with apm.

My setup: Python 2.6 (but also tried with 2.7), git, Visual Studio 2013. I tried installing with

a) setting switch --msvs_version=2013
b) setting variable to set VCTargetsPath=C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V120

Please, see the output:

C:\>apm install api-blueprint-preview 

 runas@1.1.0 install C:\Users\MM~1\AppData\Local\Temp\apm-install-dir-11511
8-12708-1q9i926\node_modules\api-blueprint-preview\node_modules\pathwatcher\node
_modules\runas
 node-gyp rebuild

C:\Users\MM~1\AppData\Local\Temp\apm-install-dir-115118-12708-1q9i926\node_m
odules\api-blueprint-preview\node_modules\pathwatcher\node_modules\runas>node "C
:\Users\mm\AppData\Local\atom\app-0.179.0\resources\app\apm\node_modules\
npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild
Building the projects in this solution one at a time. To enable parallel build,
please add the "/m" switch.
  main.cc
  runas_win.cc
C:\Users\mm\AppData\Local\Temp\apm-install-dir-115118-12708-1q9i926\node_
modules\api-blueprint-preview\node_modules\pathwatcher\node_modules\nan\nan.h(62
3): error C2039: 'ExternalAsciiStringResource' : is not a member of 'v8::String'
 (..\src\main.cc) [C:\Users\mm\AppData\Local\Temp\apm-install-dir-115118-
12708-1q9i926\node_modules\api-blueprint-preview\node_modules\pathwatcher\node_m
odules\runas\build\runas.vcxproj]
          C:\Users\mm\.atom\.node-gyp\.node-gyp\0.21.0\deps\v8\include\v8
.h(1809) : see declaration of 'v8::String'
C:\Users\mm\AppData\Local\Temp\apm-install-dir-115118-12708-1q9i926\node_
modules\api-blueprint-preview\node_modules\pathwatcher\node_modules\nan\nan.h(62
3): error C2065: 'ExternalAsciiStringResource' : undeclared identifier (..\src\m
ain.cc) [C:\Users\mm\AppData\Local\Temp\apm-install-dir-115118-12708-1q9i
926\node_modules\api-blueprint-preview\node_modules\pathwatcher\node_modules\run
as\build\runas.vcxproj]
C:\Users\mm\AppData\Local\Temp\apm-install-dir-115118-12708-1q9i926\node_
modules\api-blueprint-preview\node_modules\pathwatcher\node_modules\nan\nan.h(62
3): error C2065: 'resource' : undeclared identifier (..\src\main.cc) [C:\Users\m
makowski\AppData\Local\Temp\apm-install-dir-115118-12708-1q9i926\node_modules\ap
i-blueprint-preview\node_modules\pathwatcher\node_modules\runas\build\runas.vcxp
roj]
C:\Users\mm\AppData\Local\Temp\apm-install-dir-115118-12708-1q9i926\node_
modules\api-blueprint-preview\node_modules\pathwatcher\node_modules\nan\nan.h(62
3): error C2448: 'NanNew' : function-style initializer appears to be a function
definition (..\src\main.cc) [C:\Users\mm\AppData\Local\Temp\apm-install-d
ir-115118-12708-1q9i926\node_modules\api-blueprint-preview\node_modules\pathwatc
her\node_modules\runas\build\runas.vcxproj]
C:\Users\mm\AppData\Local\Temp\apm-install-dir-115118-12708-1q9i926\node_
modules\api-blueprint-preview\node_modules\pathwatcher\node_modules\nan\nan.h(67
2): warning C4244: 'return' : conversion from 'int64_t' to 'int', possible loss
of data (..\src\main.cc) [C:\Users\mm\AppData\Local\Temp\apm-install-dir-
115118-12708-1q9i926\node_modules\api-blueprint-preview\node_modules\pathwatcher
\node_modules\runas\build\runas.vcxproj]
C:\Users\mm\AppData\Local\Temp\apm-install-dir-115118-12708-1q9i926\node_
modules\api-blueprint-preview\node_modules\pathwatcher\node_modules\nan\nan.h(19
93): error C2039: 'IsExternalAscii' : is not a member of 'v8::String' (..\src\ma
in.cc) [C:\Users\mm\AppData\Local\Temp\apm-install-dir-115118-12708-1q9i9
26\node_modules\api-blueprint-preview\node_modules\pathwatcher\node_modules\runa
s\build\runas.vcxproj]
          C:\Users\mm\.atom\.node-gyp\.node-gyp\0.21.0\deps\v8\include\v8
.h(1809) : see declaration of 'v8::String'
C:\Users\mm\AppData\Local\Temp\apm-install-dir-115118-12708-1q9i926\node_
modules\api-blueprint-preview\node_modules\pathwatcher\node_modules\nan\nan.h(19
94): error C2039: 'ExternalAsciiStringResource' : is not a member of 'v8::String
' (..\src\main.cc) [C:\Users\mm\AppData\Local\Temp\apm-install-dir-115118
-12708-1q9i926\node_modules\api-blueprint-preview\node_modules\pathwatcher\node_
modules\runas\build\runas.vcxproj]
          C:\Users\mm\.atom\.node-gyp\.node-gyp\0.21.0\deps\v8\include\v8
.h(1809) : see declaration of 'v8::String'
C:\Users\mm\AppData\Local\Temp\apm-install-dir-115118-12708-1q9i926\node_
modules\api-blueprint-preview\node_modules\pathwatcher\node_modules\nan\nan.h(19
94): error C4430: missing type specifier - int assumed. Note: C++ does not suppo
rt default-int (..\src\main.cc) [C:\Users\mm\AppData\Local\Temp\apm-insta
ll-dir-115118-12708-1q9i926\node_modules\api-blueprint-preview\node_modules\path
watcher\node_modules\runas\build\runas.vcxproj]
C:\Users\mm\AppData\Local\Temp\apm-install-dir-115118-12708-1q9i926\node_
modules\api-blueprint-preview\node_modules\pathwatcher\node_modules\nan\nan.h(19
94): error C2143: syntax error : missing ';' before '*' (..\src\main.cc) [C:\Use
rs\mm\AppData\Local\Temp\apm-install-dir-115118-12708-1q9i926\node_module
s\api-blueprint-preview\node_modules\pathwatcher\node_modules\runas\build\runas.
vcxproj]
C:\Users\mm\AppData\Local\Temp\apm-install-dir-115118-12708-1q9i926\node_
modules\api-blueprint-preview\node_modules\pathwatcher\node_modules\nan\nan.h(19
94): error C2065: 'ext' : undeclared identifier (..\src\main.cc) [C:\Users\mmako
wski\AppData\Local\Temp\apm-install-dir-115118-12708-1q9i926\node_modules\api-bl
ueprint-preview\node_modules\pathwatcher\node_modules\runas\build\runas.vcxproj]

C:\Users\mm\AppData\Local\Temp\apm-install-dir-115118-12708-1q9i926\node_
modules\api-blueprint-preview\node_modules\pathwatcher\node_modules\nan\nan.h(19
95): error C2065: 'ext' : undeclared identifier (..\src\main.cc) [C:\Users\mmako
wski\AppData\Local\Temp\apm-install-dir-115118-12708-1q9i926\node_modules\api-bl
ueprint-preview\node_modules\pathwatcher\node_modules\runas\build\runas.vcxproj]

C:\Users\mm\AppData\Local\Temp\apm-install-dir-115118-12708-1q9i926\node_
modules\api-blueprint-preview\node_modules\pathwatcher\node_modules\nan\nan.h(19
95): error C2039: 'GetExternalAsciiStringResource' : is not a member of 'v8::Str
ing' (..\src\main.cc) [C:\Users\mm\AppData\Local\Temp\apm-install-dir-115
118-12708-1q9i926\node_modules\api-blueprint-preview\node_modules\pathwatcher\no
de_modules\runas\build\runas.vcxproj]
          C:\Users\mm\.atom\.node-gyp\.node-gyp\0.21.0\deps\v8\include\v8
.h(1809) : see declaration of 'v8::String'
C:\Users\mm\AppData\Local\Temp\apm-install-dir-115118-12708-1q9i926\node_
modules\api-blueprint-preview\node_modules\pathwatcher\node_modules\nan\nan.h(19
96): error C2065: 'ext' : undeclared identifier (..\src\main.cc) [C:\Users\mmako
wski\AppData\Local\Temp\apm-install-dir-115118-12708-1q9i926\node_modules\api-bl
ueprint-preview\node_modules\pathwatcher\node_modules\runas\build\runas.vcxproj]

C:\Users\mm\AppData\Local\Temp\apm-install-dir-115118-12708-1q9i926\node_
modules\api-blueprint-preview\node_modules\pathwatcher\node_modules\nan\nan.h(19
96): error C2227: left of '->data' must point to class/struct/union/generic type
 (..\src\main.cc) [C:\Users\mm\AppData\Local\Temp\apm-install-dir-115118-
12708-1q9i926\node_modules\api-blueprint-preview\node_modules\pathwatcher\node_m
odules\runas\build\runas.vcxproj]
          type is 'unknown-type'
C:\Users\mm\AppData\Local\Temp\apm-install-dir-115118-12708-1q9i926\node_
modules\api-blueprint-preview\node_modules\pathwatcher\node_modules\nan\nan.h(19
97): error C2065: 'ext' : undeclared identifier (..\src\main.cc) [C:\Users\mmako
wski\AppData\Local\Temp\apm-install-dir-115118-12708-1q9i926\node_modules\api-bl
ueprint-preview\node_modules\pathwatcher\node_modules\runas\build\runas.vcxproj]

C:\Users\mm\AppData\Local\Temp\apm-install-dir-115118-12708-1q9i926\node_
modules\api-blueprint-preview\node_modules\pathwatcher\node_modules\nan\nan.h(19
97): error C2227: left of '->length' must point to class/struct/union/generic ty
pe (..\src\main.cc) [C:\Users\mm\AppData\Local\Temp\apm-install-dir-11511
8-12708-1q9i926\node_modules\api-blueprint-preview\node_modules\pathwatcher\node
_modules\runas\build\runas.vcxproj]
          type is 'unknown-type'

gypnpm ERR! Windows_NT 6.2.9200
npm ERR! argv "C:\\Users\\mm\\AppData\\Local\\atom\\app-0.179.0\\resource
s\\app\\apm\\bin\\\\node.exe" "C:\\Users\\mm\\AppData\\Local\\atom\\app-0
.179.0\\resources\\app\\apm\\node_modules\\npm\\bin\\npm-cli.js" "--globalconfig
" "C:\\Users\\mm\\.atom\\.apm\\.apmrc" "--userconfig" "C:\\Users\\mmakows
ki\\.atom\\.apmrc" "install" "C:\\Users\\MM~1\\AppData\\Local\\Temp\\d-11511
8-12708-hu4qvd\\package.tgz" "--target=0.21.0" "--arch=ia32" "--msvs_version=201
3"
npm ERR! node v0.10.35
npm ERR! npm  v2.3.0
npm ERR! code ELIFECYCLE

npm ERR! runas@1.1.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the runas@1.1.0 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the runas package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls runas
npm ERR! There is likely additional logging output above.

**Comment by kevinsawicki** [comment]
This is an issue in that package, it needs to upgrade this line to be `^3.3.1` instead of `~2.0.7`.

https://github.com/danielgtaylor/atom-api-blueprint-preview/blob/9e3948f5a58fe571aa7fb0eddd99d5a0502e2126/package.json#L13

I would recommend opening an issue or pull request on that package's repo: https://github.com/danielgtaylor/atom-api-blueprint-preview/issues/new

**Comment by kotfilemon** [comment]
Please, reopen.

Upgrading to ^3.3.1 didnot help
