### ISSUE TITLE
grammar created using apm is not compatible with lightshow

### ISSUE THREAD

**Issue by thorade** [atom/apm#307]
I used apm to convert a TextMate Bundle into an atom package as described here:
https://atom.io/docs/latest/converting-a-text-mate-bundle
The resulting package is here:
https://github.com/thorade/atom-language-modelica3
It works nicely in Atom, but when I try to use it with Lightshow, it fails:
https://github.com/thorade/atom-language-modelica3/issues/1
http://bit.ly/1ANxWUe

How much work would it be to make sure apm converted packages for syntax highlighting are compatible with Lightshow? Easy? Out of scope?
Or should I file an issue with Lightshow?

**Comment by kevinsawicki** [comment]
Looks like Lightshow only detects CSON based grammars if they start with a `'` or `"` character,

I forked your repo and updated the grammar to start with a `'` and it appears to work:

https://github-lightshow.herokuapp.com/?utf8=%E2%9C%93&scope=from-url&grammar_url=https%3A%2F%2Fgithub.com%2Fkevinsawicki%2Fatom-language-modelica3%2Fblob%2Fmaster%2Fgrammars%2Fmodelica.cson&grammar_text=&code_source=from-url&code_url=https%3A%2F%2Fgithub.com%2Fmodelica%2FModelica%2Fblob%2Frelease%2FModelica%25203.2.1%2FElectrical%2FAnalog%2FLines.mo&code=

https://github.com/kevinsawicki/atom-language-modelica3/blob/81fe4602175eefc178b88d8dbde3d6f8186cdafc/grammars/modelica.cson#L1

**Comment by thorade** [comment]
Thanks for fixing that. If you send me a Pull Request I'll merge it.
Do you think it is possible to also change apm so that it inserts these single quotes automatically?
Or is it Lightshow that needs fixing?

**Comment by kevinsawicki** [comment]
> Do you think it is possible to also change apm so that it inserts these single quotes automatically?

Probably not, I think consistency is important and since some properties (like those containing a `-`) will need it, it is nice to consistently have it.

> Or is it Lightshow that needs fixing?

Lightshow could definitely do a better job detecting CSON/JSON files.

**Comment by thorade** [comment]
Does Lightshow have an issue tracker?
Closing this issue here, but would like to file an issue with Lightshow instead.
