### ISSUE TITLE
cannot modify the .apmrc file

### ISSUE THREAD

**Issue by T0T4R4** [atom/apm#308]
After installing atom via Chocolatey in Windows (7), each time atom is launched it overwrites the 
.atom/.apm/.apmrc 
file, thus making impossible any configuration changes.

This is particularly annoying when behind a proxy as browsing packages do not work.

Quick solution is to make this file ReadOnly but this should be fixed.

Thanks

**Comment by kevinsawicki** [comment]
Your local config file is `~/.atom/.apmrc`, the global config file is `~/.atom/.apm/.apmrc`.

You need to edit `~/.atom/.apmrc` instead.
