### ISSUE TITLE
Installing of packages failed

### ISSUE THREAD

**Issue by michaelkrnac** [atom/apm#309]
Atom 0.182.0
Windows 7

When i try to install any package atom outputs:
```
Installing “minimap@4.3.1” failed.Show output…
Compiler tools not found
Packages that depend on modules that contain C/C++ code will fail to install.
Read here for instructions on installing Python and Visual Studio.
Run apm install --check after installing to test compiling a native module.
```

apm install --check outputs:

```
C:\Users\mkrnac>apm install --check
Checking for native build tools
c:\Users\mkrnac\AppData\Local\atom\app-0.182.0\resources\app\apm\lib\install.js:77
      useStrictSsl = (_ref = this.npm.config.get('strict-ssl')) != null ? _ref
                                     ^
TypeError: Cannot read property 'config' of undefined
    at Install.module.exports.Install.installNode (c:\Users\mkrnac\AppData\Local\atom\app-0.182.0\resources\app\apm\lib\install.js:77:38)
    at Install.installNode (c:\Users\mkrnac\AppData\Local\atom\app-0.182.0\resources\app\apm\lib\install.js:3:61)
    at Install.module.exports.Install.checkNativeBuildTools (c:\Users\mkrnac\AppData\Local\atom\app-0.182.0\resources\app\apm\lib\install.js:559:19)
    at Install.module.exports.Install.run (c:\Users\mkrnac\AppData\Local\atom\app-0.182.0\resources\app\apm\lib\install.js:724:21)
    at Object.module.exports.run (c:\Users\mkrnac\AppData\Local\atom\app-0.182.0\resources\app\apm\lib\apm-cli.js:209:32)
    at Object.<anonymous> (c:\Users\mkrnac\AppData\Local\atom\app-0.182.0\resources\app\apm\lib\cli.js:6:7)
    at Object.<anonymous> (c:\Users\mkrnac\AppData\Local\atom\app-0.182.0\resources\app\apm\lib\cli.js:17:4)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
C:\Users\mkrnac>
```
Version:

```
C:\Users\mkrnac>apm -v
apm  0.140.0
npm  2.5.1
node 0.10.35
python 3.2.4
git 1.9.4.msysgit.0
visual studio 2010
C:\Users\mkrnac>
```
I deinstalled atom, removed all atom folders an reinstalled again but without success.

**Comment by DavidA2014** [comment]
On my Win 8.1 machine, I did a fresh install of Atom 0.182. Then a download of atom_beautify failed:

Installing “atom-beautify@0.21.3” failed.Hide output…

npm ERR! git clone git://github.com/ariya/esprima.git Cloning into bare repository 'C:\Users\<snip>\.atom\.apm\_git-remotes\git-github-com-ariya-esprima-git-9077e517'...
npm ERR! git clone git://github.com/ariya/esprima.git fatal: unable to connect to github.com:
npm ERR! git clone git://github.com/ariya/esprima.git github.com[0: 192.30.252.131]: errno=No such file or directory
npm ERR! Windows_NT 6.2.9200
npm ERR! argv "C:\\Users\\<snip>\\AppData\\Local\\atom\\app-0.182.0\\resources\\app\\apm\\bin\\\\node.exe" "C:\\Users\\<snip>\\AppData\\Local\\atom\\app-0.182.0\\resources\\app\\apm\\node_modules\\npm\\bin\\npm-cli.js" "--globalconfig" "C:\\Users\\<snip>\\.atom\\.apm\\.apmrc" "--userconfig" "C:\\Users\\<snip>\\.atom\\.apmrc" "install" "C:\\Users\\<snip>\\AppData\\Local\\Temp\\d-115123-14324-i7y0ms\\package.tgz" "--target=0.21.0" "--arch=ia32" "--msvs_version=2013"
npm ERR! node v0.10.35
npm ERR! npm  v2.5.1
npm ERR! code 128

npm ERR! Command failed: Cloning into bare repository 'C:\Users\<snip>\.atom\.apm\_git-remotes\git-github-com-ariya-esprima-git-9077e517'...
npm ERR! fatal: unable to connect to github.com:
npm ERR! github.com[0: 192.30.252.131]: errno=No such file or directory
npm ERR! 
npm ERR! 
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <http://github.com/npm/npm/issues>

I am behind a company proxy server. My .apmrc file that worked with older versions of Atom is at:

"C:\Users\<snip>\.atom\.apmrc"

and contains:

https-proxy=http://<snip>
http-proxy=http://<snip>
strict-ssl=false

apm now seems to be using:

"C:\Users\<snip>\.atom\.apm\.apmrc"

but when I paste in proxy details there, apm or Atom deletes them when I try to install a package, and the package download fails.

**Comment by liupeiyu** [comment]
colored output.
C:\Users\Administrator>apm install --check
Checking for native build tools failed

gyp info it worked if it ends with ok
gyp info using node-gyp@2.0.2
gyp info using node@0.10.40 | win32 | ia32
gyp http GET https://atom.io/download/atom-shell/v0.36.8/node-v0.36.8.tar.gz
gyp http 404 https://atom.io/download/atom-shell/v0.36.8/node-v0.36.8.tar.gz
gyp WARN

**Comment by Wulawa** [comment]
Checking for native build tools failed

gyp info it worked if it ends with ok
gyp info using node-gyp@3.4.0
gyp info using node@6.9.5 | win32 | x64
gyp http GET https://atom.io/download/electron/v1.3.13/iojs-v1.3.13.tar.gz
gyp WARN install got an error, rolling back install
gyp ERR! install error
gyp ERR! stack Error: connect ETIMEDOUT 54.231.121.27:443
gyp ERR! stack     at Object.exports._errnoException (util.js:1022:11)
gyp ERR! stack     at exports._exceptionWithHostPort (util.js:1045:20)
gyp ERR! stack     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1087:14)
gyp ERR! System Windows_NT 10.0.14393
gyp ERR! command "C:\\Users\\lufeng\\AppData\\Local\\atom\\app-1.16.0\\resources\\app\\apm\\bin\\node.exe" "C:\\Users\\lufeng\\AppData\\Local\\atom\\app-1.16.0\\resources\\app\\apm\\node_modules\\node-gyp\\bin\\node-gyp.js" "install" "--runtime=electron" "--target=1.3.13" "--dist-url=https://atom.io/download/electron" "--arch=x64" "--ensure"
gyp ERR! cwd C:\Users\lufeng\.atom
gyp ERR! node -v v6.9.5
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok


What should I do?

**Comment by BobenHome** [comment]
this problem how to solve？

**Comment by Arcanemagus** [comment]
The original issue reported here was fixed back on 2015-02-23, so I'm locking this thread.

If you are experiencing this issue or another one please file a **new** issue so we can track down your problem.
