### ISSUE TITLE
Bundle iojs instead of node v0.10.35?

### ISSUE THREAD

**Issue by jbt** [atom/apm#312]
Currently scripts/download-node.js pulls node v0.10.35 from nodejs.org. This is causing various errors like atom/atom#3783 when it tries to grab a build that doesn't exist (e.g. armv7l) which just returns a 404. (I think this might be causing #282 as well)

I'm guessing it wouldn't _technically_ be too hard to swap out nodejs for iojs (which distributes binaries for a whole pile more architectures) in that script - change a few urls and filenames and it should Just Work for downloading the binary at least. I'd pull req it myself but I don't know what other moving parts there are that it could possibly break and how to test all that.

**Comment by pwaring** [comment]
Is there any reason to pull node at all? I already have it installed on my machines so pulling it down again seems a bit pointless, unless I'm missing something.

**Comment by kevinsawicki** [comment]
> Is there any reason to pull node at all? 

So apm works for people who don't have node already installed.

**Comment by pwaring** [comment]
I'm still not sure why you would do that - pretty much every other piece of software requires you to have dependencies installed beforehand. Why not just refuse to build if node isn't already installed?

**Comment by kevinsawicki** [comment]
> Why not just refuse to build if node isn't already installed?

It isn't about building, it is about installing, you wouldn't be able to install atom packages or themes without node installed first. It is really convenient to be able to install Atom and immediately be able to install packages and themes without having to download and run another installer.

Also apm ships prebuilt native modules, so shipping a specific node version that the native modules are prebuilt against ensures that apm works predictably on all machines.

**Comment by thedaniel** [comment]
It's not likely we'll put a ton of effort in right now to support ARM specifically, but if someone wants to open a PR to switch from node->io.js we'll certainly review it and help make sure it doesn't cause breakage.

**Comment by jbt** [comment]
I can have a go at that - but is there anything in particular that's likely to explode when switching to iojs? (I haven't quite got my head around all the moving parts so I don't know what I should be looking out for)

**Comment by kevinsawicki** [comment]
>  but is there anything in particular that's likely to explode when switching to iojs?

I'm really unsure about this which is why I hesitate to switch it.

**Comment by pwaring** [comment]
I'm very happy to test on ARM - I think it's an important architecture given the rise of small computing devices (e.g. the Raspberry Pi has shipped over 5 million units).

**Comment by thedaniel** [comment]
5 million raspis working together can only run about 1 million instances of chromium though ;)

**Comment by jbt** [comment]
Turns out it's quite easy to get scripts/download-node.js to pull iojs (just change a few urls and filenames like I thought)

Unfortunately, I can't for the life of me figure out how to persuade node-gyp to build the native modules specifically against that node/iojs version, which isn't the one with which the node-gyp is invoked (the `--target` param used in atom's [script/bootstrap](https://github.com/atom/atom/blob/cd9a1ccb9fa02127501457ba8babb541c016e71b/script/bootstrap#L67) doesn't play nicely with iojs it would seem, and I don't know enough about native modules and the whole build process to understand why).

So I guess I won't be submitting that PR then, sadface :( It'll take a better mind than mine to figure it out.

Still, would be nice to be using a more recent node/iojs version than 0.10.35 if someone else is able to make it work, and if it's iojs then ARM support would (hopefully) come as a bonus side-effect.

**Comment by deepak1556** [comment]
updated apm to use v0.12.0, successfully built both atom and atom-shell with the changes https://github.com/deepak1556/apm , only blocker are the failing shell-test #305 . @kevinsawicki any thoughts on it ?

**Comment by kevinsawicki** [comment]
>  any thoughts on it ?

The way `script/build` works in atom/atom is that apm is built and bundled at that point. So I would think this line: https://github.com/atom/atom/blob/42d750f02a46fbe3f489e371b3730065c6ec0bb0/script/bootstrap#L67 would have to change in order for apm's native modules to be built against the right target such that they are runnable in node 0.12.

So if that line is changed, I'd be curious if Atom's `script/build` would still be runnable using node 0.10 . I would be nice to still support it since I assume many people haven't upgraded their system node to 0.12 yet.

**Comment by deepak1556** [comment]
archlinux x86_64
```
~  ❯ node -e "console.log(process.versions)"
{ http_parser: '1.0',
  node: '0.10.28',
  v8: '3.14.5.9',
  ares: '1.9.0-DEV',
  uv: '0.10.27',
  zlib: '1.2.3',
  modules: '11',
  openssl: '1.0.1g' }

```

@kevinsawicki built atom successfully with https://github.com/deepak1556/atom/commit/08554464d127307f7139369fc65bcb967c2179cd . Away from windows machine , so couldnt test this there but i hardly doubt there will be a platfrom dependent bug here ;)

**Comment by jlord** [comment]
@deepak1556 Just to confirm, you were able to successfully build but don't have an ARM system?

I've been able to build apm with iojs but am stuck because there is no atom-shell/electron 32 bit ARM build :link: https://github.com/atom/electron/issues/366

**Comment by deepak1556** [comment]
@jlord nope dont have an ARM system, was just building on different node versions on supported platfroms of electron (did try only on linux at that time) .

**Comment by bolinfest** [comment]
It's pretty hard to install Node v0.10 these days. Anyone who has installed it recently has Node v0.12.

I just want a version of Node bundled with apm that supports `yield`, so I don't care too much whether it's io.js or Node v0.12.

Admittedly, I see that [`keytar`](https://github.com/atom/node-keytar) has native dependencies, but the code is small, so hopefully that is easy enough to build cross-platform with a more recent Node.
