### ISSUE TITLE
Add comment to ~/.atom/.apm/.apmrc about it not being editable

### ISSUE THREAD

**Issue by kevinsawicki** [atom/apm#313]
The editable file goes in `~/.atom/.apmrc` but people are editing their global apm rc file in `~/.atom/.apm/.apmrc` which shouldn't be edited and gets wiped out on updates

**Comment by thedaniel** [comment]
Might be worth also changing the name, people assume they can edit dotfiles in their home directories. A global config file would be in something like, i dunno, `/etc/atom/apmr` and then overridden in `~/.apmrc` on linux

**Comment by kevinsawicki** [comment]
> A global config file would be in something like, i dunno, /etc/atom/apmr

Yeah, I picked the current location since I knew it would be writable, other traditional locations might require `sudo`.
