### ISSUE TITLE
Installing starred packages and re-authenticating

### ISSUE THREAD

**Issue by jegtnes** [atom/apm#318]
Hey there, apm.

I'm setting up a fresh state on my machine at the moment, and wanted to install all my starred packages. However, I copy/pasted my API key wrong when prompted, and now I'm unable to authenticate with the API at all, only ever receiving the error message `Requesting packages failed: Requires authentication`. Is there a way to re-authenticate with apm on the command line? I was unable to find any relevant option on the help commands for both `apm` and `apm stars`.

Many thanks!

**Comment by thedaniel** [comment]
You can just run `apm login` again - let me know if that doesn't work and we can reopen this issue in that case.
