### ISSUE TITLE
Dependencies (package.json): 406 with http/https

### ISSUE THREAD

**Issue by tststs** [atom/apm#319]
I don't know, if this is related to apm. If i'm using http/https for a repo in package.json, the result is always 406.

<strong>is:</strong>
package.json:
```
"dependencies": {
    "tern": "git://github.com/marijnh/tern.git",
  },
```

<strong>should:</strong>
package.json:
```
"dependencies": {
    "tern": "https://github.com/marijnh/tern.git",
  },
```
npm ERR! fetch failed https://github.com/marijnh/tern.git
npm WARN retry will retry, error on last attempt: Error: fetch failed with status code 406
npm ERR! fetch failed https://github.com/marijnh/tern.git
npm WARN retry will retry, error on last attempt: Error: fetch failed with status code 406
npm ERR! fetch failed https://github.com/marijnh/tern.git
npm ERR! Darwin 14.1.0
npm ERR! argv "/Applications/Atom.app/Contents/Resources/app/apm/bin/node" "/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/bin/npm-cli.js" "--globalconfig" "/Users/tobiasschubert/.atom/.apm/.apmrc" "--userconfig" "/Users/tobiasschubert/.atom/.apmrc" "install" "--target=0.21.0" "--arch=x64"
npm ERR! node v0.10.35
npm ERR! npm  v2.5.1

npm ERR! fetch failed with status code 406
npm ERR!

**Comment by thedaniel** [comment]
I'm pretty sure you need to drop the `.git` from the end of the `https` url

**Comment by izuzak** [comment]
This also sounds very similar to an npm issue: https://github.com/npm/npm/issues/7560

Can you install any npm packages with `npm install`?

**Comment by tststs** [comment]
Seems to be a problem with ```node 0.12.0```. I'm not able to install any package via ```https```.
I also tried to remove everything related to ```node``` and ```npm```and made a fresh install with ```brew```. Still a 406 with ```apm``` and ```npm```.

**Comment by bdefore** [comment]
I'm also having this issue with node 0.12.

**Comment by izuzak** [comment]
@bdefore @tststs Interesting -- thanks for posting updates here. So you can't reproduce this with node 0.10.x? Also, which OS are you using?

**Comment by bdefore** [comment]
@izuzak I'm using nvm on OSX 10.10.1 and with a package.json of:

```
{
  "devDependencies": {
    "react-paginate": "https://github.com/bdefore/react-paginate"
  }
}
```

I get this output from node 0.12 and then 0.10: https://gist.github.com/bdefore/067b7372ad8406f35006

**Comment by izuzak** [comment]
@bdefore The error you got for the 0.10.x case doesn't look like the 406, but something else. So, using Node 0.10.x for now should help for now. Also, might be worth reporting this over to npm or node, since `npm install` is failing -- what do you think?
