### ISSUE TITLE
apm update without --confirm requires confirmation but there is no --force

### ISSUE THREAD

**Issue by StevenACoffman** [atom/apm#325]
Hello,
When I run:
```bash
apm update
```
I get:
```
Package Updates Available (1)
└── atom-beautify 0.21.6 -> 0.22.3

Would you like to install these updates? (yes)
```
However, I cannot run apm --force to skip the confirmation for a non-interactive update.

**Comment by kevinsawicki** [comment]
Have you tried `apm update --confirm`?

**Comment by kevinsawicki** [comment]
Sorry, I mean `apm update --no-confirm`?

**Comment by StevenACoffman** [comment]
Nope, apm help update didn't show that as an option, and now I don't have anything in need of updating. Assuming that works, can `apm help update` or `apm help upgrade` show this option?

**Comment by kevinsawicki** [comment]
> Nope, apm help update didn't show that as an option

Yeah, it should show `--confirm` as an option that defaults to true, all arguments support a `no-` prefix to toggle them to false such as `--no-color` to disable terminal colors.

**Comment by StevenACoffman** [comment]
Thanks! Could you add `All arguments support a 'no-' prefix to toggle them to false such as --no-color to disable terminal colors.` to the end of `apm help <command>`? That might help other people who don't know about it.

**Comment by kevinsawicki** [comment]
> Could you add

Absolutely, great idea, will add this now, sorry for the confusion.

**Comment by kevinsawicki** [comment]
Added in https://github.com/atom/apm/commit/888594366742885467fe13d01479d4f963758f66, thanks for bringing this up
