### ISSUE TITLE
I can't get past gnome-keyring unless I'm in a desktop

### ISSUE THREAD

**Issue by mark-hahn** [atom/apm#335]
When I have no desktop running and I do `apm starred` or `apm publish` it asks for the token over and over and the publish doesn't work (starred does).  In the desktop I get a pop-up asking for the keyring password and then it works.

I've tried setting `ATOM_ACCESS_TOKEN` with no luck.  I've also tried setting the keyring password to blank.

Is there any way to tell apm to just not use the keyring at all and store the token itself?  Using ATOM_ACCESS_TOKEN would also be fine if it worked.

**Comment by thomasjo** [comment]
Is the `gnome-keyring` daemon running?

---
Please provide some more context and/or details next time. Since I came here directly from the [discussion on Discuss](https://discuss.atom.io/t/apm-wont-take-my-token/15930) I know the details about this running on a Chromebook etc, but hardly anyone else would have that context.

**Comment by mark-hahn** [comment]
sorry, I'm usually better at this.

There is no daemon running.  Googling `gnome-keyring-daemon` gave instructions way over my head.  Can't I just use something like `ATOM_ACCESS_TOKEN`?

**Comment by thomasjo** [comment]
Judging from [the relevant source code](https://github.com/atom/apm/blob/5242586a0f8721934f3395fd5712a4c20bf60623/src/auth.coffee#L20), it does look like that should work regardless of `gnome-keyring`. How did you set `ATOM_ACCESS_TOKEN`?

**Comment by mark-hahn** [comment]
I did  ...

```
ATOM_ACCESS_TOKEN="abcdefgh..."
apm starred
```

I sure hope I'm not doing some really stupid linux-newbie thing.

**Comment by mark-hahn** [comment]
Damn.  It was a newbie thing.  Adding `export ATOM_ACCESS_TOKEN` fixed it.  Now I need to study up on what `export` means.

I'm truly sorry for the trouble.

**Comment by thomasjo** [comment]
Glad it got sorted! 

`export` makes a variable available to child processes. See http://www.gnu.org/software/bash/manual/bash.html#index-export.
