### ISSUE TITLE
Submodule not bundled

### ISSUE THREAD

**Issue by tinloaf** [atom/apm#342]
Hi,

My package (https://github.com/tinloaf/autocomplete-plus-python-jedi) includes a git submodule for some code that I would like to bundle into the package. Now it seems like that does not work - the folder in which the submodule should be is empty when installing via apm, and so is it in the releases at https://github.com/tinloaf/autocomplete-plus-python-jedi/releases (I assume apm just downloads the release tarball?)

I tried to understand how APM creates these releases, but I failed. It looks like APM just pushes a tag and then hits the Atom.io API with some REST request - does Atom.io then invoke some github API to create the release? If so, is it possible to alter that request so that submodules are checked out before the tarball is created?

**Comment by lee-dohm** [comment]
apm pushes a tag, which is regarded as a release in the GitHub API. What is typically done for dependencies, even by apm itself, is to create an npm module which can then be installed as a dependency:

https://github.com/atom/apm/blob/master/package.json#L27-L49

This allows one to decouple the dependency management from Git's specific implementation.

**Comment by thedaniel** [comment]
@tinloaf this is the GitHub API call that is used by the API during package installation: https://developer.github.com/v3/repos/contents/#get-archive-link

While the archive endpoint doesn't include submodules, the Contents API *does* provides information about a repo's submodules. However, supporting this reasonably (and adding the arbitrary number of requests necessary to download submodules) would require the API backend to keep track of the reachability of all the submodules in a repo. We're not interested in adding that complexity right now, and as @lee-dohm points out above, `npm` provides a great means to add external dependencies, so you should use that if possible.
