### ISSUE TITLE
APM publish uses 'origin' remote from git, rather than repo from package.json 

### ISSUE THREAD

**Issue by ctolkien** [atom/apm#343]
`apm publish X` Will add new tag to origin remote, even if that isn't the correct repo.

The publish process will then fail with 'tag not found' error as the tag doesn't exist in the repo referenced in package.json.

**Comment by jimtahu** [comment]
Second, I normally call the github remote 'github', not origin, and this issue lead to inadvertently publishing 0.2.0 as the first package version [jimtahu/atom-build-waf/releases/tag/v0.2.0](https://github.com/jimtahu/atom-build-waf/releases/tag/v0.2.0)

**Comment by twifty** [comment]
Any news on this? I also prefer to name my remote as 'github'. It avoids many mistakes of pushing to the wrong upstream.
