### ISSUE TITLE
Could not determine current Atom version installed

### ISSUE THREAD

**Issue by despairblue** [atom/apm#344]
After upgrading to atom 0.193.0 apm cannot find atom anymore.

```bash
$ apm update
Could not determine current Atom version installed
$ apm version
apm  0.159.0
npm  2.5.1
node 0.10.35
python 2.7.9
git 2.3.5
```

Updating packages from within atom works. I've been downgrading to 0.192.0 to make sure that this is a 0.193.0 specific issue, it is.

**Comment by kevinsawicki** [comment]
What platform are you on?

**Comment by kevinsawicki** [comment]
Was able to reproduce on Linux and Windows

**Comment by kevinsawicki** [comment]
Thanks so much for reporting this so quickly :blue_heart:

**Comment by despairblue** [comment]
Yeah forgot to mention the platform, Linux it was. Thanks for the quick fix
:)

**Comment by kevinsawicki** [comment]
0.194 is out with this fixed, please let me know if you still see an issue, I tested on Ubuntu and Windows and it appeared to work correctly.

**Comment by despairblue** [comment]
0.194.0 works as expected! :clap:
