### ISSUE TITLE
[website] incomplete/empty search results from within Atom

### ISSUE THREAD

**Issue by anomaly256** [atom/apm#348]
Hi, I just installed Atom fresh on a new host from the .deb package, v0.194.0, and there are no community packages listed at all in Themes or in Packages.  I tried searching for my own theme and got 0 results.  'apm install' is able to find and install the package however.  On another host where Atom is built from source, updated today to v0.194.0, after uninstalling my theme it again isn't showing up in search results there either until I manually 'apm install' it however on this host I do see *some* community packages listed when opening the themes and packages pane - a total 5 for 'community themes' and 9 for 'community packages'

**Comment by thomasjo** [comment]
Are you searching on the *Install* view, or *Packages*—the latter is **only** for packages actually installed on your system, whereas the former is for actually installing packages.

![settings_-__users_thomasjo_code_latex_-_atom](https://cloud.githubusercontent.com/assets/3622/7342597/bb0570a4-ecb6-11e4-8f8d-3dab1257a1cc.png)

**Comment by anomaly256** [comment]
Oh man how did I miss that.  Closing ticket..
