### ISSUE TITLE
testing with Atom API preview mode

### ISSUE THREAD

**Issue by jacekkopecky** [atom/apm#353]
I can't seem to find a way to test package specs in Atom 1.0 preview mode. Should there be a command-line switch? Sorry if the answer's obvious and I'm missing it...

**Comment by thomasjo** [comment]
Doesn't look like this is actually supported. Good catch.

**Comment by kevinsawicki** [comment]
Thanks so much for bringing this up, this will be included in the next Atom release, 0.197.0
