### ISSUE TITLE
Unpublishing failed: Unauthorized, i not unpublish my package

### ISSUE THREAD

**Issue by akaytatsu** [atom/apm#354]
My package is dsl-progress (https://github.com/akaytatsu/dsl-progress).

i deleted the package from github, and then exec apm unpublish dsl-progress, but, this is not possible, the message is Unpublishing failed: Unauthorized

**Comment by lee-dohm** [comment]
Yes, deleting the package from GitHub makes it impossible for the original repository owner to unpublish the package. I'll see if someone can take a look.

/cc @thedaniel

**Comment by akaytatsu** [comment]
Please, because this name of package is very important, and the documentation and videos from this package been  generated and distributed

**Comment by lee-dohm** [comment]
I can't guarantee anyone will be able to look at it before Monday.

**Comment by akaytatsu** [comment]
then staff, help me solve this problem .

**Comment by akaytatsu** [comment]
staff, i realy need help. Is possible the correction for this problem? The marketing of package is ready, and this release need to today. I count on yours. Thank's

**Comment by akaytatsu** [comment]
someone?

**Comment by thedaniel** [comment]
@akaytatsu I deleted the package in the database, sorry to keep you waiting! :bow:

**Comment by akaytatsu** [comment]
@thedaniel the problem now is:

Registering dsl-progress done
Preparing and tagging a new version done
Pushing v0.2.0 tag Username for 'https://github.com': akaytatsu
Password for 'https://akaytatsu@github.com':
done
Publishing dsl-progress@v0.2.0 failed
Creating new version failed: Application error

**Comment by akaytatsu** [comment]
@thedaniel help-me for this problem

**Comment by lee-dohm** [comment]
@akaytatsu There are a lot of extra fields in your `package.json` which may be messing up the publishing process. You should take the information from your `package.json` and put it into this template:

```json
{
  "name": "wordcount",
  "main": "./lib/wordcount",
  "version": "0.0.0",
  "description": "A short description of your package",
  "activationCommands": {
    "atom-workspace": "wordcount:toggle"
  },
  "repository": "https://github.com/atom/wordcount",
  "license": "MIT",
  "engines": {
    "atom": ">=0.174.0 <2.0.0"
  },
  "dependencies": {
  }
}
```

**Comment by akaytatsu** [comment]
Yes, i accert this package.json and the problem as solved! Thank`s, very thank. Please, close this report.
