### ISSUE TITLE
--harmony_collections flag will need to be removed when apm supports node 0.12.x

### ISSUE THREAD

**Issue by pusateri** [atom/apm#357]
In the V8 javascript interpreter, the option --harmony_collections was removed because the functionality is no longer optional, it's always enabled beginning with V8 3.28.60 shown in this diff:

https://code.google.com/p/v8/source/diff?spec=svn22897&r=22897&format=side&path=/trunk/src/flag-definitions.h

This means that when trying to build APM with newer versions of node like 0.12.2 instead of the default version 0.10.3, apm fails when node is invoked with --harmony_collections.

This issue is a placeholder for when apm starts to support being built with node 0.12.x instead of 0.10.x.

diff --git a/bin/apm b/bin/apm
index 0d48da9..cf4d672 100755
--- a/bin/apm
+++ b/bin/apm
@@ -24,4 +24,4 @@ done
 
 binDir=`pwd -P`
 builtin cd "$initialCwd"
-"$binDir/$nodeBin" --harmony_collections "$binDir/../lib/cli.js" "$@"
+"$binDir/$nodeBin" "$binDir/../lib/cli.js" "$@"
[

**Comment by kevinsawicki** [comment]
Thanks for opening this but I think this can be closed out. If/when the node version shipped with apm is upgraded this flag will definitely be removed since apm will be completely broken without removing it so I don't think it needs to be tracked specifically as a separate issue.
