### ISSUE TITLE
Add `apm disable / enable` command

### ISSUE THREAD

**Issue by mnquintana** [atom/apm#358]
[There is currently no way to disable packages from the command-line](https://github.com/atom/language-html/issues/59#issuecomment-99542896) - we should add an `apm disable` command that can take one or more package names and disable them in Atom (as well as its counterpart, `apm enable`).

**Comment by brennanMKE** [comment]
:+1:

**Comment by bronson** [comment]
It's possible to do manually: https://github.com/atom/atom/issues/5987#issuecomment-84129975

But, I agree, :+1: for `apm disable`.

**Comment by bronson** [comment]
@mnquintana now there's a way.  Chance of a review for #400?

**Comment by dfang** [comment]
+1

**Comment by echohack** [comment]
+1 please

**Comment by nmccready** [comment]
for the love +1 also doing this in bulk would be great

**Comment by bronson** [comment]
@nmccready the PR (#400) accepts multiple packages on the command line:
```
apm disable metrics exception-reporting
```

is this what you mean by bulk?

**Comment by nmccready** [comment]
yep ty

**Comment by nmccready** [comment]
Any suggestions how I could use `xargs` from `apm list` to disable all installed packages (not default) . I am unable to get the editor to open with latest update.

**Comment by Sirlon** [comment]
+1

**Comment by pmsm1100** [comment]
+1

**Comment by bronson** [comment]
@nmccready sorry, I don't know of a good way.  In theory it ought to look something like this:

```sh
apm disable $(apm list --installed --bare)
```

But that doesn't work because --bare still includes "@_version_" after each package name.

I like the idea of a --really-bare option that would make that work.  Probably worth opening a new issue?

(Or, maybe apm should just remove the "@_version_" from --bare's output.  That's what I picture by "bare".  :)

**Comment by nmccready** [comment]
@bronson , no worries; I had to blow everything away and start from scratch. Atom keeps breaking thing with all the updates lately.

**Comment by danielbayley** [comment]
@bronson `apm list -ib | sed s/@.*//g` will give you a plain text list of all packages.

`apm list -ibd false | sed s/@.*//g` will do the same, excluding disabled packages.

**Comment by bronson** [comment]
@nmccready Yes, it's been a particularly rough patch over the past month or two.  Hoping things will settle down now that Electron and Node are updated.

@danielbayley agreed, that does the job here.  But I think it's a bad sign when a command line program can't ingest its own output.  It would be nice to have a proper fix.

Another potential fix would be to modify apm enable/disable to ignore the @_version_ tags.  That's probably easier and has less risk of breaking other things.  Even so, I'd rather make --bare's output more bare.  I think.

**Comment by danielbayley** [comment]
> Another potential fix would be to modify apm enable/disable to ignore the @version tags. That's probably easier and has less risk of breaking other things. Even so, I'd rather make --bare's output more bare. I think.

Agreed.

**Comment by mnquintana** [comment]
Added in https://github.com/atom/apm/pull/400

**Comment by bronson** [comment]
If anyone cares, maybe open a new issue for the ingest/output problem?  (apm list prints package@version, but apm install doesn't accept that syntax)

Of the possible solutions, I wouldn't know which to choose.  I'm happy to write the fix once there's agreement.

**Comment by MichaelCereda** [comment]
To make things clear to whomever interested

`apm disable $(apm list -ib | sed -e 's/@.*// ')`  

disables all the atom packages.
