### ISSUE TITLE
apm publish gives Application Error

### ISSUE THREAD

**Issue by noseglid** [atom/apm#364]
Not sure if this is where this issue should go. Please direct me to the correct forum otherwise.

I get this:
```
$ apm publish -t v0.32.0
Publishing build@v0.32.0 ✗
Creating new version failed: Application error
```

I've debugged a little, and it appears I get `500 Internal Server Error` from the API. So likely something is off with whatever `apm` communicates with.

**Comment by lee-dohm** [comment]
Have you done an `apm login` to make sure that it has your credential?

**Comment by noseglid** [comment]
Yes I have. This is the 32nd release of this package I am doing from the exact same setup.

**Comment by noseglid** [comment]
(I don't really think it's a problem with `apm`. The request for publishing looks fine from what I can tell. It's likely to be something with the service running at `atom.io`)

**Comment by thedaniel** [comment]
Yeah any time atom.io 500s it's a concern. I'll look into it when I have a moment.

**Comment by cs150bf** [comment]
I'm also seeing "Application Error". Tagging and pushing went okay. The new release (`v0.1.2`) shows up just fine on [the releases page of my git repo](https://github.com/cs150bf/ever-notedown/releases), but not on the [atom.io package page](https://atom.io/packages/ever-notedown) as it still says `v0.1.1`.

**Comment by noseglid** [comment]
Not sure if this helps. I engineered the request using `cURL`.

```
curl -v --http1.1 -X POST -H 'Content-Type: application/json' -d '{ "tag": "v0.32.0" }' -H 'Authorization: _FHAOkgbw6Ven0Gxf6_BUxQ' "https://atom.io/api/packages/build/versions"
* Hostname was NOT found in DNS cache
*   Trying 107.21.209.157...
* Connected to atom.io (107.21.209.157) port 443 (#0)
* TLS 1.2 connection using TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256
* Server certificate: *.atom.io
* Server certificate: DigiCert SHA2 High Assurance Server CA
* Server certificate: DigiCert High Assurance EV Root CA
> POST /api/packages/build/versions HTTP/1.1
> User-Agent: curl/7.37.1
> Host: atom.io
> Accept: */*
> Content-Type: application/json
> Authorization: <removed for security reasons>
> Content-Length: 20
>
* upload completely sent off: 20 out of 20 bytes
< HTTP/1.1 500 Internal Server Error
* Server Cowboy is not blacklisted
< Server: Cowboy
< Connection: close
< Date: Thu, 14 May 2015 08:40:31 GMT
< Status: 500 Internal Server Error
< Strict-Transport-Security: max-age=631152000
< X-Frame-Options: DENY
< X-Xss-Protection: 1; mode=block
< X-Content-Type-Options: nosniff
< Content-Security-Policy: default-src 'self'; connect-src 'self'; font-src 'self'; frame-src 'self'; img-src https://* 'self' data:; media-src 'none'; object-src 'self'; script-src 'self' 'unsafe-inline' https://ssl.google-analytics.com https://www.google-analytics.com; style-src 'self' 'unsafe-inline';
< Content-Type: application/json; charset=utf-8
< Cache-Control: no-cache
< Set-Cookie: request_method=POST; path=/; secure
< X-Request-Id: b87c974b-3129-4ff5-8376-6df676e00c53
< X-Runtime: 0.458679
< X-Rack-Cache: invalidate, pass
< Via: 1.1 vegur
<
* Closing connection 0
{"message":"Application error"}
```

If there's anything else I can do, let me know.

**Comment by thedaniel** [comment]
Thanks for the details - I haven't fixed this yet, but I want to give an update; I see the failed requests in the server logs, but not in our internal exception tracking system, which makes it a little more difficult to reproduce. I'll update this thread when I know more.

**Comment by noseglid** [comment]
It is happend **every** time I try to publish `v0.32.0` for the `build` package. You're welcome to publish it as a means to reproduce it. And if you succeed, it's all good!

**Comment by thedaniel** [comment]
@noseglid strangely enough, there was a version 0.32.0 in the DB pointing to [this commit](https://github.com/noseglid/atom-build/commit/fb265b35598ff429528996a394a15a299f938287) from 2 weeks ago, that was created the same day as that commit's date. After I deleted that row from the DB, I was able to re-import a new v0.32.0 from the same tag: https://atom.io/packages/build

I'm not sure how it happened, but basically a version 0.32.0 of build had already been published, and then other, earlier versions were created, and when you tried to publish another 0.32.0, the app crashed rather than giving you a reasonable error message.

@cs150bf I'll investigate your package tomorrow.

**Comment by noseglid** [comment]
@thedaniel Aha! I might be able to  give some insight on that.

I did `apm publish` (on `0.31.0`) without the proper proxy/socksify connections set, which pushed the tag to github but never succeeded in publishing the package (from what I gathered at least).

I fixed the proxy settings and did another publish which succeeded (but this time it accidentally became v0.32.0).

Realizing my mistake, I removed the tags, forced pushed master on github to remove the `Preparing v0.32.0`-commit and unpublished `0.32.0` and went on to publish `0.31.0`. Now it is 2 weeks later and voila.

That's the most accurate description I can give from memory. Maybe it is the `unpublish` command that doesn't really work?

**Comment by magalhas** [comment]
I'm having the same symptoms with the `jenkins` package for over a month. I've tried different machines, `apm` setup is fine.

**Comment by magalhas** [comment]
What's the status on this? Atom 1.0 is almost out and I can't release my updated package without deprecated APIs.

**Comment by thedaniel** [comment]
Sorry about this, I'll take a look at it.

**Comment by magalhas** [comment]
@thedaniel let me know

**Comment by thedaniel** [comment]
@magalhas i see the errors in our exception tracking system, but I also notice that the version (0.3.2) in package.json on master matches the latest version here: https://atom.io/packages/jenkins

Is it possible that the package published successfully even though there was an error?

**Comment by thedaniel** [comment]
@magalhas exactly what apm command are you running?

**Comment by magalhas** [comment]
`apm publish patch`. After getting the application error message I've also tried unpublishing but it says that the version is not found.

**Comment by thedaniel** [comment]
@magalhas I see an unpublished 0.3.3 in the db and some deleted tags in GitHub staff tools. The API won't let you unpublish a version and then publish the same one with a different tag - force pushing & deleting history in general leads to some unfortunate behavior in the atom.io API as it's closely tied to the GitHub repo. You can likely publish 0.3.4 though. I'm working on a fix for the API that does a better job of reporting the nature of the error rather than just crashing, and if apm makes it difficult for you to publish the right version for any reason, let me know and we can work on that (or you can make the calls directly via curl)

**Comment by magalhas** [comment]
@thedaniel I was able to publish v0.3.4 as you've stated, though not being able to publish v0.3.3 is still harsh to understand for me. Thank you for your feedback :+1:

**Comment by kmorey** [comment]
I'm having this issue with my package as well this morning. How can I resolve it?

**Comment by thedaniel** [comment]
This issue was moved to atom/atom.io#7

**Comment by jacogr** [comment]
Same here. 3 packages, 2 were fine the 3rd gave the issue. Yes, I am logged-in, yes I re-logged-in, yes other packages work - before and after my trial and tribulations. I have tried multiple times and completely screwed up the tags now.

This is the one that doesn't publish

https://atom.io/packages/git-control

Did it again, just to copy n paste.

```
➜  git-control git:(master) apm publish patch 
Preparing and tagging a new version ✓
Pushing v0.4.5 tag ✓
Publishing git-control@v0.4.5 ✗
Creating new version failed: Application error
```

**Comment by thedaniel** [comment]
@jacogr could you remove the _atomModuleCache key from your package.json? It's not necessary and it's related to what's causing the application error (which we should fix, of course, but in the meantime having a package.json that's not 130kb will avoid triggering it)
