### ISSUE TITLE
npm ERR! Failed resolving git HEAD when installing package.

### ISSUE THREAD

**Issue by sulliwane** [atom/apm#375]
Here is my apm version output:
```
$ apm -v
apm  0.168.0
npm  2.5.1
node 0.10.35
python 2.7.6
git 2.4.3
```

and here is the error when I try installing go-plus:

```
$ apm install go-plus
Installing go-plus to /home/victor/.atom/packages ✗

npm ERR! Failed resolving git HEAD (https://github.com/joefitzgerald/atom-message-panel.git) fatal: ambiguous argument 'go-plus': unknown revision or path not in the working tree.
npm ERR! Failed resolving git HEAD (https://github.com/joefitzgerald/atom-message-panel.git) Use '--' to separate paths from revisions, like this:
npm ERR! Failed resolving git HEAD (https://github.com/joefitzgerald/atom-message-panel.git) 'git <command> [<revision>...] -- [<file>...]'
npm ERR! Failed resolving git HEAD (https://github.com/joefitzgerald/atom-message-panel.git) 
npm ERR! Linux 3.16.0-40-generic
npm ERR! argv "/usr/share/atom/resources/app/apm/bin/node" "/usr/share/atom/resources/app/apm/node_modules/npm/bin/npm-cli.js" "--globalconfig" "/home/victor/.atom/.apm/.apmrc" "--userconfig" "/home/victor/.atom/.apmrc" "install" "/tmp/d-115514-13786-vsxwjj/package.tgz" "--target=0.22.0" "--arch=x64"
npm ERR! node v0.10.35
npm ERR! npm  v2.5.1
npm ERR! code 128

npm ERR! Command failed: fatal: ambiguous argument 'go-plus': unknown revision or path not in the working tree.
npm ERR! Use '--' to separate paths from revisions, like this:
npm ERR! 'git <command> [<revision>...] -- [<file>...]'
npm ERR! 
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /tmp/apm-install-dir-115514-13786-g5574z/npm-debug.log
```

thank you for your help!

**Comment by sulliwane** [comment]
It is a cache problem with npm. I solved it with a dirty trick by adding a / at the end of the url that makes problem, so it will bypass the cache.

npm can do "npm cache clean", is there a way to clean the cache with apm ? And btw where is apm's npm and apm's node installed ?

**Comment by sulliwane** [comment]
I still can't get go-plus plugin working on my **Ubuntu 14.04** computer with **atom 1.0**. Everytime I try to install it ends up with this **npm error**:

    Installing “go-plus@3.3.12” failed.Hide output…
    npm ERR! Failed resolving git HEAD (https://github.com/joefitzgerald/atom-message-panel.git) fatal: ambiguous argument 'go-plus': unknown revision or path not in the working tree.
    npm ERR! Failed resolving git HEAD (https://github.com/joefitzgerald/atom-message-panel.git) Use '--' to separate paths from revisions, like this:
    npm ERR! Failed resolving git HEAD (https://github.com/joefitzgerald/atom-message-panel.git) 'git <command> [<revision>...] -- [<file>...]'
    npm ERR! Failed resolving git HEAD (https://github.com/joefitzgerald/atom-message-panel.git) 
    npm ERR! Linux 3.16.0-41-generic
    npm ERR! argv "/usr/share/atom/resources/app/apm/bin/node" "/usr/share/atom/resources/app/apm/node_modules/npm/bin/npm-cli.js" "--globalconfig" "/home/victor/.atom/.apm/.apmrc" "--userconfig" "/home/victor/.atom/.apmrc" "install" "/tmp/d-115527-14657-pqu4ct/package.tgz" "--target=0.22.0" "--arch=x64"
    npm ERR! node v0.10.35
    npm ERR! npm  v2.5.1
    npm ERR! code 128
    npm ERR! Command failed: fatal: ambiguous argument 'go-plus': unknown revision or path not in the working tree.
    npm ERR! Use '--' to separate paths from revisions, like this:
    npm ERR! 'git <command> [<revision>...] -- [<file>...]'
    npm ERR! 
    npm ERR! 
    npm ERR! If you need help, you may report this error at:
    npm ERR!     <http://github.com/npm/npm/issues>
    npm ERR! Please include the following file with any support request:
    npm ERR!     /tmp/apm-install-dir-115527-14657-qw3b92/npm-debug.log

I believe it's is related to a npm cache problem...but not idea how to solve it.

Thank you for you help !!!

note: I also open similar issue on go-plus github: https://github.com/joefitzgerald/go-plus/issues/225

**Comment by sulliwane** [comment]
SOLVED

I solved the problem by moving npm-cli.js, doing this: 

    sudo mv /usr/share/atom/resources/app/apm/node_modules/npm/bin/npm-cli.js /usr/share/atom/resources/app/apm/node_modules/npm/bin/npm-cli.js.bak

Then install the package from atom and it worked! (I don't know how it can work without knowing about `npm-cli.js` but it worked! 

So it should have been a npm cache problem. 

Happy now!

**Comment by sulliwane** [comment]
Here is the correct and proper solution to clean apm cache, and solve the error:

    "/usr/share/atom/resources/app/apm/node_modules/npm/bin/npm-cli.js" "--globalconfig" "/home/victor/.atom/.apm/.apmrc" cache clear

after that, re-open ATOM and go to update or install the package that gave you problem!

**Comment by mochadwi** [comment]
Thank you sir :) It really helps me out!

**Comment by kakaOW** [comment]
Thanks! I have been searching for an answer for a week and this solved my problem!
