### ISSUE TITLE
Remove theme spaceship-ui

### ISSUE THREAD

**Issue by hacdias** [atom/apm#378]
Hello!

I've created a theme some months ago but I want to unpublish it (spaceship-ui, https://atom.io/themes/spaceship-ui). I have deleted the repository, but I can't unpublish it. I receive the following error:

```
Unpublishing spaceship-ui...
Unpublishing failed: Unauthorized
```

I just you to say me how to resolve this or if you can remove it for me, please.
Have a nice day ;)

**Comment by thedaniel** [comment]
I'll take care of it, thanks!

**Comment by hacdias** [comment]
Thanks ;)
