### ISSUE TITLE
Atom won't connect via Proxy

### ISSUE THREAD

**Issue by martineboh** [atom/apm#379]
Atom doesn't connect when am using a proxy. shows "read ECONNRESET" during package installation.

**Comment by izuzak** [comment]
@martineboh Have you set up apm to use the proxy? Check out [these instructions](https://atom.io/docs/v0.209.0/getting-started-installing-atom#setting-up-a-proxy) and let us know if that doesn't help.

**Comment by martineboh** [comment]
Thanks! Now working.
