### ISSUE TITLE
apm is not installed on Windows, no "Install Shell Commands" option

### ISSUE THREAD

**Issue by bnb** [atom/apm#381]
I'd like to start using apm to install Atom packages more easily, but I get an error saying the system doesn't recognize the apm command. I followed the instruction listed several places to go to Atom > Install Shell Commands, but there's nothing called Atom, and assuming, that "File" would be akin to OS X's "Atom" menu, it's not in the File menu. Any ideas on how I can get apm installed?

**Comment by 50Wliu** [comment]
`Atom > Install Shell Commands` is only available on Mac.
How did you install Atom?  If you used the new Squirrel installer (the one on atom.io), it should have installed `apm` automagically for you.

**Comment by bnb** [comment]
@50Wliu I installed via the Windows installer on atom.io. I've been having problems with Atom not installing how it should, and I don't know if this is another symptom of that. I previously had the Chocolaty version, and uninstalled and deleted all Atom files, but I'm still experiencing issues.

**Comment by kultom86** [comment]
Hi,

Would just like to add to this and say I'm also experiencing this issue. 
Used the installer from Atom.io, version 1.0.0. 

Windows 7. apm does not show up when doing echo %path% (dont know if it should).

**Comment by peduxe** [comment]
@kultom86 You can add it to the system path environment variables.

Win + R: then type `%localappdata%`, Atom > app-(atom version) > resources > app > apm > bin

Copy the entire path and open the system path environment settings window.
* Append to the end and confirm
* Restart console

This applies to every command line interface, in case you want to know where the executable is located use the `where <executable-name>` command.

```sh
where apm
where node
(...)
```

**Comment by DontPanic345** [comment]
I updated the readme and created a pull request, is there anything else I should do?

**Comment by damieng** [comment]
AtomSetup has done this now for a while although there were issues if you were using a locked down machine that didn't have registry tools access or had unicode characters in the existing path that are fixed in 1.7.0.

**Comment by prateekpannu** [comment]
If you don't have permissions to change "system path environment variables". You can still browse to where atom installation files are, and follow the path: Atom > app-(atom version) > resources > app > apm > bin; and then shift+right click, and select command prompt here

**Comment by keiyakins** [comment]
> Atom > Install Shell Commands is only available on Mac.

Then it shouldn't be in the fucking documentation without saying that. While you're at it, you can remove all the times it tells you to push cmd, which doesn't exist on more platforms than it does.

Honestly, just never let mac users touch the documentation. Every last one of them is a moron who thinks macs are the only computers.

**Comment by Aibokalv** [comment]
i test the method ,but did n't work,but when i change the path to C:\Users\Lenovo\AppData\Local\atom\app-1.10.2\resources\cli
it works

**Comment by yanakey** [comment]
The more flexible way is to add path without version: C:\Users\Administrator\AppData\Local\atom\bin

**Comment by josiahlund** [comment]
I just installed the latest version and still had to do this workaround.

https://github.com/atom/apm/issues/381#issuecomment-126911491

Seems like this issue should be reopened.

**Comment by allbarkays** [comment]
still same issue with the latest version as at today
