### ISSUE TITLE
apm --version should also list Atom version

### ISSUE THREAD

**Issue by mnquintana** [atom/apm#382]
It's often helpful for debugging to know what version of Atom is being used with `apm`.

**Comment by wldcordeiro** [comment]
I'm down to work on this.

**Comment by ManoloBrn** [comment]
It looks that it is finished, Is there anything more to do?

**Comment by Arcanemagus** [comment]
@ManoloBrn Both #453 and #473 were abandoned by their authors at an incomplete stage, so currently at least there is no "finished" implementation.
