### ISSUE TITLE
Installing packages fails every time

### ISSUE THREAD

**Issue by k5e** [atom/apm#384]
According to [leedohm](https://discuss.atom.io/users/leedohm) on [discuss.atom.io](https://discuss.atom.io/t/installing-packages-fails-every-time-windows-8-1-atom-1-0/17990):

- Windows 8.1
- Atom 1.0.0

Every attempt to install a package fails:
![apm-error](https://cloud.githubusercontent.com/assets/606885/8377638/25167af2-1c13-11e5-9d49-e307f88ffba7.png)

I performed tho following checks:
```
C:\Users\k5e\Desktop>apm -v
apm  1.0.1
npm  2.5.1
node 0.10.35
python 2.7.9
git 1.9.5.msysgit.0
visual studio
C:\Users\k5e\Desktop>apm test
Tests passed
C:\Users\k5e\Desktop>apm install --check
Checking for native build tools failed

gyp info it worked if it ends with ok
gyp info using node-gyp@1.0.2
gyp info using node@0.10.35 | win32 | ia32
gyp http GET https://atom.io/download/atom-shell/v0.22.0/node-v0.22.0.tar.gz
gyp WARN install got an error, rolling back install
gyp
```
The `--verbose` switch of apm does not add any verbosity to the above commands, BTW.

All tools are in the PATH and i can run them from the command line.
I sit behind a proxy. I have put the proxy conf into .apmrc:
```
C:\Users\k5e\Desktop>apm config list
; cli configs
globalconfig = "C:\\Users\\k5e\\.atom\\.apm\\.apmrc"
user-agent = "npm/2.5.1 node/v0.10.35 win32 ia32"
userconfig = "C:\\Users\\k5e\\.atom\\.apmrc"

; userconfig C:\Users\k5e\.atom\.apmrc
https-proxy = "http://proxy:8080/"
proxy = "http://proxy:8080/"

; globalconfig C:\Users\k5e\.atom\.apm\.apmrc
cache = "C:\\Users\\k5e\\.atom\\.apm"

; node bin location = C:\Users\k5e\AppData\Local\atom\app-1.0.0\resources\app\apm\bin\node.exe
; cwd = C:\Users\k5e\Desktop
; HOME = C:\Users\k5e
; 'npm config ls -l' to show all defaults.
```
Further, I have set the proxy configuration in the environment, so that all other tools like curl, wget, npm can use it. And they do.

What else should I check?

**Comment by batjko** [comment]
Well done for all the analysis so far! That's an excellent issue report.

Now, the node-gyp error often indicates an issue with visual studio. Which version do you have installed (Desktop or Web for example).
Can you otherwise try to install the ,NET 3.5 framework?

**Comment by k5e** [comment]
Thank you for the flowers ;-)

I have installed _Visual Studio Express 2013 for Windows Desktop (with Update 4)_, as indicated in the [docs](https://github.com/atom/atom/blob/master/docs/build-instructions/windows.md).
There is no .NET 3.5 on the PC, but 4.5 and 4.5.1. Is 3.5 really necessary?

**Comment by batjko** [comment]
I think 3.5 includes 2.0 which is neede by node-gyp, but normally the VS tools for Desktop have all that anyway.

What about Python 2?

**Comment by k5e** [comment]
Hmm, I have used nmp (and thus node-gyp) often before (outside of apm) and it never complained about missing .NET 3.5 or 2.0.
Python is 2.7.9

**Comment by batjko** [comment]
Well that's the end of my Latin then.
Let's see if someone from the core team can help, once they a breathing moment after the CodeConf today.

**Comment by k5e** [comment]
OK. Thank you so far. 

Week-end is about take off soon and at home I use Linux. So there is no need to hurry. 

Take care 
Christian 

Am 26. Juni 2015 16:31:49 MESZ, schrieb Patrick Metzdorf <notifications@github.com>:

**Comment by kubetz** [comment]
This is duplicate of https://github.com/atom/apm/issues/322 .

I had the same issue and [this hotfix](https://github.com/atom/apm/issues/322#issuecomment-96430856) worked for me.

The issue seems to be caused by the node-gyp following redirect when downloading `node-v0.22.0.tar.gz` but forgetting about proxy settings.

**Comment by batjko** [comment]
Thanks @kubetz  :+1:

**Comment by k5e** [comment]
Thank @kubetz. 
the workaround did help:
```
C:\Users\k5e\Desktop>set ATOM_NODE_URL=http://gh-contractor-zcbenz.s3.amazonaws.com/atom-shell/dist

C:\Users\k5e\Desktop>apm install --check
Checking for native build tools done

C:\Users\k5e\Desktop>apm install minimap
Installing minimap to C:\Users\k5e\.atom\packages done
```
I am going to close this an I hope for a solution in #322

**Comment by pinich** [comment]
@k5e I tried to run all of your commands but I get this error
```
C:\Users\pinchasc>apm install --check
Checking for native build tools failed

gyp info it worked if it ends with ok
gyp info using node-gyp@2.0.2
gyp info using node@0.10.40 | win32 | ia32
gyp http GET http://gh-contractor-zcbenz.s3.amazonaws.com/atom-shell/dist/v0.36.
8/node-v0.36.8.tar.gz
gyp http 200 http://gh-contractor-zcbenz.s3.amazonaws.com/atom-shell/dist/v0.36.
8/node-v0.36.8.tar.gz
gyp WARN install got an error, rolling back install
```

```
C:\Users\pinchasc>apm install minimap
Installing minimap to C:\Users\pinchasc\.atom\packages Unable to download https:
//www.atom.io/api/packages/minimap/versions/4.24.4/tarball: DEPTH_ZERO_SELF_SIGN
ED_CERT
```

**Comment by k5e** [comment]
Hi @TinoMuianga,
Thanks for reaching out to me.
As this is like seven years old, I do not even remotely remember, what exactly the issues were. And since then I have had three different PCs and I have had this problem never again.
I suggest that you collect the exact circumstances and error messages an open a new issue. And make sure to use up-to-date software. From OS up to Atom.

Am 26. Februar 2022 16:41:18 UTC schrieb Constantino De Jesus Muianga ***@***.***>:
***@***.***  where have you performed those checks, because i.ve tried on my windows powershell and got error.

**Comment by TinoMuianga** [comment]
Well Hi,
I Wasn't expecting a fast response, anyways I'll try your recommendation
and see where it gets. I have to say I'm new to this world of programming
and getting stuck just with an IDE before even starting to code is awkward!
Anyways, thank you for your time and attention.
Cheers
