### ISSUE TITLE
Unpublishing Problem

### ISSUE THREAD

**Issue by promek** [atom/apm#386]
My package is wombat-px (https://github.com/promek/wombat-px).

i deleted the package from github, and then exec apm unpublish, but, this is not possible, the message is Unpublishing failed: Unauthorized

**Comment by mnquintana** [comment]
/cc @thedaniel 

FWIW, there is [documentation warning against deleting repos](https://atom.io/docs/latest/behind-atom-maintaining-your-packages#unpublish-your-package) before unpublishing.

**Comment by promek** [comment]
Hi,  wombat-px project and got a completely different structure of the two different names,
new ones: wombat-light-syntax and wombat-dark-syntax
I need to delete wombat-px. Many people are still using it.
Could you please help me solve?

**Comment by thedaniel** [comment]
Sure, I'll remove it for you.

**Comment by CentaurWarchief** [comment]
@thedaniel Could you do the same for me? I've removed the repository before unpublish.

**Comment by izuzak** [comment]
@CentaurWarchief we've unpublished that package for you.

**Comment by fruggiero** [comment]
@izuzak @thedaniel can you remove for me the package **robox-light-syntax** please?

**Comment by thedaniel** [comment]
@fruggiero done!
