### ISSUE TITLE
Cannot unpublish package once GitHub repository deleted

### ISSUE THREAD

**Issue by Sheng-Bo** [atom/apm#394]
This is the package I want to remove from Atom package repository:
https://atom.io/packages/chinese-menu

Would you please remove it for me manually? Because I am afraid that this broken package could cause confusion for Atom users.

My suggestions:
1. Is it possible to have a "delete package" button on my Atom user profile page?
2. Is it possible to use APM to log into GitHub before unpublish my package?

Thanks so much.

Reference: https://discuss.atom.io/t/cannot-unpublish-package-once-github-repository-deleted/18580

**Comment by bronson** [comment]
Yes, this is affecting https://atom.io/packages/policeman-rubocop too.  It makes Atom crash when you try to install it!

It would be nice if the apm package would disappear if the github repo gets deleted.

**Comment by thedaniel** [comment]
I removed those 2 packages from the DB. I'd like to make this flow better on the site and in the API, with at least a manual delete for packages owned by individuals.

**Comment by Sheng-Bo** [comment]
Hi @thedaniel, 
Thanks so much.

So how can I rename my package to chinese-menu? I tried, but it failed. 
Thanks again.

**Comment by thedaniel** [comment]
This issue was moved to atom/atom.io#5
