### ISSUE TITLE
Apm publish not working on freshly generated theme

### ISSUE THREAD

**Issue by dannyk08** [atom/apm#397]
Apm Publish command is not working on a new theme I'm trying to make.

I followed the steps to create a syntax theme [here](https://atom.io/docs/v0.60.0/creating-a-theme). And the steps to deploy/publish my theme from [here](https://atom.io/docs/v0.74.0/publishing-a-package).

This is the error I get after running the command
```shell
apm publish 
A version, tag, or new package name is required
```
I've been reading around and I think the tag might not be generated and so it's giving me this error. I've also ran ```apm login``` more than 5 times. restarted the zsh and still no go.

**Comment by mnquintana** [comment]
As the error you got and [the documentation say](https://atom.io/docs/v1.0.2/hacking-atom-package-word-count#publish-your-package), you need to specify a version (`major`, `minor`, or `patch`, corresponding to a version number of the form `major.minor.patch`, e.g. `0.2.1`). So the command is actually:

```
apm publish minor
```

*(Just as an aside, you linked to an extremely old version of Atom's documentation which is no longer valid - the latest docs can be found here: https://atom.io/docs/latest/)*

**Comment by dannyk08** [comment]
I ran that command as well.. Why did you close the issue if I haven't solve the problem any way?

**Comment by mnquintana** [comment]
In your initial post you wrote that you ran `apm publish` with no arguments, so it seemed that that was all you did. What error did you get when you ran `apm publish minor`?

**Comment by dannyk08** [comment]
```
apm publish minor                             ⏎ ✭
Preparing and tagging a new version ✓
Pushing v0.1.0 tag ✗
To git@github.com:dannyk08/light-wave.git
 ! [rejected]        HEAD -> master (fetch first)
 ! [rejected]        v0.1.0 -> v0.1.0 (already exists)
error: failed to push some refs to 'git repository'
hint: Updates were rejected because the tag already exists in the remote.
```

**Comment by mnquintana** [comment]
The error `git` is throwing is telling you that you can't publish both because your local `master` branch is behind the remote `master` branch on GitHub and because there is already a 0.1.0 tag. You need to:

1. `git pull` in the remote changes to your `master` branch
1. Either delete the v0.1.0 tag on GitHub or run `apm publish 0.2.0` instead.

Then you should be able to publish. Let me know if this works for you.

**Comment by dannyk08** [comment]
Which is why I'm starting over.. I forked from the atom's light repo and it's giving me errors. I haven't made too many changes 

Thank you for the suggestions. Hope this helps someone as well

**Comment by dannyk08** [comment]
I've at this for hours.. Can't believe something so simple can be so frustrating

```
❯ apm publish minor
Preparing and tagging a new version ✓
Pushing v0.1.0 tag ✓
Publishing light-wave-syntax@v0.1.0 ✗
Creating new version failed: Git tag not found
light-wave-syntax git:master ❯ git tag                                      ⏎
v0.1.0
❯ apm publish
A version, tag, or new package name is required
```

As you can see.. I've restarted from scratch. Pointed to the right github repo. started at ```v0.0.0``` in ```package.json``` .. I even tried making my own git tags and nothing.

Is there a way to manually do this? I'd like to contribute but this whole thing is just ridiculous.

**Comment by dannyk08** [comment]
I've "solved" the problem... [read this](https://discuss.atom.io/t/help-with-publishing-packages/18803) if you're having the same issue
