### ISSUE TITLE
Respect HTTP_PROXY and HTTPS_PROXY Environment Variables

### ISSUE THREAD

**Issue by TuckerWhitehouse** [atom/apm#398]
For some reason, apm does not respect if the HTTP_PROXY and HTTPS_PROXY environment variables are set and instead I must hard code them into my .apmrc file.

NPM respects my environment variables and works without issue.

**Comment by JPvRiel** [comment]
just to add to this, on Linux, the env proxy vars are often lowercase, so http_proxy, https_proxy, ftp_proxy and no_proxy in the shell env should be respected.

**Comment by 50Wliu** [comment]
The initial issue should be fixed by #447.  @JPvRiel if you're still experiencing problems with lowercase env vars, please create a new issue for that :sparkles:.
