### ISSUE TITLE
Creating new version failed: Not found

### ISSUE THREAD

**Issue by pyrox777** [atom/apm#403]
I tried to initially publish [this package](https://github.com/pyrox777/timestamp) to Atom.
But apm keeps responding like this:

```
$ apm publish patch
Registering timestamp done
Preparing and tagging a new version done
Pushing v0.1.2 tag done
Publishing timestamp@v0.1.2 failed
Creating new version failed: Not found
```

If publishing an already tagged version it jumps straight from Registering to the publishing error.

What I tried till now:
- Double checked my account and token is active (tried with fresh login as well)
- Always pushed last commit to GitHub before publishing
- Reset version in package.json to 0.0.0
- Published minor instead of patch
- Double checked I'm on branch master to avoid #393
- Creating tag in advance without `v`
- Added .git to url parameter in package.json

After additionally searching in the Atom support forums for this error I would now like to call for help.
I just can't figure out what is wrong.

**Comment by kyoh86** [comment]
+1

I'm trying to publish [tomorrow-night-syntax](https://github.com/kyoh86/tomorrow-night-syntax)

**Comment by pyrox777** [comment]
> I'm trying to publish tomorrow-night-syntax

I'm just curious - is this the first package you tried to publish?

**Comment by fruggiero** [comment]
It happen's for me too 

> 
> $ apm publish minor
> Registering robox-light-syntax done
> Preparing and tagging a new version done
> Pushing v1.11.0 tag done
> Publishing robox-light-syntax@v1.11.0 failed
> Creating new version failed: Not found
> 

i don't know the cause.
Actually my package isn't published.

**Comment by pyrox777** [comment]
I am not intending to necro bump this issue. Nor am I intending to publish packages to Atom anymore.

If @kyoh86 or @fruggiero still have this issue, this thread might be used as reference in a newly opened issue. But I am closing this for now.
