### ISSUE TITLE
Running apm commands mess up terminal colors

### ISSUE THREAD

**Issue by 50Wliu** [atom/apm#405]
On Windows 7 x64, running `apm publish minor` (and presumably any other command that makes use of colors) messes up the terminal's colors:
![apm-colors](https://cloud.githubusercontent.com/assets/2766036/8921917/2c51955e-34aa-11e5-8b18-8ff3c4e794bb.png)

I'm guessing this is because the green that I have is also the color apm uses for the `done` keyword, and then maybe it gets confused and tries to reset it to the default gray?

**Comment by thomasjo** [comment]
I haven't tried reproducing this yet, but colored terminal output is handled by https://github.com/Marak/colors.js. It might be worth trying to upgrade to v1.x and seeing if that resolves the issue. If not, then either open an issue on vendor repo, or migrating to a different npm package.

**Comment by 50Wliu** [comment]
Here's a picture of it on a different color scheme:
![invisible](https://cloud.githubusercontent.com/assets/2766036/8947084/aad32568-3564-11e5-8511-79050e427979.png)

I'll try updating colors to ^1 locally and seeing if that helps.

**Comment by 50Wliu** [comment]
Just happened with `node` as well...maybe this isn't apm-specific?

**Comment by 50Wliu** [comment]
Seems to have been fixed.
