### ISSUE TITLE
Incomplete sorted package listings on atom.io/packages

### ISSUE THREAD

**Issue by jacekkopecky** [atom/apm#412]
The listing sorted by stars seems to be incomplete: https://atom.io/packages/list?direction=desc&sort=downloads shows `vim-mode` there with many downloads and 505 stars, but https://atom.io/packages/list?direction=desc&sort=stars doesn't show `vim-mode` even though its 505 stars should put it right after `highlight-selected`.

**Comment by thedaniel** [comment]
This issue was moved to atom/atom.io#1
