### ISSUE TITLE
Display type info in method signatures

### ISSUE THREAD

**Issue by ssorallen** [atom/apm#413]
Surfacing type information in method signatures would make scanning the docs more valuable. For example from the TextEditor (https://atom.io/docs/api/v1.0.5/TextBuffer#section-Mutating%20Text):

Currently:
> ::setTextInRange(range, text, [options]) 
> 
> ::insert(position, text, [options]) 

Surfacing type information in the signature:
> ::setTextInRange(range: Range, text: string, options?: Object): Range
> 
> ::insert(position: Point, text: string, options?: Object): Range

The examples are formatted to fit Flow's [type annotations](http://flowtype.org/docs/type-annotations.html).

**Comment by thedaniel** [comment]
This issue was moved to atom/atom.io#2
