### ISSUE TITLE
Summarize methods in left bar, remove collapsing/expanding

### ISSUE THREAD

**Issue by ssorallen** [atom/apm#414]
This is a suggestion based on Ruby's documentation site (like http://ruby-doc.org/core-2.2.0/Array.html for example).

Currently each class documentation page for Atom (like https://atom.io/docs/api/v1.0.5/TextEditor for example) attempts to be both a table of contents and the content itself by collapsing all sections by default. This makes searching for content difficult with Cmd/Ctrl + f. If the table of contents, the list of properties and methods, instead lived in the left bar then the main content area would not need to behave like a table of contents as well and could avoid collapsing content at all.

**Comment by thedaniel** [comment]
This issue was moved to atom/atom.io#3
