### ISSUE TITLE
Link primitives to MDN's primitives doc

### ISSUE THREAD

**Issue by ssorallen** [atom/apm#415]
This is related to https://github.com/atom/atom/issues/8124

Lowercase JavaScript primitives should link to https://developer.mozilla.org/en-US/docs/Glossary/Primitive.

Atom's documentation mostly refers to the uppercase wrapper objects like Boolean, Number, and String, but nearly all of those uses should reference the lowercase primitives boolean, number, and string instead. atom.io links `{Boolean}`, etc. to the wrapper objects, but it's unclear if it correctly links primitives like `{boolean}` to a doc describing primitives like https://developer.mozilla.org/en-US/docs/Glossary/Primitive.

**Comment by thomasjo** [comment]
I'm just curious why this issue was opened on this repo; isn't this a problem across all relevant Atom repos?

**Comment by ssorallen** [comment]
Someone in Slack mentioned issues against the project site, atom.io, should be opened on this repo. This is specifically about linking `{boolean}`, `{number}`, etc. to the correct page. The code that generates the site links `{Boolean}` to its object wrapper equivalent docs page on MDN, and I'm unsure where that mapping lives; it doesn't appear to be public.

**Comment by thomasjo** [comment]
:cool:

**Comment by thedaniel** [comment]
This issue was moved to atom/atom.io#4
