### ISSUE TITLE
download node to a local cache

### ISSUE THREAD

**Issue by xnrand** [atom/apm#423]
It would make sense to cache the node.js binaries that are downloaded by script/download-node.js to a local directory (subdirectory of `.atom`) so that the whole node binaries don't have to be downloaded every time.

**Comment by kevinsawicki** [comment]
`script/download-node.js` is only run when this module is installed and cached from then on out until the version gets bumped.

Can you give specific steps to reproduce where you are seeing it being constantly downloaded?

**Comment by 50Wliu** [comment]
No response, closing.
