### ISSUE TITLE
Cannot unpublish package

### ISSUE THREAD

**Issue by elliottpost** [atom/apm#432]
During my first attempt to publish a package, I forked from an existing theme and tried modifying, but ran into several issues. I never got it to publish correctly and I cannot get it to unpublish, either. I haven't deleted the git repo yet, as I saw in another thread that it should be removed from atom.io first.

Can someone please help me unpublish https://atom.io/packages/monokai-light-blue?

I ran ```apm login``` then tried the following command:
```bash
elly@kerrigan:/var/www/html/monokai-light-blue$ apm unpublish monokai-light-blue
Are you sure you want to unpublish monokai-light-blue? (yes) yes
Unpublishing monokai-light-blue ✗
Unpublishing failed: Unauthorized```

**Comment by elliottpost** [comment]
Just following up on this issue. I still am unable to unpublish this package.

**Comment by thedaniel** [comment]
@elliottpost Done.
