### ISSUE TITLE
npm@3

### ISSUE THREAD

**Issue by Stanzilla** [atom/apm#436]
npm 3 is going final next week (https://github.com/npm/npm/releases/tag/v3.3.4) with loooots of improvements for Windows users. Just making this an issue so it is tracked and upgrading to it not forgotten.

**Comment by 4xmg** [comment]
I can't even backup all my packages to git ...we need NPM 3 now ... please?

fatal: unable to stat 'packages/clipboard-plus/node_modules/@aki77/atom-select-action/node_modules/atom-space-pen-views/node_modules/space-pen/node_modules/grim/node_modules/emissary/node_modules/es6-weak-map/node_modules/es5-ext/array/#/@@iterator/is-implemented.js': No such file or directory
