### ISSUE TITLE
Lost publish rights to my package

### ISSUE THREAD

**Issue by chamini2** [atom/apm#439]
@lee-dohm directed me here for help on regaining publishing rights to my package.

I made a fork of a unmaintained package and decided to publish it with the fixes I did, since it had been dead from 2 years. I published the fork and then decided I wanted a new repo (giving proper credit), not a fork.

So I duplicated the repo, deleted the fork, and renamed the new repo to the fork's name.

So the link to repo never changed, but now when publishing it says:

    $ apm publish --tag v0.3.4
    Publishing google@v0.3.4 ✗
    Creating new version failed: Git tag not found

**Comment by chamini2** [comment]
[I've been instructed](https://discuss.atom.io/t/cant-publish-unpublish-package/21270/2?u=chamini2) to ask for help here, what should I do?

**Comment by thomasjo** [comment]
Can you please give us the URL to the package repo you are trying to publish? Is it https://github.com/chamini2/atom-google-search.

@thedaniel Could this be a backend problem? Assuming I found the correct repo, it does indeed look as if the tags and releases are in order; https://github.com/chamini2/atom-google-search/tags.

**Comment by chamini2** [comment]
Yes, that is the repo

**Comment by chamini2** [comment]
I still can't publish anything. Is there something I could do on my end?

**Comment by chamini2** [comment]
What if I unpublish the package and publish it again/

**Comment by chamini2** [comment]
@thomasjo, @lee-dohm, any chance to get this sorted?

**Comment by thedaniel** [comment]
@chamini2 We keep track of renamed and moved repos by using the repo's ID to identify it. If you delete and recreate, even if it has the same URL, it won't work at this time. I just updated the ID for the `google` package in the database now, let me know if you have further issues.
