### ISSUE TITLE
Error during the publishing of a package 

### ISSUE THREAD

**Issue by williamd1k0** [atom/apm#441]
OS: Windows 10 and 7.
There's some kind of incompatibility issue with Git's newest version (>2.5)
When publishing it generates the following error, whether you use the `apm` the CMD or Mingw32 that comes with Git:
```shell
bash: /dev/tty: No such device or address
error: failed to execute prompt script (exit code 1)
fatal: could not read Username for 'https://github.com': No error
```
The problem was solved downgrading Git to 1.9.5
williamd1k0/language-renpy#4

**Comment by 50Wliu** [comment]
Closing in favor of atom/atom#8984.
