### ISSUE TITLE
Request for package information failed: connect EACCES

### ISSUE THREAD

**Issue by jerone** [atom/apm#442]
When running `apm update` in the console I'm getting the following error at random times more frequently then not:

> Request for package information failed: connect EACCES

Could this be related to a proxy or something? I'm at work, but sometimes the package update does work.

apm  1.0.5
Atom 1.0.19
Windows 8.1

**Comment by Aeriel** [comment]
Yes, I work under a proxy and when the proxy is not set in the `.apmrc` file, that error appears.
You can try the command `apm install minimap --verbose` and see if the proxy is set to null.

**Comment by jerone** [comment]
I just checked at work and we are not running on any proxy what so ever. Besides it does work on some random times.

I also checked your verbose command and installing is not an issue. Checking for new updates `apm update` still errors with above error message.
