### ISSUE TITLE
Hide package names that start with `.` in apm list

### ISSUE THREAD

**Issue by thedaniel** [atom/apm#446]
By default, npm symlinks installed bins generated by a package to `../.bin/`. Rather than changing this behavior (since it might be useful to keep the bins organized with the packages, and `.foo` isn't a valid package name anyway), `apm list` should omit directories with these names.

Related:

- https://github.com/atom/settings-view/pull/569
- https://github.com/atom/settings-view/issues/348

**Comment by impinball** [comment]
This is probably the best repo to file this in, as far as I can tell. :+1:

**Comment by thomasjo** [comment]
Good idea.

**Comment by bronson** [comment]
Is https://github.com/atom/apm/pull/458 what you're looking for?

**Comment by impinball** [comment]
@bronson That's exactly what we need :smile:
