### ISSUE TITLE
apm test broken on beta build

### ISSUE THREAD

**Issue by steelbrain** [atom/apm#451]
```
>>> apm-beta test
<<< Error spawning atom: spawn ENOENT
```
It should be spawning `atom-beta` instead of `atom`

**Comment by thomasjo** [comment]
It can't read your mind :smirk: — how is apm supposed to understand you wanted it to execute using `atom-build` as opposed to `atom`? I guess we could implement some extra flag for directing it to the appropriate channel (e.g. `--beta`), although I'm not entirely convinced...

You can work around this problem by doing `atom-beta --spec-directory=spec`. Soon this will simplify to `atom-beta --test spec`.

**Comment by steelbrain** [comment]
Please re-read the updated question

**Comment by thomasjo** [comment]
Aha, I wasn't even aware we created an alias for apm; then I agree, it should be directed to the correct executable.

**Comment by kn1kn1** [comment]
@steelbrain I recently found this issue can be evaded by `apm-beta test -p /usr/bin/atom-beta`. See my Dockerfile: https://github.com/kn1kn1/language-context-free/blob/master/Dockerfile.atom-beta. I hope this helps you.

**Comment by steelbrain** [comment]
@kn1kn1 It does! Thank you!

**Comment by steelbrain** [comment]
Broken as outdated
