### ISSUE TITLE
Request for package info failed. Upgrade returns HTML

### ISSUE THREAD

**Issue by thibmaek** [atom/apm#455]
Running `apm upgrade -c false` failed and returned the following:

```html
Request for package information failed: <!DOCTYPE html>
    <html>
    <head>
      <meta name="viewport" content="width=device-width, initial-scale=1">
      <style type="text/css">
        html, body, iframe { margin: 0; padding: 0; height: 100%; }
        iframe { display: block; width: 100%; border: none; }
      </style>
    <title>Application Error</title>
    </head>
    <body>
      <iframe src="//s3.amazonaws.com/heroku_pages/error.html">
        <p>Application Error</p>
      </iframe>
    </body>
    </html>
```

**Comment by izuzak** [comment]
Thanks for the report, @thibmaek. Is this still happening for you? Can you share a list of packages you have installed? And can you try updating them one-by-one to see which one is causing this? (Or does it happen for every one)?

/cc @thedaniel

**Comment by thibmaek** [comment]
Works now, maybe it was an network thing (I was doing this on the school network and now I come to think of it they changed some firewall settings over the weekend)
