### ISSUE TITLE
apm publish --amend?

### ISSUE THREAD

**Issue by danielbayley** [atom/apm#459]
Something like `apm publish --amend` might be useful for really small fixes perhaps? Especially since bumping the version number & pushing tags is so error prone at the moment (see #315 for example…)

**Comment by thomasjo** [comment]
I don't really see a valid use case for this. What's wrong with pushing a patch release? If you made a big mistake, unpublish and republish? If something failed during a publish, you can try republishing the tag via `apm publish --tag <tag>`.

You're claiming that bumping version numbers and pushing tags is something that is error prone, how would this not suffer from the same problems? How would this proposed `--amend` flag work?

Thanks in advance!

**Comment by danielbayley** [comment]
Ah, I wasn't aware that `apm publish --tag <tag>` would basically do this (i.e attempt the publish again without an additional version bump or adding another commit…) I guess `--amend` could just be an alias for `apm publish --tag <latest tag>` in that case… or not?

**Comment by thedaniel** [comment]
That's what patch releases are for. You shouldn't be modifying already-published releases of any software because that undermines the idea of having a known stable configuration.

**Comment by danielbayley** [comment]
Fair enough, I get that.

@thedaniel I only really suggested this after borking the `test` and `language-jxa` packages though (deleted the GitHub repo before `apm unpublish`), which I would *really* like deleted from the database if possible (see #221).
