### ISSUE TITLE
`apm rm .` (or uninstall) will uninstall all packages

### ISSUE THREAD

**Issue by forivall** [atom/apm#460]
I've accidentally done this a couple times when trying to remove linked packages for the official versions. Luckily, I have a list of all of my installed packages saved and a script to install all of them (for new computers).

**Comment by lee-dohm** [comment]
I'm not clear on what exactly the issue is. Are you saying you accidentally typed <kbd>.</kbd><kbd>RETURN</kbd>? So you'd like it if `apm uninstall .` would *not* uninstall everything but instead return an error?

**Comment by forivall** [comment]
Yes, i typed `apm rm .`<kbd>Return</kbd>. Yes, it should not uninstall everything, but instead either return an error or display an "Are you sure?" prompt, or unlink the package in the current directory. `npm rm .` and `npm unlink .` will unlink the package in the current directory, i.e. if there is a `package.json` in the current directory, it will uninstall the package under the `package.json`'s `name` field.

Thanks for the tip on `unlink` though. I need to RTFM the semantic difference between unlink and rm.

**Comment by socketubs** [comment]
I just run `apm uninstall .` because I've done `apm install .` just before to install my local package and every packages have been removed.

I don't really know how `apm uninstall .` must act but I think, `install` and `uninstall` must have same behaviour.

**Comment by ShaneWilton** [comment]
This just happened to a colleague of mine too. He expected `apm uninstall .` to uninstall the package in the current directory, and accidentally wiped away all of his packages.

I think it'd be a useful UX improvement to output a warning on `apm uninstall .` that asks whether you intended to uninstall all of the packages on your system.

**Comment by cdsousa** [comment]
I've just done that too 😢 
Is there a log of installed packages anywhere?

**Comment by Alhadis** [comment]
Eyyyyup, fell victim to this just now. Decided to run `apm uninstall .` from `~/.atom/packages/languages-csound`, thinking it'd have analogous behaviour to `apm install .`, but it wiped the entire `packages` folder (half of which were symlinked directories). In the middle of amending my Makefile to enable packages to be reinstalled/relinked programmatically.

> (i apologise in advance for my childishness).

You call that childish? Dude, [take it from a pro](https://github.com/Alhadis/-).
