### ISSUE TITLE
APM returns false positive on uninstall a non-installed package

### ISSUE THREAD

**Issue by stephenyeargin** [atom/apm#461]
This may be on purpose, but it seems odd. If I never installed a particular package, I feel like it should at least post a line saying "This was not installed, but we promise it is super not installed now."

Example:

```
$ apm uninstall this-package-was-never-installed
Uninstalling this-package-was-never-installed ✓
```

**Comment by 50Wliu** [comment]
This is a duplicate of #461, so please subscribe there for updates.  I really like your "we promise it is super not installed now" line though :stuck_out_tongue:.
