### ISSUE TITLE
apm requires npm@2 module paths

### ISSUE THREAD

**Issue by bengotow** [atom/apm#463]
It'd be really great if `apm` could be assembled with npm@3, since it shortens paths and prevents long paths like `apm/node_modules/npm/node_modules/npm-registry-client/node_modules/concat-stream/node_modules/readable-stream/node_modules/process-nextick-args/package.json` on Windows.

Unfortunately, if you `npm install atom-package-manager; npm dedupe` using npm 3, it flattens the entire dependency tree into a single, top-level `node_modules` folder. This causes APM to throw exceptions at runtime at lines like https://github.com/atom/apm/blob/c6e5123b17c99233b661a616ce4e09c38c2c9a07/src/deprecated-packages.coffee#L1, because it assumes `npm/node_modules/semver` will exist. In npm@3, `npm` and `semver` are placed in the same directory.

**Comment by fibric** [comment]
This would be great to have now.

I can't install `atom-beautify` on Windows because of a super long path (450+ chars, supported are only 253 chars if I remember correctly).

```npm ERR! enoent ENOENT, rename 'C:\Users\DENNY~1.TRE\AppData\Local\Temp\apm-install-dir-11649-26316-1wk7hl\node_modules\atom-beautify\node_modules\analytics-node\node_modules\superagent-proxy\node_modules\proxy-agent\node_modules\pac-proxy-agent\node_modules\pac-resolver\node_modules\regenerator\node_modules\commoner\node_modules\glob\node_modules\minimatch\node_modules\brace-expansion\node_modules\balanced-match\package.json.5aac7555444b0595f7885a7a434656b6'```
