### ISSUE TITLE
fail to install atom/apm to linux mint 

### ISSUE THREAD

**Issue by tahenti** [atom/apm#465]
i have linux mint 17 
i try to build atom from source srcipt/build but it fail. i am a new user . 
this  is my log file 
beya-Lenovo-Z50-70 atom # script/build
Node: v5.0.0
npm: v3.3.6
Installing build modules...
Installing apm...
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: write EPROTO
    at Object.exports._errnoException (util.js:860:11)
    at exports._exceptionWithHostPort (util.js:883:20)
    at WriteWrap.afterWrite (net.js:763:14)
npm ERR! Linux 3.16.0-38-generic
npm ERR! argv "/usr/local/bin/node" "/home/beya/atom/build/node_modules/.bin/npm" "--userconfig=/home/beya/atom/build/.npmrc" "--target=0.10.35" "install" "--loglevel" "error"
npm ERR! node v5.0.0
npm ERR! npm  v2.13.3
npm ERR! code ELIFECYCLE

npm ERR! atom-package-manager@1.1.1 install: `node ./script/download-node.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the atom-package-manager@1.1.1 install script 'node ./script/download-node.js'.
npm ERR! This is most likely a problem with the atom-package-manager package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./script/download-node.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls atom-package-manager
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/beya/atom/apm/npm-debug.log

**Comment by thedaniel** [comment]
Could you attempt to build with node 4.2 or 0.12?

**Comment by tahenti** [comment]
how to know it . I am just starting with linux :'(

**Comment by tahenti** [comment]
i think i an unsing node v5.0.0
