### ISSUE TITLE
Documentation for using apm programmatically with an Electron app

### ISSUE THREAD

**Issue by davej** [atom/apm#475]
I'm interested in using apm with an Electron app but it's difficult to find any documentation. Is this something that is an encouraged use case? Is it a case of running the command in a child_process or is there a better way to do it?

Can I easily change the install path from `~/.atom/packages` to something else? Or do I need to fork the project to do that?

**Comment by thedaniel** [comment]
This isn't a supported use case for apm. apm is Atom-specific and the package listing on atom.io is only for packages that run in Atom. Could you go into a little more detail about what you want to do? Where are you getting the packages from? Are you planning to provide some kind of public package listing, etc?

**Comment by davej** [comment]
Thanks for replying. The packages are just npm packages but some of them have native components so I want them built against chromium's headers.

My use case: my app is used for transpiling css/html/js but I don't want to bloat the initial application size by including all of the modules. Instead I want the preprocessing/transpiling libs to be installed and **updated** independently of the app.

I noticed that apm was also used in https://github.com/nylas/N1

**Comment by thedaniel** [comment]
Take a look at https://github.com/electronjs/electron-rebuild

**Comment by davej** [comment]
Ok Thanks for your help!

I think I should be able to put something together using npm (with `--prefix`), [electron-rebuild](https://github.com/electronjs/electron-rebuild), [app-module-path](https://github.com/patrick-steele-idem/app-module-path-node), and [npm-check-updates](https://www.npmjs.com/package/npm-check-updates).
