### ISSUE TITLE
Weird message after package update through the command line

### ISSUE THREAD

**Issue by abe33** [atom/apm#476]
When running `apm update` and there's available update, at the end of the install, the command terminate with the following message: 

```
/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:163
let prepareStackTrace = prepareStackTraceWithSourceMapping
^^^
✓
```
IMO it looks like the file is loaded in an environment that doesn't support `let`. An easy fix would be to get rid of the `let` keyword here, but it won't really prevent this kind of issue in the future.

It doesn't prevent from installing any of the updates so I'm not really sure how it should be labelled.

**Comment by 50Wliu** [comment]
This has been fixed.
