### ISSUE TITLE
Unpublishing failed: Unauthorized, i not unpublish my package

### ISSUE THREAD

**Issue by TOP-Chao** [atom/apm#483]
My package is atom-file-watchers (https://github.com/TOP-Chao/atom-file-watchers).

Wrong operation i deleted the package from github, and then exec  atom-file-watchers, but, this is not possible, the message is Unpublishing failed: Unauthorized

staff, i realy need help. I have lost the package control now  @thedaniel 

SOS...

**Comment by TOP-Chao** [comment]
staff, i realy need help. @thedaniel

**Comment by 50Wliu** [comment]
I'm pretty sure most if not all of the GitHub staff is on holiday break right now, so you might need to wait a bit longer.  Sorry.

**Comment by thedaniel** [comment]
@TOP-Chao I've unpublished the package for you.
