### ISSUE TITLE
Creating new version failed: Not found

### ISSUE THREAD

**Issue by TOP-Chao** [atom/apm#486]
$ `apm publish atom-file-watchers`
Registering atom-file-watchers ✓
Preparing and tagging a new version ✗
npm ERR! npm version [<newversion> | major | minor | patch | premajor | preminor | prepatch | prerelease]
npm ERR! (run in package dir)
npm ERR! 'npm -v' or 'npm --version' to print npm version (2.13.3)
npm ERR! 'npm view <pkg> version' to view a package's published version
npm ERR! 'npm ls' to inspect current package/dependency versions

$ `apm publish -t v0.0.3`
Registering atom-file-watchers ✓
Publishing atom-file-watchers@v0.0.3 ✗
Creating new version failed: Not found

$ `apm publish -t 0.0.3`
Registering atom-file-watchers ✓
Publishing atom-file-watchers@0.0.3 ✗
Creating new version failed: Not found

$ `git tag`
v0.0.1
v0.0.2
v0.0.3

$ `apm -v`
apm  1.4.1
npm  2.13.3
node 0.10.40
python 2.7.10
git 2.5.4

project : https://github.com/TOP-Chao/atom-file-watchers

@thedaniel

**Comment by TOP-Chao** [comment]
https://github.com/atom/apm/issues/483 ~ 
Whether the problem was caused because the name is repeated

**Comment by thedaniel** [comment]
We discussed this in chat - it turned out that the repo was deleted and recreated, changing its numeric ID. I fixed it for @TOP-Chao, and now that the new version has been published I'm closing this issue.

**Comment by airclear** [comment]
apm unpublish
then apm publish
