### ISSUE TITLE
Can't unpublish or publish after deleting original package repo

### ISSUE THREAD

**Issue by francoislaberge** [atom/apm#489]
Hi. We created a repo for ```jiborobot/jibo-atom``` and then decided to start from a new clean history so we deleted and recreated the ```jiborobot/jibo-atom``` repo. Now we can't publish our package using ```apm publish```. We get:

apm publish patch
Preparing and tagging a new version ✓
Pushing v0.0.12 tag ✓
Publishing jibo-atom@v0.0.12 ✗
Creating new version failed: Git tag not found

**Comment by lee-dohm** [comment]
Yes, this is the expected behavior. It is [documented in the Flight Manual](https://atom.io/docs/latest/behind-atom-maintaining-your-packages#unpublish-your-package), though I agree that the section in the documentation doesn't exactly match your situation.

Did you need help regaining access? Or were you only intending to report a bug in apm?

**Comment by francoislaberge** [comment]
We are under a tight deadline to launch a private beta tomorrow and this ended up causing us some strife. We ended up just having to rename our module ```jibo-sdk```, start a new repo, and search and replace for all ```jibo-atom``` to ```jibo-sdk```.

**Comment by francoislaberge** [comment]
We're at late (east coast) and now a little sleep deprived crazy, so I think we've just sworn off the module name and accepted it. Thanks for the quick response. We know the gotcha now, won't be happening eva again.

**Comment by francoislaberge** [comment]
Oh, though can you please delete ```jibo-atom``` as we can't unpublish it as mentioned in the docs you just linked.

**Comment by lee-dohm** [comment]
Sorry that you ran into such problems. I'll work with the team to get it unpublished. Thanks for understanding!

**Comment by francoislaberge** [comment]
Awesome, thanks!

**Comment by francoislaberge** [comment]
Hey Lee, any movement on this? We have a blocking bug or two remaining and then we'll be sending out an invite email to our early private beta users.

**Comment by lee-dohm** [comment]
Sorry for the delay, I'll be working with another member of the team in about an hour to teach me the backend stuff to fix this. I'm assuming you want to publish under the original name @francoislaberge?

**Comment by francoislaberge** [comment]
No worries, just wanted to see if you had an ETA. Appreciated. I believe it's @francoislaberge, yup.

**Comment by lee-dohm** [comment]
Ok, just to make sure that I'm understanding: you want jiborobot/jibo-atom to be able to publish the jibo-atom Atom package again? I'll see if this is possible and it probably won't be quick from what I understand by talking to another team member.

The quick option is for me to unpublish `jibo-atom` and the system will prevent anyone from reclaiming the name.

Let me know which one you want me to do.

**Comment by francoislaberge** [comment]
We were hoping you could delete jiborobot/jibo-atom. We moved to using jiborobot/jibo-sdk to work around the issue. If jibo-atom was then freed up that would be cool. We're ok with risk of it being grabbed in the small window before we might grab it ourselves

**Comment by lee-dohm** [comment]
Thanks @francoislaberge ... I'll take a look and get back to you.

**Comment by francoislaberge** [comment]
Thank you!

**Comment by lee-dohm** [comment]
Ok ... [jibo-atom](https://atom.io/packages/jibo-atom) is now unpublished. There currently isn't a way in the system to reclaim the name though. This prevents issues with weird auto-upgrade situations. But at least there won't be any confusion between the two packages.

I know it wasn't exactly what you wanted, but I hope it helps. Let me know if there's anything else I can do :blush:

**Comment by francoislaberge** [comment]
That works. You are awesome for jumping on this. Now I sleep, launch day burn.

**Comment by lee-dohm** [comment]
Have a well-deserved :zzz:
