### ISSUE TITLE
Can't unpublish package

### ISSUE THREAD

**Issue by bali182** [atom/apm#491]
Sorry for this, but I both renamed and deleted-and-recreated a repo, which was partially published (`apm publish` failed, but something appeared in the package registry), and now it's in a zombie state. 

Could you please delete this package:

https://atom.io/packages/autocomplete-semantic-json

Thanks,
Balazs

**Comment by bali182** [comment]
Any progress on this? Do you need more information?

**Comment by thedaniel** [comment]
Sorry about the delay - I've been traveling. The package has been deleted - let me know if you need any more help!

**Comment by bali182** [comment]
Thank you very much! Hope you had a good vacation :)
