### ISSUE TITLE
Not authorized to unpublish package that I created

### ISSUE THREAD

**Issue by Muffinoota** [atom/apm#492]
I'm unable to unpublish a package that I created and tried to publish. Here is a screenshot of the commands that I used and their outcomes.![2264fcf88efcc22dac08118ae8fefa5c](https://cloud.githubusercontent.com/assets/16392448/12403984/7b1a4492-bdfd-11e5-8b51-afa13e9048c2.png)
 I tried running as admin, regenerating my token, and updating NPM, none of them let me unpublish. Here is a screenshot of the package showing up under my account.
![4db7ed7ec42284909d708e027e6aabde](https://cloud.githubusercontent.com/assets/16392448/12404013/b2378eb2-bdfd-11e5-9c18-2cf4c41f5d8b.png)
The package does not show up when you search for it inside of atom. Am I missing a step to unpublishing the package?

**Comment by bali182** [comment]
Having the same issue, did you by any chance rename or delete then recreate the underlying repo? Reading the related issues, if you have done so, the package can only be manually deleted by atom.io admins.

**Comment by Muffinoota** [comment]
I'm pretty sure that I did that exactly.
I contacted github and they told me to open up an issue on here.
Is there a way for me to flag it, or contact an admin to have it deleted?

**Comment by bali182** [comment]
I think when they have the time, they will do it for you, though I'm not sure about who to contact, or how complicated it is to remove the "zombie package". In fact I just submitted the issue today, same as you :)

**Comment by thedaniel** [comment]
Do you mind going to the atom.io website, logging out and in and trying again?

**Comment by Muffinoota** [comment]
### It's still there :/
![](https://i.gyazo.com/9dbc4e91853f827a91b26b6bbf4bdca2.gif)
Also I regenerated the token after capturing those so I should be safe

**Comment by thedaniel** [comment]
Oh, I'm sorry, I came back to this tab after doing something else and missed that you deleted the repo! That's the problem. I'll just unpublish it in the admin interface.

**Comment by Muffinoota** [comment]
Thanks!
