### ISSUE TITLE
How to add images, so they show up both on atom.io and github.com

### ISSUE THREAD

**Issue by bali182** [atom/apm#495]
Ok, it seems like this is something, that everybody knows except me. 

I tried adding an image displaying, what my package does. I added it directly to my files, https://raw.githubusercontent.com/bali182/autocomplete-json/master/demo.gif and referenced it in my `readme.md` like this (this looked like the most straight forward thing to do): 

`![Demo image](/demo.gif "Demo")`

This showed up nicely on github, but did not on atom.io. Then I tried with full URL:

`![Demo image](http://github.com/bali182/autocomplete-json/raw/master/demo.gif "Demo")`

Which was blocked on github. Then I looked at how other packages are doing it, this is `autocomplete+` for example:

`![autocomplete+](https://cloud.githubusercontent.com/assets/744740/7656861/9fb8bcc4-faea-11e4-9814-9dca218ded93.png)`

But I was not able to find any information, about how to publish something on https://cloud.githubusercontent.com .

Can you please give me some hints about this?

**Comment by 50Wliu** [comment]
@bali182 You can drag the picture into an issue comment, which will automatically upload it and give you a URL.  Hope that helps!

**Comment by bali182** [comment]
Thanks, would never have guessed this :)

**Comment by kuzyn** [comment]
This work as a workaround, but does not really address the issue. Shouldn't apm deduce that assets with relative paths are relative to repository and not to itself?
