### ISSUE TITLE
Why ship the ancient node

### ISSUE THREAD

**Issue by steelbrain** [atom/apm#497]
It causes problems with npm scripts, like the one we caught in [linter-eslint](https://github.com/AtomLinter/linter-eslint/pull/412#issuecomment-174691386).

If my understanding is correct, APM is meant to be used with Electron and/or Atom, if that's the case why not use the electron binary directly with `ELECTRON_INTERNAL_RUN_AS_NODE` cli var?

**Comment by lee-dohm** [comment]
The answer is here: https://github.com/atom/apm/issues/410
