### ISSUE TITLE
Atom fails to correctly read any files including its config and packages

### ISSUE THREAD

**Issue by Hugoch** [atom/apm#500]
When I start atom, the editor complains that it can't read config.cson and packages. Opening any file in atom gives me rubbish characters whatever the encoding. Opening the same file in another editor works fine.
![image](https://cloud.githubusercontent.com/assets/733386/12645843/02f36d7c-c5cd-11e5-99f8-252f95167066.png)
![image](https://cloud.githubusercontent.com/assets/733386/12647743/0555aab2-c5d7-11e5-8243-51cac14caeab.png)

I have to reboot the computer to get it right. After a few start/stop of atom (I can't figure which event breaks everything) the bug reapears.

Trying to start atom from the command line (cmd.exe), I get
![image](https://cloud.githubusercontent.com/assets/733386/12647705/c07cc2fe-c5d6-11e5-9b17-57663878ce62.png)
Safe mode does not work either.

I upgraded from 1.4 to 1.4.1, same behavior. I tried to disable my packages, no success.

I'm running on W7.

Any clues ?

**Comment by lee-dohm** [comment]
Do you alter or modify (or even open) the `config.cson` before the corruption occurs?

**Comment by Hugoch** [comment]
Nope. I realise I messed up with my browser tabs and this should live in the atom repo. Closing and reopening there ...
