### ISSUE TITLE
Attempted to rename a package, instead got duplicate package

### ISSUE THREAD

**Issue by plttn** [atom/apm#504]
My goal was to rename [tubster-syntax](https://atom.io/themes/tubster-syntax) to [pubster-syntax](https://atom.io/themes/pubster-syntax), but somehow the wires got crossed and I ended up with a dupe, rather than renaming the original, which was what I wanted. 

Is there a solve for this (assuming on the backend)?

**Comment by plttn** [comment]
**cc** @thedaniel since it seems like you're the one that ends up solving most backend apm related issues.

**Comment by thedaniel** [comment]
Hey there, I'll take a look at this today.Thanks for being patient.

**Comment by thedaniel** [comment]
OK, this is fixed, and will also redirect from `tubster-syntax` for future updates & installs.. Let me know if you need anything else :)

**Comment by plttn** [comment]
Great, thanks :+1:
