### ISSUE TITLE
Upgrade to npm3

### ISSUE THREAD

**Issue by gaurav21r** [atom/apm#510]
Windows is showing the **path too long error**. Also apm is taking drastically long to install some packages, that too without any progress indicators!

**npm** has resolved above issues in npm3+

Any technical difficulties in upgrading?

https://github.com/npm/npm/issues/3697

**Comment by lee-dohm** [comment]
This is a duplicate of https://github.com/atom/apm/issues/436. You may want to subscribe there for updates.
