### ISSUE TITLE
Can't install packages on Windows 7

### ISSUE THREAD

**Issue by Saturate** [atom/apm#513]
I can't install packages from Atom or from the commandline. However the C++ Tool Chain is installed and I'm able to install c++ dependent packages from npm (`npm install bufferutil`), also followed everything on the [nodejs windows guidelines](https://github.com/Microsoft/nodejs-guidelines/blob/master/windows-environment.md#environment-setup-and-configuration).

Example: `apm install minimap` outputs:

```
Installing minimap to C:\Users\USER\.atom\packages
gyp info it worked if it ends with ok
gyp info using node-gyp@2.0.2
gyp info using node@0.10.40 | win32 | ia32
gyp http GET https://atom.io/download/atom-shell/v0.34.5/node-v0.34.5.tar.gz
gyp WARN install got an error, rolling back install
gyp
```

`apm --version`'s output:

```
apm  1.6.0
npm  2.13.3
node 0.10.40
python
git
visual studio 2012
```

`apm --check`'s output:

```
Checking for native build tools failed                                            
                                                                                  
gyp info it worked if it ends with ok                                             
gyp info using node-gyp@2.0.2                                                     
gyp info using node@0.10.40 | win32 | ia32                                        
gyp http GET https://atom.io/download/atom-shell/v0.34.5/node-v0.34.5.tar.gz      
gyp WARN install got an error, rolling back install                               
gyp                                                                               
```

The thing that bugs me is that it's saying `visual studio 2012` when I run `apm --version`, is there anything I can do to set what platform I have on my machine?

**Comment by damieng** [comment]
There are some notes about setting the environment variable for GYP to tell it which VS version at https://github.com/atom/atom/blob/master/docs/build-instructions/windows.md

Also if you are using VS2015 do not use GitHub Shell for now as it has an old version of msbuild in the path and that causes issues.

**Comment by Saturate** [comment]
I'm using Powershell 4, and I did set `GYP_MSVS_VERSION` also tried to do it again, but no luck it still gives me the same error.

**Comment by Saturate** [comment]
Okay so it seems everything was fine, but for some reason a proxy was the issue.

I did the following:

```
apm config set proxy http://1.2.3.4:8080
apm config set https-proxy http://1.2.3.4:8080
```

And now everything works. It seems like the `apm install --check` fails due to connection and not really a build step, better error handling would be very handy for debugging this.

**Comment by damieng** [comment]
Are you using the same proxy for apm as your system proxy (the one from IE connection settings)?

Trying to figure out if there is an issue with apm not picking up system proxy settings.

**Comment by Saturate** [comment]
Yes, the problem is that it's not picking up the system proxy on Windows 7. After I set it manually it works.

**Comment by damieng** [comment]
Known issue with Windows proxy integration.

**Comment by Tset-Noitamotua** [comment]
Is there a solution or at least a known workaround?

**Comment by Saturate** [comment]
@Tset-Noitamotua I sovled my problem here; by settings it manually: https://github.com/atom/apm/issues/513#issuecomment-193215499

**Comment by Tset-Noitamotua** [comment]
Here is [THE SOLUTION](https://github.com/atom/apm/issues/322#issuecomment-196835163) propably for many many Windows users!!!

Can u please put it in the docs or FAQs in big big BIG LETTERS and make it blink and flash and let it make noise, too :)))

@Saturate, you are right, too. But a special attention needs to be payed to the one f****** character  `s` which MUST NOT be used in `http://proxy..bla..bla` ... just **http** NOT **https**, you know!!! ;-)))

**Comment by Tset-Noitamotua** [comment]
@Saturate, you are right, too.

But a special attention needs to be payed to the one f****** character  `s` which MUST NOT be used in `http://proxy..bla..bla` ... just **http** NOT **https**, you know!!! ;-)))
