### ISSUE TITLE
APM not working under LTS version of Node.js

### ISSUE THREAD

**Issue by krrg** [atom/apm#514]
I recently updated my system node version to 4.2.4.  When I try to use `apm` however, it gives me the following output:

`/usr/share/atom/resources/app/apm/bin/node: bad option: --harmony_collections`

Are there any plans to support newer versions of Node.js?

**Comment by alice-em** [comment]
I have the same issue on Fedora 23.

**Comment by lee-dohm** [comment]
The apm tool packages its own version of Node. Did you by chance try to replace the one that comes packaged with apm?

**Comment by krrg** [comment]
On my system, the `apm` tool was symlinked to /usr/bin/node

**Comment by alice-em** [comment]
How exactly do I change the symlink on apm to point to the right version of node*, instead of pointing to my global node installation?

*I assume the right node is `/usr/share/atom/resources/app/apm/bin/node`

**Comment by krrg** [comment]
@alice-em did you use a copr repository on Fedora to install atom?  Or did you use the RPM provided by atom?

**Comment by alice-em** [comment]
I used the copr repo.  Should I not use that and instead use the atom .rpm?

**Comment by krrg** [comment]
Yeah, looks like this is a problem with the copr repo.  The RPM from atom comes with the correct version of node, whereas the copr repo version just uses the system version.

**Comment by alice-em** [comment]
alrighty! Thanks, that solved it on my end.

**Comment by krrg** [comment]
Closing this ticket, since this turned out to not be a problem with apm, but with an unofficial distribution channel for atom.

**Comment by lee-dohm** [comment]
Thanks for following up @krrg! Glad to hear it is fixed for you :grinning:
