### ISSUE TITLE
Help to remove a obsolete package

### ISSUE THREAD

**Issue by m2q1n9** [atom/apm#517]
> It is important that you unpublish your package before deleting your repository. If you delete the repository first, you will lose access to the package and will not be able to recover it without assistance.

https://atom.io/packages/language-sproto

I can't unpublish this package, because the repo is deleted...
can someone help me to remove it?

**Comment by lee-dohm** [comment]
Do you want it deleted? Or do you want it unpublished so that you can republish it again?

**Comment by m2q1n9** [comment]
delete,  this package is obsolete.

**Comment by lee-dohm** [comment]
Done. Thanks for the quick reply! :grinning:

**Comment by m2q1n9** [comment]
Thanks :)
