### ISSUE TITLE
Need help republishing package after repo delete/recreation

### ISSUE THREAD

**Issue by fasterthanlime** [atom/apm#524]
Hey, experiencing one of the many duplicates of #483 / #486 - I published a package from a repository, then deleted & re-created the repository (for reasons discussed in https://github.com/JonathanMH/nothrill-dark-syntax/issues/2), and am now unable to push new versions / unpublish-republish the package.

Could @thedaniel use his magical dba powers once again? Sorry to bother you with this :panda_face:

**Comment by thedaniel** [comment]
Should be fixed now!

**Comment by fasterthanlime** [comment]
Can confirm it's fixed, thanks @thedaniel! :star2:
