### ISSUE TITLE
Docs improvements

### ISSUE THREAD

**Issue by kevinSuttle** [atom/apm#527]
Followed the instructions in the README, because I can't open the Atom app on Mac. 

Running the executable locally doesn't work. 
```
⬡  ./bin/apm config
dyld: lazy symbol binding failed: Symbol not found: _node_module_register
  Referenced from: /Users/kevinSuttle/Code/apm-master/node_modules/git-utils/build/Release/git.node
  Expected in: dynamic lookup

dyld: Symbol not found: _node_module_register
  Referenced from: /Users/kevinSuttle/Code/apm-master/node_modules/git-utils/build/Release/git.node
  Expected in: dynamic lookup

./bin/apm: line 28: 15735 Trace/BPT trap: 5       "$binDir/$nodeBin" --harmony_collections "$binDir/../lib/cli.js" "$@"
```

I tried making an alias. That didn't work. 

Tried making a symbolic link. That didn't work either.

Tried moving it. That didn't work either.
```
⬡  apm
/usr/local/bin/node: bad option: --harmony_collections
```

Tried re-building it. Nope. `apm` is here in the repo. Not sure what we're rebuilding, then.

**Comment by 50Wliu** [comment]
> /usr/local/bin/node: bad option: --harmony_collections

This usually means that `apm` is using the wrong version of Node.  Can you try building using Node 0.10?

**Comment by kevinSuttle** [comment]
Yeah, I'm using 
```bash
⬡  node -v
v5.9.1
```

**Comment by mnquintana** [comment]
Yup, sounds like you're running into https://github.com/atom/apm/issues/410 – unfortunately you'll need to build `apm` with Node 0.10 for the time being. :disappointed:
