### ISSUE TITLE
Fetching packages fails on Windows with space in system usernames

### ISSUE THREAD

**Issue by nilayk** [atom/apm#535]
On `Windows 10`, with `Atom 1.6.1` installed, the package manager fails to search for or fetch features packages and themes when the system username contains spaces in between.

It seems like a case of missing quotes in the scripts somewhere.

![image](https://cloud.githubusercontent.com/assets/278733/14163356/76289a58-f6a9-11e5-8c54-ebe49762c9b1.png)

**Comment by damieng** [comment]
I just tried to repro this on 1.7.4 and wasn't able to - is it still an issue for you on that version?

**Comment by damieng** [comment]
No response. closing.
