### ISSUE TITLE
Unable to publish or unpublish `language-factor`

### ISSUE THREAD

**Issue by ForNeVeR** [atom/apm#545]
I've published the initial version of [language-factor](https://atom.io/packages/language-factor) from [my own repository](https://github.com/ForNeVeR/atom-language-factor). Everything was okay before we've decided to merge my initial changes into [the upstream repository](https://github.com/factor/atom-language-factor).

For example, if I clone the upstream repository and try to do `apm publish minor`, then I get the following message:

```
Preparing and tagging a new version done
Pushing v0.2.0 tag done
Publishing language-factor@v0.2.0 failed
Creating new version failed: Git tag not found
```

While trying to solve the problem, I've deleted and re-forked [my repository](https://github.com/ForNeVeR/atom-language-factor) from the upstream. Maybe that was a mistake, because now I cannot unpublish the package (to publish it from the new repository). When I'm trying that, I get an error:

```
> apm unpublish
Are you sure you want to unpublish language-factor? (yes)
Unpublishing language-factor failed
Unpublishing failed: Unauthorized
```

I've tried to invoke `apm login`, but it does not help (it opens the browser, I copy an access token, but `apm` still tells me that I'm "unauthorized").

`language-factor` shows up on [my atom.io personal page](https://atom.io/users/ForNeVeR), but I cannot either publish or unpublish it. What should I do now? I want to publish the new version from [the upstream repository](https://github.com/factor/atom-language-factor) (I've been granted the write access to it).

Ah, and I'm using Windows. May it be the source of the problem?

`apm -v` tells me the following:

```
> apm -v
apm  1.9.2
npm  2.13.3
node 0.10.40
python 2.7.11
git 2.8.1.windows.1
visual studio 2013
```

**Comment by lee-dohm** [comment]
I unpublished the package. You may want to familiarize yourself with the [Maintaining Your Package](http://flight-manual.atom.io/behind-atom/sections/maintaining-your-packages/) section of the Atom Flight Manual.

**Comment by ForNeVeR** [comment]
Thank you, it helped a lot!
