### ISSUE TITLE
License file not found on website

### ISSUE THREAD

**Issue by puranjayjain** [atom/apm#546]
I have published my package using apm and my repo has the LICENSE.md file but the atom website shows it as not found.
Possible reasons must be that on he first commit on the repo it was named LICENSE and was subsequently renamed LICENCE.md
My package is located here https://atom.io/packages/chrome-color-picker

**Comment by puranjayjain** [comment]
issue resolved manually by @lee-dohm but the issue remains on some of my packages.
https://atom.io/themes/chrome-dark-syntax
https://atom.io/packages/autocomplete-nunjucks

This needs to be fixed so that no manual intervention is required in the future.

**Comment by 50Wliu** [comment]
Closing in favor of atom/atom.io#68 as that's probably where this issue belongs.
