### ISSUE TITLE
Package installation issues

### ISSUE THREAD

**Issue by mcarpenterjr** [atom/apm#548]
I am running into an issue trying to install an atom plugin, atom-beautify specifically. I have worked with the creator and seemed to have narrowed the issue down to something with apm... possibly. I was curious to see if anyone might be able to help, below is the output from the windows command prompt.

```
C:\Windows\system32>npm cache clean -f
npm WARN using --force I sure hope you know what you are doing.

C:\Windows\system32>apm install atom-beautify
Installing atom-beautify to C:\Users\Mark N Carpenter Jr\.atom\packages failed

> spawn-sync@1.0.15 postinstall C:\Users\MARKNC~1\AppData\Local\Temp\apm-install
-dir-116324-5396-19zaics\node_modules\atom-beautify\node_modules\cross-spawn\nod
e_modules\spawn-sync
> node postinstall

Installing native dependencies (this may take up to a minute)

npm WARN engine analytics-node@2.1.0: wanted: {"node":">= 0.12.x"} (current: {"n
ode":"0.10.40","npm":"2.13.3"})
npm WARN engine typescript-formatter@2.1.0: wanted: {"node":">= 4.2.0"} (current
: {"node":"0.10.40","npm":"2.13.3"})
npm WARN deprecated lodash@1.2.1: lodash@<3.0.0 is no longer maintained. Upgrade
 to lodash@^4.0.0.
npm WARN optional dep failed, continuing fsevents@1.0.11
npm WARN engine deep-extend@0.4.1: wanted: {"node":">=0.12.0","iojs":">=1.0.0"}
(current: {"node":"0.10.40","npm":"2.13.3"})
npm WARN engine is-buffer@1.1.3: wanted: {"node":">=0.12"} (current: {"node":"0.
10.40","npm":"2.13.3"})
npm WARN optional dep failed, continuing source-map@0.1.43
npm WARN engine is-buffer@1.1.3: wanted: {"node":">=0.12"} (current: {"node":"0.
10.40","npm":"2.13.3"})
npm WARN engine is-buffer@1.1.3: wanted: {"node":">=0.12"} (current: {"node":"0.
10.40","npm":"2.13.3"})
npm WARN engine is-buffer@1.1.3: wanted: {"node":">=0.12"} (current: {"node":"0.
10.40","npm":"2.13.3"})
npm WARN engine is-buffer@1.1.3: wanted: {"node":">=0.12"} (current: {"node":"0.
10.40","npm":"2.13.3"})
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Users\\Mark N Carpenter Jr\\AppData\\Local\\atom\\app-1.7.2\\
resources\\app\\apm\\bin\\node.exe" "C:\\Users\\Mark N Carpenter Jr\\AppData\\Lo
cal\\atom\\app-1.7.2\\resources\\app\\apm\\node_modules\\npm\\bin\\npm-cli.js" "
--globalconfig" "C:\\Users\\Mark N Carpenter Jr\\.atom\\.apm\\.apmrc" "--usercon
fig" "C:\\Users\\Mark N Carpenter Jr\\.atom\\.apmrc" "install" "C:\\Users\\MARKN
C~1\\AppData\\Local\\Temp\\d-116324-5396-13k1cv0\\package.tgz" "--target=0.36.8"
 "--arch=ia32"
npm ERR! node v0.10.40
npm ERR! npm  v2.13.3
npm ERR! file C:\Users\Mark N Carpenter Jr\.atom\.apm\amdefine\1.0.0\package\pac
kage.json
npm ERR! code EJSONPARSE

npm ERR! Failed to parse json
npm ERR! Unexpected token '\u0000' at 1:1
npm ERR!

npm ERR! ^
npm ERR! File: C:\Users\Mark N Carpenter Jr\.atom\.apm\amdefine\1.0.0\package\pa
ckage.json
npm ERR! Failed to parse package.json data.
npm ERR! package.json must be actual JSON, not just JavaScript.
npm ERR!
npm ERR! This is not a bug in npm.
npm ERR! Tell the package author to fix their package.json file. JSON.parse
```

This is the same error that is displayed when trying to install the plugin through atom itself.

I am particularly stumped by this set of lines;
```
npm WARN engine is-buffer@1.1.3: wanted: {"node":">=0.12"} (current: {"node":"0.
10.40","npm":"2.13.3"})
```
 only because if I get the version of both node and npm I get this output;
```
C:\Windows\system32>node -v
v5.10.1

C:\Windows\system32>npm -v
3.8.3
```

I have tried uninstalling and re-installing nodejs on multiple occasions, switching up versions from the LTS and Stable, as well as between the 64 and 32 bit versions. If I am understanding the output right from installing the package the proper version is not being picked up by apm.

I am fairly new to this so any help would be much appreciated.

**Comment by 50Wliu** [comment]
`apm` uses Node 0.10.40 internally - we haven't managed to update it yet.

**Comment by mcarpenterjr** [comment]
going to close this, found a solution.

the following is from the problem package issue,

> So I am closing this issue, because I have reached a resolution. I ultimately did a clean install of atom, github desktop, node and python. to rule out all major suspects. Ultimately though, I can conclude in the windows user temp folder ``` %AppData%\Local\Temp\``` dirty installs and upgrades for what ever reason are being left behind, simple restarts won't clear them. I deleted all folders associated with npm, apm and atom before doing a fresh install. This cleared the issue, took a couple trial and errors to make sure old packages were not left behind. 
Also clearing ``` C:\Users\Your_User_Name\.atom ``` may help. Although I believe this is for current packages.

> I did also find that most of these install errors of this nature sometimes relate to deep file trees created when installing packages and their dependencies, windows does not like deep file trees.
