### ISSUE TITLE
Nested filenames too long on Windows

### ISSUE THREAD

**Issue by steronydh** [atom/apm#549]
I've found that the temporary folders created during the install of atom-beautify create filenames too long to put in the Recycle Bin and too long to shift-delete. I had to move some of the nested folders up a couple of levels to shorten their path length before I was able to delete them.

A very odd side effect: before I deleted the files manually, I ran Disk Cleanup and it reported there was over 1TB of data to delete from the temporary folder. After deleting the nested-too-deep folder, Disk Cleanup reported the correct size.

If this is a side effect of the nested-too-deep folders then it's a dangerous one!

**Comment by lee-dohm** [comment]
Due to certain constraints, we can't update the version of npm that apm is based upon. That is what is causing this problem and it is being tracked in https://github.com/atom/apm/issues/436. You may want to subscribe there for updates.

**Comment by steronydh** [comment]
This is such a serious problem that I'm not using Atom until it's fixed. It's not worth the risk of disk corruption...
