### ISSUE TITLE
APM fails to update my packages after long periods of time. 

### ISSUE THREAD

**Issue by abeltensor** [atom/apm#553]
So I'm on windows 10 64bit (the stable release).  I have node 4.4.4 and npm 3.5.3, my APM version says 1.9.2, with python 3.5.1 and visual studio 2013 (despite having 2015 installed).  

When I run an APM update in the cmd prompt, the command starts to spawn 4-5 different node processes and then ramps up my CPU/memory usage to about 99%.  I let it sit for like 30 minutes earlier before i quit out because obviously I am having issues.  After quitting out, when i run the command again, the package that it "hung" on is no longer on the APM update list and it hangs on the next one.  (currently proto-repl 1.1.9.)

Before, when i physically opened atom and ran the auto update, all of the to-be updated packages threw an exception that I was missing either VS or Python on my computer or in my path, this was resolved after restarting the shell but I still encountered packages with infinitely long update bars as well as 10-15 node processes and had to quit out of Atom as a result.

**Comment by abeltensor** [comment]
Issue was resolve by installing Git through Github.

**Comment by thomasjo** [comment]
Since this has been reported as resolved, I'm closing the issue.
