### ISSUE TITLE
Unable to unpublish atom-zeal

### ISSUE THREAD

**Issue by gliwka** [atom/apm#554]
Hi there,

i've discontinued a project i've created and already have deleted the github repository. Now, i'm not able to unpublish the atom package:

`➜  ~ apm unpublish atom-zeal
Are you sure you want to unpublish atom-zeal? (yes) 
Unpublishing atom-zeal ✗
Unpublishing failed: Unauthorized
➜  ~ 

I'm already logged into apm using apm login and pasting the token.

I've read in the discuss forum, that my best option to get this package deleted would be to create a issue here?

Best,
Matthias
`

**Comment by lee-dohm** [comment]
Deleted. Thank you for reporting!
