### ISSUE TITLE
Unpublishing failed: Unauthorized, I cannot unpublish my package

### ISSUE THREAD

**Issue by joshbuchea** [atom/apm#564]
Hi,

Apologies upfront for bothering anyone for my ignorance. In an attempt to unpublish and republish my package, I managed to delete the repo for my atom package [html-head-snippets](https://atom.io/packages/html-head-snippets), and subsequently lost access.

Could someone please unpublish this package for me? Thanks so much!

**Comment by thedaniel** [comment]
@joshbuchea - sorry, I don't work on this project anymore. cc @lee-dohm

**Comment by joshbuchea** [comment]
Ok thanks @thedaniel! Appreciate the quick reply and the reference to the new person to pester :smile:

**Comment by lee-dohm** [comment]
The package has been deleted.

**Comment by joshbuchea** [comment]
Awesome you're the man! Thanks @lee-dohm!
