### ISSUE TITLE
Several (incorrect?) assumptions about node path

### ISSUE THREAD

**Issue by gjtorikian** [atom/apm#568]
I'm looking at getting Atom running on ARM. I followed the build instructions in the README, but ran into two problems (which are actually the same problem):

* After cloning and building, I tried to run `bin/apm -v` to make sure things were working. I received an error message that said: `/home/gjtorikian/Development/apm/bin/node: No such file or directory`. I traced this back to [this line](https://github.com/atom/apm/blob/b25e8fee56a94e9a884307e87139e1322ca0d755/bin/apm#L35).
* Following the rest of the instructions, I ran `./bin/npm run build`. This crashed with a similar error [on this line](https://github.com/atom/apm/blob/b25e8fee56a94e9a884307e87139e1322ca0d755/script/check-version.js#L7).

So, in both cases, it looks like it's assuming a `node` binary to be in the `bin` folder. I don't see how that's possible with the current instructions or setup. Is this a documentation error or a configuration error? In any event, I was able to move forward by just changing both paths to use `node`, since it's already on my `PATH`.

**Comment by NoahVlncrt** [comment]
I'm trying to create this for myself and I ran into this issue how exactly did your code look if you don't mind me asking?
