### ISSUE TITLE
Missing path to `node-gyp`?

### ISSUE THREAD

**Issue by gjtorikian** [atom/apm#569]
Similar to https://github.com/atom/apm/issues/568, I had an issue with [the install script](https://github.com/atom/apm/blob/b25e8fee56a94e9a884307e87139e1322ca0d755/src/install.coffee#L29) looking for `node-gyp` in a path that didn't exist. `node-gyp` is not currently a dependency for this repo or `atom/atom`.

In the end, I did `npm install -g node-gyp`, and hardcoded the path to my installed `node-gyp` bin folder.

**Comment by gjtorikian** [comment]
This same issue was in the `dedupe` script, too, fwiw.

**Comment by BinaryMuse** [comment]
There's a postinstall script that should (1) download node and (2) run a dedupe so that node-gyp is moved from npm into the top-level node_modules folder. Is this working now that #568 has been resolved?

**Comment by gjtorikian** [comment]
Sorry this took so long for me to get to. Yes, this is working after #568!
