### ISSUE TITLE
Need help to republish `symbols-view-plus`

### ISSUE THREAD

**Issue by aidistan** [atom/apm#575]
I accidentally deleted the original repo of my package `symbols-view-plus` and have failed to publish any new version now. I have tried to:

- delete the tag, force push away the release commit, and try again => get "Git tag not found"
- push a later version => still get "Git tag not found"
- unpublish the package => get "Unauthorized"

Could anyone help me to delete the package manually? Thus I could republish it.

Thanks for the help!

---

Related issues are:
- Unpublishing fails with 'Unauthorized' when the package repository doesn't exist #221
- Unable to publish or unpublish packages #538
- Unable to unpublish linter-js-standard-tenx #541
- Unpublishing a package after deleting the Github repo? #582
- apm unpublish messes up versioning #598
- apm unpublish unauthorized #602
- apm unpublish unauthorized #603

**Comment by aidistan** [comment]
To whom it may concern,

the url of the repo: https://github.com/aidistan/atom-symbols-view-plus
the url of the package: https://atom.io/packages/symbols-view-plus

Hope this issue could be solved ASAP :pray:

**Comment by aidistan** [comment]
@lee-dohm Just want to remind you of this early issue, since I found you have replied a later similar issue.

**Comment by aidistan** [comment]
@BinaryMuse Any progress on this issue? I have made a list of similar issues in the first comment. Hope it would be helpful :smile:

**Comment by lee-dohm** [comment]
@aidistan Has this been resolved? It looks like everything is connected properly.

**Comment by aidistan** [comment]
@lee-dohm Nope. Still unable to unpublish:

```
Are you sure you want to unpublish symbols-view-plus? (yes) yes
Unpublishing symbols-view-plus ✗
Unpublishing failed: Unauthorized
```

**Comment by lee-dohm** [comment]
Should be fixed now. Let me know if it isn't!

**Comment by aidistan** [comment]
@lee-dohm Everything works fine now. Thank you so much.
