### ISSUE TITLE
Please unpublish loud-colors theme

### ISSUE THREAD

**Issue by h-a-n-n-e-s** [atom/apm#583]
I'm sorry for bothering anyone, but could you please unpublished my theme on
https://atom.io/themes/loud-colors-syntax

I erroneously removed the github repo
https://github.com/h-a-n-n-e-s/loud-colors-syntax
first and are now not able to do 'apm unpublished'
Wrong order, I know.

Thank you

**Comment by 50Wliu** [comment]
@lee-dohm

**Comment by Alhadis** [comment]
Just curious, what language is that in the theme's preview? =)

**Comment by h-a-n-n-e-s** [comment]
That's good old FORTRAN... but new :)
(actually following the 2008 standard)

**Comment by Alhadis** [comment]
Ah, thanks! =) I wanna learn that language some day.

**Comment by h-a-n-n-e-s** [comment]
@lee-dohm It was a fork from
https://github.com/atom/template-syntax
which didn't fully comply with Shadow DOM, so it created some unexpected behavior.
It should be unpublished permanently.
This
https://atom.io/themes/glaring-syntax
is a clean second try for a theme from scratch.

**Comment by lee-dohm** [comment]
Done. Thanks for the ping :grinning:
