### ISSUE TITLE
'Copy token' button not functioning atom.io/account in Firefox 

### ISSUE THREAD

**Issue by liuderchi** [atom/apm#584]
This is about official page styling/function.
This is posted here because of end of this [discussion](https://discuss.atom.io/t/is-atom-io-atoms-website-open-sourced/14197/9).

in [account page](atom.io/account), _Copy token_ button is not functioning in Firefox (v47.0) while working fine in Chrome.

1. button went black when mouse hovered
![hovered](https://cloud.githubusercontent.com/assets/4994705/16296855/b32238fc-3960-11e6-8318-4107714cc0e5.png)

2. token is not copied to copy to clipboard when clicked

**Comment by 50Wliu** [comment]
This issue was moved to atom/atom.io#78
