### ISSUE TITLE
Errors when installing other packages.

### ISSUE THREAD

**Issue by hoseong613** [atom/apm#588]
I've been having this problem for more than 2 weeks. 
Found out that pty.js had a dependency of nan which is not updated in the package. 
https://github.com/chjj/pty.js/pull/167 has a fix with the problem but it's not being updated. 
A forked updated package https://github.com/iiegor/ptyw.js. 
There's a lot of people having the same errors and issuing it on the package issues. 
@BinaryMuse

**Comment by lee-dohm** [comment]
I'm not sure any of this has to do with apm or Atom? If you let us know what is going wrong with apm, I'll be happy to re-open the Issue.
