### ISSUE TITLE
Don't reinstall when packages have been removed.

### ISSUE THREAD

**Issue by envygeeks** [atom/apm#589]
When I remove a package I expect it to stay removed and there to be an error thrown about a dependency being removed, however, when rebooting Atom, it asumes that packages should be reinstalled after I explicitly removed them.  With all the errors that atom currently throws when uninstalling packages, this makes it terribly hard to remove packages and keep a clean view of what's still installed.

**Comment by 50Wliu** [comment]
> an error thrown about a dependency being removed

Atom doesn't currently have any notion about packages depending on other packages.  What packages are you having this problem with?

**Comment by thomasjo** [comment]
I'm guessing this is caused by a community package, most likely via the npm package [`atom-package-dependencies`](https://www.npmjs.com/package/atom-package-dependencies). This is certainly not caused by Atom or apm (unless there's some wild, unknown 🐛 in play here).

**Comment by 50Wliu** [comment]
Closing until more information is provided.
