### ISSUE TITLE
Installation of certain packages fails due to a JSON syntax error that does not appear in the actual package's package.json.

### ISSUE THREAD

**Issue by Gum-Joe** [atom/apm#593]
When attempting to install certain packages, both within atom and via apm's cli, apm fails with error code `EJSONPARSE`. For example:
```
npm ERR! Windows_NT 6.2.9200
npm ERR! argv "C:\\Users\\Gum-Joe\\AppData\\Local\\atom\\app-1.8.0\\resources\\app\\apm\\bin\\node.exe" "C:\\Users\\Gum-Joe\\AppData\\Local\\atom\\app-1.8.0\\resources\\app\\apm\\node_modules\\npm\\bin\\npm-cli.js" "--globalconfig" "C:\\Users\\Gum-Joe\\.atom\\.apm\\.apmrc" "--userconfig" "C:\\Users\\Gum-Joe\\.atom\\.apmrc" "install" "C:\\Users\\KISHAN~1\\AppData\\Local\\Temp\\d-116617-8468-1hxqzxh\\package.tgz" "--target=0.36.8" "--arch=ia32" "--msvs_version=2013"
npm ERR! node v0.10.40
npm ERR! npm  v2.13.3
npm ERR! file C:\Users\Gum-Joe\.atom\.apm\wrappy\1.0.2\package\package.json
npm ERR! code EJSONPARSE

npm ERR! Failed to parse json
npm ERR! Unexpected token '\u0000' at 1:1
npm ERR! 
npm ERR! ^
npm ERR! File: C:\Users\Gum-Joe\.atom\.apm\wrappy\1.0.2\package\package.json
npm ERR! Failed to parse package.json data.
npm ERR! package.json must be actual JSON, not just JavaScript.
npm ERR! 
npm ERR! This is not a bug in npm.
npm ERR! Tell the package author to fix their package.json file. JSON.parse
```
This happens with multiple packages.  I think it may be linked with `CRLF` and `LF` line endings.

Before, I have had this issue with the version of `npm` that comes with nodejs (npm v3), which was fixed by cleaning the cache (`npm cache clean`). Any help in clearing apm's cache may help me fix this issue.

In addition, if I manually download the package's `package.json`, the `package.json` appears to have no syntax errors.

**Reproduction Steps:**

1. Load up a windows machine
2. Install a couple of random `apm` packages
3. Uninstall a couple of `apm` packages
4. Install a package such as `linter-bootlint` or `linter-htmllint` (there are also other packages that fail to install that do not start with `linter`.
5. The error message that is seen near the start of the issue should appear

**Expected behavior:**

Package should install successfully.

**Observed behavior:**

`apm` errors with the error code `EJSONPARSE`. It says it has found `\u0000` on line 1 of the package's `package.json`.

**Atom version:** `1.8.0`
**Apm version:** `1.9.2`
**OS:** Windows 10, version 1511 (November Update)

**Additional information:**

* Problem can be reproduced in safe mode: N/A, as this issue is both on the cli and within atom itself.
* Problem started happening recently, didn't happen in an older version of apm: Yes, but I have found this issue in npm v3, so I can't really say if it happens in an older version of apm.
* Problem can be reliably reproduced, doesn't happen randomly: Depends on the computer and (probably) the amount of cache stored.
* Problem happens with all files and projects, not only some files or projects: Yes

**Comment by thomasjo** [comment]
If you look closely at the error, the problem stems from within `.atom/.apm/`, in specific the npm package `wrappy`. I'm guessing something has gotten corrupted in your environment. Unless you have, for whatever reason, been running various `npm` functions within the `.atom` tree, this is unrelated to npm versions since apm comes bundles with its own isolated node and npm. Just run `apm --version` and you'll see this.

``` sh
$ apm --version
apm  1.10.0
npm  2.13.3
node 0.10.40
python 2.7.12
git 2.9.2
```

`\u0000` is the `NULL` character, and the fact it's present on line 1, column 1 (`1:1`) indicates something has become corrupt in your environment. You should be able to safely delete the `.apm` folder since it's just (IIRC) a module cache, then try `apm install <whatever package>` again.

**Comment by Gum-Joe** [comment]
Thanks @thomasjo. Package now installs!
