### ISSUE TITLE
Node version out-of-date

### ISSUE THREAD

**Issue by Sorunome** [atom/apm#599]
It seems like the version of node which is packaged in apm is out-of-date, which leads pro problems including some node modules, such as here: https://github.com/EmergingTechnologyAdvisors/node-serialport/issues/880

**Comment by thomasjo** [comment]
The next release of Atom will be bundled with a new release of apm that is currently using [Node.js v4.4.5](https://github.com/atom/apm/blob/cea5ef8497a788d7d6949b2632bdc74ddd6c1f9e/BUNDLED_NODE_VERSION).
