### ISSUE TITLE
Duplicate package after renaming

### ISSUE THREAD

**Issue by idleberg** [atom/apm#600]
I have recently renamed my Inno Setup package from `language-inno` to `language-innosetup`. The renaming itself, as well as the redirection of the package page worked fine. However, after updating my package locally, I now have two instances of the package installed, one under the old name `language-inno` and another one under the new name `language-innosetup`. Since the files of the old package remain unchanged, the package will continue to request updates.

On my personal computer, I simply deleted the old package, but since I received a [first issue](https://github.com/idleberg/atom-language-innosetup/issues/1#issuecomment-238435874), I wanted to post it here (where it belongs!)
## Steps to Reproduce
- Clone repository, checkout to a tag before package was renamed:

``` bash
cd ~/.atom/packages
git clone https://github.com/idleberg/atom-language-innosetup language-inno
cd language-inno
git checkout tags/v2.1.6
```
- Launch Atom
- Update packages
- Browse to packages directory

**Expected behavior**: [What you expected to happen]

`language-inno` should have been removed

**Actual behavior**: [What actually happened]

Package directory contains two versions of the package: `language-inno` (old) and `language-innosetup` new
## Versions

apm  1.10.0
npm  2.13.3
node 0.10.40
python 2.7.10
git 2.7.4

Atom    : 1.9.6
Electron: 0.37.8
Chrome  : 49.0.2623.75
Node    : 5.10.0

**Comment by 50Wliu** [comment]
Should be fixed by #747.
