### ISSUE TITLE
apm unpublish unauthorized

### ISSUE THREAD

**Issue by pcnate** [atom/apm#602]
I am unable to unpublish my apm package. I ended up screwing up the versioning, deleting the releases in github screwed with the release versions of apm. I was unable to fix anything so I deleted the repo on github and republished. It was not until afterwards that I tried to remove the apm package which now fails.

Could someone please remove the package in the database?
https://atom.io/packages/open-in-openscad

It would be great if we had some sort of web interface to do this sort of thing. Or to fix minor release information.

**Comment by pcnate** [comment]
Any way to get this done?

**Comment by lee-dohm** [comment]
Do you want the package unpublished because you want it gone? Or because you want to republish it under the same name?

**Comment by pcnate** [comment]
I want to republish it but apm does not will not let me.

**Comment by pathtrk** [comment]
Hi,

I deleted my github repo in advance of unpublishing my atom package by mistake. Now I can't unpublish it by an unauthorized error nor publish by missing git tags.

I'd like to publish my syntax theme with the same name again.

Could someone let me know how I resolve this error?

**Comment by jasonrudolph** [comment]
> I want to republish it but apm does not will not let me.

This was a bug in apm's backend API. I think we've got it resolved now. 🤞

@pcnate: Can you please try unpublishing? If you've already run `apm login`, then this command should do the trick:

    apm unpublish open-in-openscad

Once you've unpublished, you should be able to republish the package using your new repo.

If you still run into trouble, please let us know.
