### ISSUE TITLE
apm unpublish unauthorized

### ISSUE THREAD

**Issue by lanzhiheng** [atom/apm#603]
I am unable to unpublish my apm package. I remove my github repo before unpublish it from atom.io。

Could someone please remove the package in the database?

https://atom.io/packages/my-package-words-count

thank you very mush 😢

**Comment by 50Wliu** [comment]
@lee-dohm

**Comment by lee-dohm** [comment]
Do you want it deleted because you want it gone? Or do you want to republish it under the same name?

**Comment by lanzhiheng** [comment]
@lee-dohm I want to delete it 😢  Thx

**Comment by jasonrudolph** [comment]
This was a bug in apm's backend API. I think we've got it resolved now. 🤞

@lanzhiheng: If you still want to unpublish the package, can you please try unpublishing again? If you've already run `apm login`, then this command should do the trick:

    apm unpublish my-package-words-count

If you still run into trouble unpublishing, please let us know.
