### ISSUE TITLE
apm install reinstalls existing packages

### ISSUE THREAD

**Issue by vrinek** [atom/apm#604]
I'm using the following procedure to "sync" a couple of machines:

- `apm list --installed --bare > my-packages.txt`
- `apm install --packages-file my-packages.txt`

Sadly, the second command reinstalls everything, which is slow. I don't see a flag in the documentation that would instruct `apm install` to skip already installed packages.

Am I missing something or is this indeed a bug-report?

**Comment by 50Wliu** [comment]
Closing as a duplicate of #170 - feel free to subscribe there for updates.

**Comment by vrinek** [comment]
Cool, thanks for the heads up!
