### ISSUE TITLE
Rebuilding module cache fails since apm v1.12.5

### ISSUE THREAD

**Issue by dm-blue** [atom/apm#605]
Hello,

I'm using a custom theme, generated from a Textmate theme resource file (.tmTheme), using command:
  apm init --theme ~/.atom/packages/Custom-theme --convert Custom.tmTheme
which still works fine.

But starting with atom 1.10.0 (apm 1.12.5), the command:
  apm rebuild-module-cache
fails with:

Rebuilding Custom-theme module cache ✗
Cannot read property 'link' of undefined

and it breaks here.

**Comment by watilde** [comment]
I just tried with [GitHub.tmTheme](https://raw.githubusercontent.com/filmgirl/TextMate-Themes/master/GitHub.tmTheme), and it worked well. Could you give us your `Custom.tmTheme`?

**Comment by dm-blue** [comment]
Actually, after further investigation, 'apm rebuild-module-cache' is not working with any other module, anymore. Accidentally, the Custom.tmTheme was the first module. If removed, the next module fails with the same error.
The last atom version where this command worked fine was 1.9.8 (with apm 1.10.0).
I'm compiling the atom each time on a Centos 6 Workstation linux platform, with nodejs 6.9.4. Last test was with atom 1.14.0-beta0 (apm 1.15.1). Except this command, everything works fine.

**Comment by noe132** [comment]
I encounter the same problem with apm rebuild-module-cache.

Rebuilding atom-beautify module cache failed
Cannot read property 'link' of undefined

using window 10 x64 atom 1.15

seems like dependencies of every package was independent, the atom folder is very large

**Comment by seanbuscay** [comment]
I have this same issue. Using OSX, and atom 1.16

List after running `apm -v`

npm  3.10.5
node 6.9.5 x64
python 2.7.13
git 2.10.2

**Comment by dm-blue** [comment]
It seems to be fixed with apm 1.18.2 (atom 1.18.x)

**Comment by dmig** [comment]
Still seeing this:
```sh
$ apm-beta -v
apm  1.19.0
npm  3.10.10
node 6.9.5 x64
atom 1.25.0-beta3
python 2.7.14
git 2.14.1
$ apm-beta rebuild-module-cache
Rebuilding Stylus module cache ✗
Cannot read property 'link' of undefined
```

**Comment by fbbdev** [comment]
I started seeing this error with all packages on atom 1.25.0, apm 1.19.0
```sh
$ apm -v 
apm  1.19.0
npm  3.10.10
node 6.9.5 x64
atom 1.25.0
python 2.7.14
git 2.16.2
```

**Comment by kenficara** [comment]
Having the same problem with 1.29.

```
$ apm --version
apm  1.19.0
npm  3.10.10
node 6.9.5 x64
atom 1.29.0
python 2.7.10
git 2.18.0
```

**Comment by JerrySievert** [comment]
having the same problem with `2.1.3`.

started removing packages to fix it, and after a while ran into packages I rely on.

**Comment by hkockerbeck** [comment]
I've got the same problem with Atom 1.54.0, apm 2.5.2 on Ubuntu 20.04. I actually removed the whole `~/.atom` folder and started over from scratch. Once I install the first package (I've tried emmet, hydrogen, atom-beautify and others), I get
```
$ apm rebuild-module-cache
Rebuilding atom-beautify module cache ✗
Cannot read property 'link' of undefined
```
```
$ apm --version
apm  2.5.2
npm  6.14.8
node 12.4.0 x64
atom 1.54.0
python 2.7.18
git 2.30.0
```
