### ISSUE TITLE
unpublishing unauthorized.

### ISSUE THREAD

**Issue by facelesspanda** [atom/apm#609]
Hi. I want to unpublish https://atom.io/packages/giant-comment-headers.

I had forked https://github.com/masavini/atom-minimap-titles and added a feature, but my Pull Request has merged today so I wanted to unpublish my now obsolete package.

Couldn't find any info about how to do it so I just ended up deleting the github repo, and now I can't unpublish it (I found actual info about unpublishing packages since then)

I've read I had to file an issue here?

I should note I want the package gone, not renamed or whatever, because it is a redundancy of masavini's much more popular package.

**Comment by entozoon** [comment]
Same issue: https://github.com/atom/apm/issues/612

**Comment by lee-dohm** [comment]
Deleted.
