### ISSUE TITLE
Hard to contribute to apm develop'd repos 

### ISSUE THREAD

**Issue by benogle** [atom/apm#61]
What's the story for actually contributing to a 3rd party package installed via `apm develop`? It just clones from the repo url, but doesn't make a fork. This works for us, but not those without commit bit. Could it fork and clone?

We should at least have some docs on how we think they should do it (fork, then change the origin after apm develop?)

http://discuss.atom.io/t/submitting-a-pull-request/2306

**Comment by damieng** [comment]
apm link now works on Windows.

I'd recommend the following process for using apm dev;

1. `apm dev packagename`
2. Do your work, commit locally to a branch

So far, so easy and no new steps. Now if you want to contribute back to the package;

1. Fork the original repo on github.com
2. `git remote set-url origin <your-fork-url>`
3. `git push`
4. Create PR on github.com
