### ISSUE TITLE
apm unpublish assistance

### ISSUE THREAD

**Issue by entozoon** [atom/apm#612]
Having the same issue a lot of people are having whereby I can't unpublish / publish to my own package.
What I did was (briefly):

```
create package and git push
apm publish minor
delete my git repo in a fit of rage
recreate git repo with same name
apm publish minor
- Git tag not found
apm unpublish
- Unauthorized
```

So my package is dead - can't update or remove it, pretty embarrassing.

I (now) understand the packages are inextricably linked to the original repo for whatever reason but can someone help me .. extrict it? 
extricate*

Thanks in advance

**Comment by 50Wliu** [comment]
@lee-dohm

**Comment by entozoon** [comment]
Any update on this?
It seems to me that atom packages should automatically unpublish if their parent github repo is deleted, if they are indeed so permanently linked

**Comment by entozoon** [comment]
Any update on this?
It seems to me that atom packages should automatically unpublish if their parent github repo is deleted, if they are indeed so permanently linked

**Comment by lee-dohm** [comment]
@entozoon What is the name of your package?

**Comment by entozoon** [comment]
Hi there @lee-dohm, thanks for the reply. It's:
https://atom.io/packages/lorem-gibson

**Comment by entozoon** [comment]
Is there anything I can do here @lee-dohm / @50Wliu ?
The package is dead in the water and needs whippin' out.

**Comment by lee-dohm** [comment]
It's been deleted. You are free to republish it :+1:

**Comment by entozoon** [comment]
You're my hero @lee-dohm! Very much appreciated, I know how busy you are :)
