### ISSUE TITLE
apm unpublish failed!

### ISSUE THREAD

**Issue by Rawnly** [atom/apm#613]
Hello i need to remove 2 packages from my account, but the command line fail 
`$ apm unpublish simple-toolbar`
`Are you sure you want to unpublish ALL VERSIONS of 'simple-toolbar'? This will remove it from the apm registry, including download counts and stars, and this action is irreversible. (no) yes`
`Unpublishing simple-toolbar ✗`
`Unpublishing failed: Unauthorized`
The package is [this](https://atom.io/packages/simple-toolbar)

Can you remve it? else can you remove [this one](https://atom.io/packages/tool-bar-rawn).

Thanks in advance

**Comment by 50Wliu** [comment]
@lee-dohm

**Comment by 50Wliu** [comment]
This was a bug in apm's backend API. We think we've got it resolved now. 🤞

@Rawnly: If you still want to unpublish the packages, can you please try unpublishing again? If you've already run `apm login`, then this command should do the trick:

    apm unpublish simple-toolbar
    apm unpublish tool-bar-rawn

If you still run into trouble unpublishing, please let us know.
