### ISSUE TITLE
Package search doesn't work

### ISSUE THREAD

**Issue by tiborsaas** [atom/apm#618]
Hello,

Is this normal? :) I'd assume I enter a keyword here and see a list of packages. 

![image](https://cloud.githubusercontent.com/assets/342688/19417718/3a27c350-93b4-11e6-9748-c3f382cce0a9.png)

I'm on Windows 10

**Comment by Ben3eeE** [comment]
This is a duplicate of https://github.com/atom/atom/issues/12999.
