### ISSUE TITLE
`apm list` always shows `(empty)` in its output

### ISSUE THREAD

**Issue by bronson** [atom/apm#621]
Very strange.  Appears related to https://github.com/atom/apm/commit/c66de27adf0117b140aeb4d4ea3e8ff7fef7faac

```
├── vim-mode-plus@0.60.1
├── vim-mode-plus-ex-mode@0.5.0
└── white-cursor@0.6.0

└── (empty)
```

**Comment by 50Wliu** [comment]
Do you mean `apm list`?

**Comment by bronson** [comment]
I did, edited to fix.   Darn fingers.  :)
