### ISSUE TITLE
Concerned about CI

### ISSUE THREAD

**Issue by bronson** [atom/apm#625]
It appears that TravisCI hasn't successfully built apm since 1.12.4, 3 months ago.

And, while Appveyor is currently showing green, it doesn't seem like it's actually running any tests.  There's no test output in the logs, anyway.

Is CI still being used?

**Comment by 50Wliu** [comment]
Yes, this is definitely a problem that should be fixed.

As for Appveyor, I have a hunch that tests have never passed on Windows in the first place which is why they're not run yet.

**Comment by bronson** [comment]
That makes sense.  It seems a little premature to put Appveyor in the README then!

Think it's worth submitting a PR to remove it temporarily?  I found it confusing.  And I'd look forward to replacing it once it works.

**Comment by bronson** [comment]
Or maybe a better solution would be to put a `fail "need to finish Appveyor integration"` at the bottom of the build script.  Happy to submit that too.

**Comment by 50Wliu** [comment]
What we do for other packages now is let Appveyor run the tests, even if they fail, so that the red "x" eventually makes you annoyed enough that you go in and fix the broken specs.  See tree-view as an example.

**Comment by bronson** [comment]
Sounds good.  So, maybe it's as easy as just deleting these two lines?

https://github.com/atom/apm/blob/master/appveyor.yml#L15-L17

**Comment by thomasjo** [comment]
@bronson That won't work. Those flags are for .NET/msbuild. We simply need to invoke [`npm test`](https://github.com/atom/apm/blob/6b553d31c08068a6b4bbd1efa10ff65c86a72af4/.travis.yml#L13).

**Comment by bronson** [comment]
Closing...  I think we're all used to seeing breakage in Atom's CI now.  :)
