### ISSUE TITLE
apm is available in Atom's Install Packages screen

### ISSUE THREAD

**Issue by bronson** [atom/apm#627]
I don't know what's stranger, that Atom is offering to install apm...

<img width="1172" alt="screen shot 2016-10-19 at 1 40 24 pm" src="https://cloud.githubusercontent.com/assets/1776/19536647/af6309dc-9601-11e6-9d74-75dfc95ee21b.png">

... or that appears stuck at 1.9.3.  :)

Anyone know what's going on here?  It appears 1700 people have installed it.

**Comment by iolsen** [comment]
This started when somebody inadvertently published apm as an apm package (rather than an npm package). We left it there to keep the name claimed. Ideally we'd blacklist this within apm so it doesn't appear here or in the CLI.

**Comment by jasonrudolph** [comment]
> This started when somebody inadvertently published apm as an apm package (rather than an npm package). We left it there to keep the name claimed. Ideally we'd blacklist this within apm or the atom.io backend so it doesn't appear here or in the CLI.

We've blacklisted the package and unpublished it. Atom should no longer offer to install it, and it should no longer appear in any search results.

Thanks for reporting this, @bronson. :bow:
