### ISSUE TITLE
Failed to publish (after unpublish)

### ISSUE THREAD

**Issue by Pedromdrp** [atom/apm#630]
I unpublished my package in order to transfer the repository.
I then proceed to publish it again and it is failing with the following error:

```
$ apm publish language-caper
Preparing and tagging a new version failed
npm ERR! npm version [<newversion> | major | minor | patch | premajor | preminor | prepatch | prerelease | from-git]
npm ERR! (run in package dir)
npm ERR! 'npm -v' or 'npm --version' to print npm version (3.10.5)
npm ERR! 'npm view <pkg> version' to view a package's published version
npm ERR! 'npm ls' to inspect current package/dependency versions
```

Any ideas what is the problem?
Thanks.

**Comment by 50Wliu** [comment]
You need to specify one of `major | minor | patch` instead of the package name (which is already contained within `package.json`).  For example, `apm publish minor`.

**Comment by Pedromdrp** [comment]
That solved it!
