### ISSUE TITLE
apm unpublish unauthorized

### ISSUE THREAD

**Issue by pathtrk** [atom/apm#632]
I mistakenly deleted my github repo before I unpublish its apm package. Now I can't publish or unpublish with 'unauthorized' errors. 

The package I published is : https://atom.io/packages/ariake-syntax

I need to delete this package because I intended to publish it as theme.

I'm really sorry about my ignorance. 
Thanks,

**Comment by 50Wliu** [comment]
This was a bug in apm's backend API. We think we've got it resolved now. 🤞

@pathtrk: If you still want to unpublish the package, can you please try unpublishing again? If you've already run `apm login`, then this command should do the trick:

    apm unpublish ariake-syntax

If you still run into trouble unpublishing, please let us know.

**Comment by pathtrk** [comment]
@50Wliu It resolved! I successfully unpublished the package.  Thanks for your help!
