### ISSUE TITLE
Please unpublish `faketerm` from the Atom package repository

### ISSUE THREAD

**Issue by Fred-Barclay** [atom/apm#634]
(Apologies if this is in the wrong place. My understanding after reading [this](https://discuss.atom.io/t/cannot-unpublish-package-once-github-repository-deleted/18580) is that this is the place to ask.)

I had published the `faketerm` package as a "dummy" package for me to practice and test code with, and after I finished I made the mistake of deleting the associated Github repository before unpublishing faketerm with `apm`. Would it be possible for someone here to unpublish the package for me? 

Cheers!
Fred

**Comment by 50Wliu** [comment]
This was a bug in apm's backend API. We think we've got it resolved now. 🤞

@Fred-Barclay: If you still want to unpublish the package, can you please try unpublishing again? If you've already run `apm login`, then this command should do the trick:

    apm unpublish faketerm

If you still run into trouble unpublishing, please let us know.

**Comment by Fred-Barclay** [comment]
Hi @50Wliu 
It's unpublished now. Thanks! :+1:
