### ISSUE TITLE
CRASH: Meld was unexpected at this time

### ISSUE THREAD

**Issue by sbrl** [atom/apm#642]
I was attempting to install mrodalgaard/atom-todo-show again in order to provide more information about mrodalgaard/atom-todo-show#137, but apm decided to output this:

```
\Meld"" was unexpected at this time.
```

Now it won't install anything. How can go about debugging this?

**Comment by Ben3eeE** [comment]
This happens if your PATH environment variables contains a " around any of the entries.  Windows normally uses " around paths with spaces but it should not be like this in PATH.

This is fixed in the latest version of apm. In the meantime you can edit your PATH variable and remove the quotes.

**Comment by sbrl** [comment]
@Ben3eeE Ah right! Thanks for the help.

When will the next version of apm be released please? Although I've identified that `"C:\Program Files (x86)\Meld"` is the culprit, in the `PATH` environment editor it doesn't show the quotes, so I can't remove them 😕

**Comment by sbrl** [comment]
Never mind, I've figured it out. You have to go to "Edit Text" change it from there.
