### ISSUE TITLE
Request to `unpublish` ui theme

### ISSUE THREAD

**Issue by cdonohue** [atom/apm#644]
I apologize for asking, but is there any way that a team member could `unpublish` my ui-theme:
> https://atom.io/themes/clean-ui

I severed the fork by deleting the repo without knowing that would damage the relationship with `apm`. I have published the theme under a new name now, and just need `clean-ui` removed.

Thank you

**Comment by cdonohue** [comment]
Any idea on when this can be looked at?

**Comment by lee-dohm** [comment]
Deleted :grinning:

**Comment by cdonohue** [comment]
Thanks @lee-dohm
