### ISSUE TITLE
apm unpublish unauthorized

### ISSUE THREAD

**Issue by Kemichal** [atom/apm#649]
I have removed the github repo, please remove the package https://atom.io/packages/language-eloquence

**Comment by entozoon** [comment]
Hope you're sitting comfortably @Kemichal, it could take a good while:
https://github.com/atom/apm/issues?q=is%3Aissue+is%3Aopen+label%3Apackage-maintenance

The unpublish issue has been around for at least two years now :S

**Comment by Kemichal** [comment]
@entozoon yea, I saw that :(
A delete button on the Atom site would be nice in cases like this.

**Comment by Kemichal** [comment]
@lee-dohm @Ben3eeE

Have I not waited long enough now?

**Comment by lee-dohm** [comment]
This was a bug in apm's backend API. I think we've got it resolved now. 🤞

@Kemichal: If you still want to unpublish the package, can you please try unpublishing again? If you've already run `apm login`, then this command should do the trick:

    apm unpublish language-eloquence

If you still run into trouble unpublishing, please let us know.
