### ISSUE TITLE
Can't unpublish my package

### ISSUE THREAD

**Issue by yassh** [atom/apm#655]
I have deleted the GitHub repository of [Copy With Line Numbers](https://atom.io/packages/copy-with-line-numbers), so I can not unpublish it.
Would you please unpublish it manually?

Thank you

**Comment by yassh** [comment]
I noticed that the package has been deleted.
But I can not republish it...

```
% apm publish minor
Registering copy-with-line-numbers ✓
Preparing and tagging a new version ✓
Pushing v0.1.0 tag ✓
Publishing copy-with-line-numbers@v0.1.0 ✗
Creating new version failed: Not found
```

**Comment by yassh** [comment]
Could you help me? @lee-dohm

**Comment by lee-dohm** [comment]
@yassh Sometime between when you posted this and now, it has been deleted. I guess I (or whomever did it) forgot to update and close the issue :blush: My apologies!

**Comment by yassh** [comment]
Thanks a lot!

I could not republish it, so I changed package name from "copy-with-line-numbers" to "atom-copy-with-line-numbers" and publish [it](https://atom.io/packages/atom-copy-with-line-numbers).
