### ISSUE TITLE
APM fails on Windows when the user's path contains special characters

### ISSUE THREAD

**Issue by DamnedScholar** [atom/apm#659]
[A user over on the forums](https://discuss.atom.io/t/atom-wont-install-packages-to-my-oddly-named-user-directory) is having difficulty installing packages because their user folder is named `C:\Users\R&M`. They're receiving the error message "'C:\Users\R' is not recognized as an internal or external command, operable program or batch file." I have not created a new user folder to test this, but a similar test, such as `cd C:\R&M` shows that the ampersand is indeed read as a special character unless the path is wrapped in quotes: `cd "C:\R&M"`. This should be an easy enough fix.

**Comment by 50Wliu** [comment]
https://github.com/atom/atom/commit/01de6855f182d0e6dd83e00b8b116736b1a15e9f
