### ISSUE TITLE
Can't unpublish atom-mapfile

### ISSUE THREAD

**Issue by geofreak** [atom/apm#663]
I can't unpublish my package:

apm unpublish atom-mapfile

Are you sure you want to unpublish ALL VERSIONS of 'atom-mapfile'? This will remove it from the apm registry, including download counts and stars,
and this action is irreversible. (no)yes

Unpublishing atom-mapfile failed
Unpublishing failed: Unauthorized

**Comment by 50Wliu** [comment]
This was a bug in apm's backend API. We think we've got it resolved now. 🤞

@geofreak: If you still want to unpublish the package, can you please try unpublishing again? If you've already run `apm login`, then this command should do the trick:

    apm unpublish atom-mapfile

If you still run into trouble unpublishing, please let us know.

**Comment by geofreak** [comment]
@50Wliu
I tried it again, it works :-)

Thanks.
