### ISSUE TITLE
APM fails on Windows when Atom location contains space character

### ISSUE THREAD

**Issue by afrz** [atom/apm#666]
Hello !

### Prerequisites

* [ ]  Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
* [ ] Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
* [x] Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
* [x] Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
* [x] Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description
Installation/update failure of atom-beautify 0.29.16 on Windows 7 x64.

### Steps to Reproduce

1. Try to install 0.29.16 (through Atom GUI or apm CLI)
2. Installing “atom-beautify@0.29.16” failed.

**Expected behavior:**

Installation ends successfully

**Actual behavior:**

Installation fails with following [DEBUG output](https://gist.github.com/afrz/046daf8f44f10d53d3bbd30d052cde04) (see gist for full log)

> 'D:\Program' n'est pas reconnu en tant que commande interne

 or in English :

>  'D:\Program' is not recognized as an internal or external command, operable program or batch file.

**Reproduces how often:**

100%

### Versions

Windows 7 (64 bits)
```
atom --version
  Atom    : 1.12.7
  Electron: 1.3.13
  Chrome  : 52.0.2743.82
  Node    : 6.5.0

apm --version
  apm  1.12.9
  npm  3.10.5
  node 4.4.5
  python 2.7.11
  git 2.6.1.windows.1
  visual studio 2013
```

### Additional Information

It seems that script build-options can not find a file located in 'Program Files' directory (which contains a space character).
For information Atom is installed in **D:\Program Files\Atom\atom** directory.

I notice that issue [APM fails on Windows when the user's path contains special characters](https://github.com/atom/apm/issues/659) is fixed, but I do not know if it's the same problem (because user path vs. atom path)

**Comment by damieng** [comment]
I just tried this with a bunch of packages and didn't get any errors except on atom-beautify.

In fact all paths contain a space now on x64 Windows which I've been using for weeks.  

I suspect this is an issue with atom-beautify especially given that it gets a lot of the way through and errors at;

```
> atom-beautify@0.29.16 postinstall f:\Temp\apm-install-dir-11703-8944-1kieqc0\node_modules\atom-beautify
> npm run build-options

'C:\Users\damien' is not recognized as an internal or external command,
operable program or batch file.
f:\Temp\apm-install-dir-11703-8944-1kieqc0
`-- (empty)
```

**Comment by Glavin001** [comment]
The problem is there is nothing Atom-Beautify can do to change it. All Atom-Beautify has is `npm run build-options` are a `postinstall` script within `package.json`, which is all fairly standard stuff. Then `npm` is translated into the absolute path -- which has the space -- and things start breaking.

Eventually Atom-Beautify will be removing the `postinstall` script, however, until that time this is something Atom-Beautify should be allowed to do without issue.

**Comment by damieng** [comment]
You're right -it's us getting in the way of the post-install scripts. Found, tested and fixed!

**Comment by damieng** [comment]
![image](https://cloud.githubusercontent.com/assets/118951/21630667/473eb072-d1e8-11e6-9eca-4973dd6da38f.png)

**Comment by Glavin001** [comment]
Wow, that was a quick fix. Awesome work!!! 🎆

**Comment by afrz** [comment]
Great news. Thanks you for your quick support.  :+1: 

You killed the [beast](https://en.wikipedia.org/wiki/Number_of_the_Beast) !  :wink:

**Comment by Glavin001** [comment]
Is this released yet? How can users receive this fix? 

/cc @RockWolfHD

**Comment by pingshunhuangalex** [comment]
Hi @damieng 

Just wonder when this fix will be pushed? I noticed it has a version no. of 1.15.2 which is really far away from the current 1.13.0 version. Thanks.

**Comment by damieng** [comment]
It should ship in the next 1.14 beta. No ETA on that right now.

**Comment by afrz** [comment]
For info, Atom version 1.14.1 fixed the problem for me. Thanks again.
