### ISSUE TITLE
Cannot unpublish my "threshold-ui" package

### ISSUE THREAD

**Issue by binaryfunt** [atom/apm#668]
Can you please unpublish [threshold-ui](https://atom.io/packages/threshold-ui) for me? I can't get it to publish from the [github repo](https://github.com/binaryfunt/threshold-ui) and I can't unpublish it myself:

    Are you sure you want to unpublish ALL VERSIONS of 'threshold-ui'? This will remove it from the apm registry, including download counts and stars, and this action is irreversible. (no)Y
    Unpublishing threshold-ui failed
    Unpublishing failed: Unauthorized

I came from [this post](https://discuss.atom.io/t/cant-publish-unpublish-package/21270/2) on the Atom Discuss site.

**Comment by 50Wliu** [comment]
This was a bug in apm's backend API. We think we've got it resolved now. 🤞

@binaryfunt: If you still want to unpublish the theme, can you please try unpublishing again? If you've already run `apm login`, then this command should do the trick:

    apm unpublish threshold-ui

If you still run into trouble unpublishing, please let us know.
