### ISSUE TITLE
Failed to Install atom beautify, the developers of this package told me it's a bug in apm

### ISSUE THREAD

**Issue by Guy-Markman** [atom/apm#669]
### Prerequisites

* [X ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description
I created a issue ([this one](https://github.com/Glavin001/atom-beautify/issues/1445)), about when I install atom-beautify I get the errors. Only atom-beautify. The developers of this package told me this is apm error and closed the issue
### Steps to Reproduce

1. Open cmd on windows 8 64 bits
2. wrote apm intall atom-beautify

**Expected behavior:** [What you expect to happen]
Installing atom-clock to C:\Users\Guy and Noam\.atom\packages done
**Actual behavior:** [What actually happens]
Installing atom-beautify to C:\Users\Guy and Noam\.atom\packages failed

> atom-beautify@0.29.16 postinstall C:\Users\GUYAND~1\AppData\Local\Temp\apm-ins
tall-dir-11706-8696-1v8o5wy\node_modules\atom-beautify
> npm run build-options

C:\Users\GUYAND~1\AppData\Local\Temp\apm-install-dir-11706-8696-1v8o5wy
`-- (empty)

npm WARN deprecated node-uuid@1.4.7: use uuid module instead
npm WARN deprecated minimatch@0.2.12: Please update to minimatch 3.0.2 or higher
 to avoid a RegExp DoS issue
npm WARN deprecated node-uuid@1.4.0: use uuid module instead
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher
 to avoid a RegExp DoS issue
'C:\Users\Guy' is not recognized as an internal or external command,
operable program or batch file.
npm WARN enoent ENOENT: no such file or directory, open 'C:\Users\GUYAND~1\AppDa
ta\Local\Temp\apm-install-dir-11706-8696-1v8o5wy\package.json'
npm WARN apm-install-dir-11706-8696-1v8o5wy No description
npm WARN apm-install-dir-11706-8696-1v8o5wy No repository field.
npm WARN apm-install-dir-11706-8696-1v8o5wy No README data
npm WARN apm-install-dir-11706-8696-1v8o5wy No license field.
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Users\\Guy and Noam\\AppData\\Local\\atom\\app-1.12.9\\resour
ces\\app\\apm\\bin\\node.exe" "C:\\Users\\Guy and Noam\\AppData\\Local\\atom\\ap
p-1.12.9\\resources\\app\\apm\\node_modules\\npm\\bin\\npm-cli.js" "--globalconf
ig" "C:\\Users\\Guy and Noam\\.atom\\.apm\\.apmrc" "--userconfig" "C:\\Users\\Gu
y and Noam\\.atom\\.apmrc" "install" "C:\\Users\\GUYAND~1\\AppData\\Local\\Temp\
\d-11706-8696-5dkwst\\package.tgz" "--runtime=electron" "--target=1.3.13" "--arc
h=ia32" "--global-style"
npm ERR! node v4.4.5
npm ERR! npm  v3.10.5
npm ERR! code ELIFECYCLE

npm ERR! atom-beautify@0.29.16 postinstall: `npm run build-options`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the atom-beautify@0.29.16 postinstall script 'npm run build-o
ptions'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the atom-beautify package
,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run build-options
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs atom-beautify
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls atom-beautify
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\GUYAND~1\AppData\Local\Temp\apm-install-dir-11706-8696-1v8
o5wy\npm-debug.log
npm ERR! code 1

**Reproduces how often:** [What percentage of the time does it reproduce?]
Everytime I try to install it, and only atom-beautify

### Versions

You can get this information from copy and pasting the output of `atom --version` and `apm --version` from the command line. Also, please include the OS and what version of the OS you're running.

windows 8 64 bits

atom --version 
Atom    : 1.12.9
Electron: 1.3.13
Chrome  : 52.0.2743.82
Node    : 6.5.0

apm --version
apm  1.12.9
npm  3.10.5
node 4.4.5
python 2.7.12
git 2.10.2.windows.1
visual studio
### Additional Information
The user name on my computer is "Guy and Noam" (without the quote marks) but on the file it show it as GUYAND~1, also the file apm-install-dir-11706-8696-1v8o5wy\npm-debug.log does not exist on my machine

**Comment by 50Wliu** [comment]
This has been fixed in e8b28ce31dc55890ca978ebe889a3de945d7cd99 and will be available in future Atom versions.

**Comment by TheGreatJo** [comment]
Had this problem with several plugins.
For me I solved it with starting cmd as administrator.

For atom-beautify didn't solved it but I get a different error than you:

`Request for package information failed: getaddrinfo ENOTFOUND atom.io atom.io:44
3 (ENOTFOUND)`
