### ISSUE TITLE
apm unpublish unauthorized

### ISSUE THREAD

**Issue by Esaud17** [atom/apm#671]
I have removed the github repo, please remove the package
https://atom.io/packages/atom-tron-legacy

I have tried to delete but it does not authorize and a message on screen says this

Unpublishing atom-tron-legacy failed
Unpublishing failed: Unauthorized

Can you help me please  ? @lee-dohm

**Comment by lee-dohm** [comment]
Thanks for letting us know. I've deleted the package 👍
