### ISSUE TITLE
unpublish package ( I broke the links and apm unpublish won't work)

### ISSUE THREAD

**Issue by Or3stis** [atom/apm#679]
I wanted to unpublish a theme I made, but I didn't read the documentation first and now everything is messed up 😔.

My theme is <https://atom.io/themes/firefox-dev-dark-syntax>

My steps were:
1.  Delet github repository.
1.  Tried to `apm unpublish` got `Unpublishing failed: Unauthorized`.
1.  Recreated the github repository.
1.  Tried to `apm unpublish` got `Unpublishing failed: Unauthorized`.
1.  Tried to publish a new version `apm publish patch` got `Creating new version failed: Git tag not found`
1. Fought with the git tags.
1. Submitted issue.

I would appreciate if you could remove it. My theme is not relevant anymore. Firefox changed their developer tools color theme and there is a much better package in atom than mine that supports the new color themes and the old ones.

**Comment by 50Wliu** [comment]
This was a bug in apm's backend API. We think we've got it resolved now. 🤞

@Or3stis: If you still want to unpublish the theme, can you please try unpublishing again? If you've already run `apm login`, then this command should do the trick:

    apm unpublish firefox-dev-dark-syntax

If you still run into trouble unpublishing, please let us know.
