### ISSUE TITLE
unpublish unauthorized - atom-captain-sweetheart

### ISSUE THREAD

**Issue by mashaal** [atom/apm#683]
I have in issue with duplicated packages. Could we remove `atom-captain-sweetheart`? The correct one is minus the 'atom-'.

I have tried to delete but it does not authorise and a message on screen says this

Unpublishing atom-captain-sweetheart failed
Unpublishing failed: Unauthorized

Can you help me please ? @lee-dohm

**Comment by lee-dohm** [comment]
@AndreaGriffiths11 can you delete the `atom-captain-sweetheart` package for me?

**Comment by AndreaGriffiths11** [comment]
Got it @lee-dohm, atom-captain-sweetheart is deleted as requested.
