### ISSUE TITLE
README.md points to ~/.atom/.atomrc that does not exist

### ISSUE THREAD

**Issue by userlerueda** [atom/apm#686]
### Prerequisites

* [ X ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

README.md points to `~/.atom/.atomrc` for configuration but configuration file is in `~/.atom/.apm/.apmrc` on macOS

### Steps to Reproduce

1. Try editing ~/.atom/.atomrc

**Expected behavior:** [What you expect to happen]
File is found and can be edited.

**Actual behavior:** [What actually happens]
File is not found.

**Reproduces how often:** [What percentage of the time does it reproduce?]
Happens all the time.

### Versions

```
$ atom --version
Atom    : 1.14.1
Electron: 1.3.13
Chrome  : 52.0.2743.82
Node    : 6.5.0
$ apm --version
apm  1.15.3
npm  3.10.5
node 4.4.5 x64
python 2.7.13
git 2.11.1
```
### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by Aerijo** [comment]
This is still perhaps a dcumentation issue, but in my experience it is expected the user will create a configuration file if it does not already exist.

**Comment by 50Wliu** [comment]
I don't think atomrc is a thing; that's the documentation issue. Fairly certain it should be apmrc.

**Comment by Aerijo** [comment]
@50Wliu Oh yeah, totally missed that part. In that case it appears to have been fixed at some point.
