### ISSUE TITLE
cannot install nuclide in atom

### ISSUE THREAD

**Issue by Zedonboy** [atom/apm#708]
### Prerequisites

* [ ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

i cannot install nuclide

### Steps to Reproduce
I typed `apm install nuclide` in cmd with admin privelledge

**Expected behavior:** 
for nuclide to be installed

**Actual behavior:** 
gives me this error
```
gyp info it worked if it ends with ok
gyp info using node-gyp@3.4.0
gyp info using node@4.4.5 | win32 | x64
gyp http GET https://atom.io/download/electron/v1.3.13/iojs-v1.3.13.tar.gz
gyp http 200 https://atom.io/download/electron/v1.3.13/iojs-v1.3.13.tar.gz
gyp WARN install got an error, rolling back install
gyp ERR! install error
gyp ERR! stack Error: read ECONNRESET
gyp ERR! stack     at exports._errnoException (util.js:870:11)
gyp ERR! stack     at TLSWrap.onread (net.js:552:26)
gyp ERR! System Windows_NT 6.2.9200
gyp ERR! command "C:\\Users\\User\\AppData\\Local\\atom\\app-1.15.0\\resources
\\app\\apm\\bin\\node.exe" "C:\\Users\User\\AppData\\Local\\atom\\app-1.15.0\
\resources\\app\\apm\\node_modules\\node-gyp\\bin\\node-gyp.js" "install" "--run
time=electron" "--target=1.3.13" "--dist-url=https://atom.io/download/electron"
"--arch=x64" "--ensure"
gyp ERR! cwd C:\Users\user\.atom
gyp ERR! node -v v4.4.5
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok
```

**Reproduces how often:** [100%]

### Versions

apm  1.15.3
npm  3.10.5
node 4.4.5 x64
python
git 2.9.3.windows.2
visual studio
windows 8

### Additional Information
Thanks in Advance.

**Comment by Z-Y00** [comment]
i met the same one few hours ago on linux
i installed gyp and it was solved:)
maybe this can help you, if you need to reinstall gyp:D

**Comment by Zedonboy** [comment]
Roger @Z-Y00
