### ISSUE TITLE
issue regarding installation of expressjs

### ISSUE THREAD

**Issue by saisaraswathi** [atom/apm#720]
Microsoft Windows [Version 6.1.7601]
Copyright (c) 2009 Microsoft Corporation.  All rights reserved.

C:\Users\tejaswi.sombhatla>cd..

C:\Users>cd..

C:\>cd sandbox

C:\sandbox>cd mytasklist

C:\sandbox\mytasklist>set http_proxy=http://tejaswi.sombhatla:vijayalakshmi!1995
@10.219.2.220:80

C:\sandbox\mytasklist>npm install
npm WARN mytasklist@1.0.0 No repository field.

C:\sandbox\mytasklist>npm install
npm WARN mytasklist@1.0.0 No repository field.

C:\sandbox\mytasklist>npm config get proxy
null

C:\sandbox\mytasklist>"http://itl\infosys%5Ctejaswi.sombhatla:vijayalakshmi!1995
@10.219.2.220:80/"
'"http://itl\infosys%5Ctejaswi.sombhatla:vijayalakshmi!1995@10.219.2.220:80/"' i
s not recognized as an internal or external command,
operable program or batch file.

C:\sandbox\mytasklist>npm config set proxy "http://itl\infosys%5Ctejaswi.sombhat
la:vijayalakshmi!1995@10.219.2.220:80/"

C:\sandbox\mytasklist>npm config get proxy
http://itl/infosys%5Ctejaswi.sombhatla:vijayalakshmi!1995@10.219.2.220:80/

C:\sandbox\mytasklist>yinnpm install
'yinnpm' is not recognized as an internal or external command,
operable program or batch file.

C:\sandbox\mytasklist>npm install
npm WARN mytasklist@1.0.0 No repository field.

C:\sandbox\mytasklist>cd..

C:\sandbox>cd..

C:\>D:

D:\>cd xyz

D:\xyz>mkdir fruits

D:\xyz>cd fruits

D:\xyz\fruits>npm install
npm WARN enoent ENOENT: no such file or directory, open 'D:\xyz\fruits\package.j
son'
npm WARN fruits No description
npm WARN fruits No repository field.
npm WARN fruits No README data
npm WARN fruits No license field.

D:\xyz\fruits>npm init
This utility will walk you through creating a package.json file.
It only covers the most common items, and tries to guess sensible defaults.

See `npm help json` for definitive documentation on these fields
and exactly what they do.

Use `npm install <pkg> --save` afterwards to install a package and
save it as a dependency in the package.json file.

Press ^C at any time to quit.
name: (fruits)
version: (1.0.0)
description: fruit shop
entry point: (index.js) server.js
test command:
git repository:
keywords:
author: teja
license: (ISC)
About to write to D:\xyz\fruits\package.json:

{
  "name": "fruits",
  "version": "1.0.0",
  "description": "fruit shop",
  "main": "server.js",
  "dependencies": {},
  "devDependencies": {},
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "teja",
  "license": "ISC"
}

Is this ok? (yes) yes

D:\xyz\fruits>npm install express body-parser ejs mongojs
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\
node_modules\\npm\\bin\\npm-cli.js" "install" "express" "body-parser" "ejs" "mon
gojs"
npm ERR! node v7.9.0
npm ERR! npm  v4.2.0
npm ERR! code ECONNRESET

npm ERR! network tunneling socket could not be established, cause=getaddrinfo EN
OTFOUND itl itl:80
npm ERR! network This is most likely not a problem with npm itself
npm ERR! network and is related to network connectivity.
npm ERR! network In most cases you are behind a proxy or have bad network settin
gs.
npm ERR! network
npm ERR! network If you are behind a proxy, please make sure that the
npm ERR! network 'proxy' config is set properly.  See: 'npm help config'

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\tejaswi.sombhatla\AppData\Roaming\npm-cache\_logs\2017-05-
12T11_19_04_097Z-debug.log

D:\xyz\fruits>npm install
npm WARN fruits@1.0.0 No repository field.

D:\xyz\fruits>npm init
This utility will walk you through creating a package.json file.
It only covers the most common items, and tries to guess sensible defaults.

See `npm help json` for definitive documentation on these fields
and exactly what they do.

Use `npm install <pkg> --save` afterwards to install a package and
save it as a dependency in the package.json file.

Press ^C at any time to quit.
name: (fruits)
version: (1.0.0)
git repository:
keywords:
license: (ISC)
About to write to D:\xyz\fruits\package.json:

{
  "name": "fruits",
  "version": "1.0.0",
  "description": "fruit shop",
  "main": "server.js",
  "dependencies": {},
  "devDependencies": {},
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "teja",
  "license": "ISC"
}

Is this ok? (yes) yes

D:\xyz\fruits>npm install
npm WARN fruits@1.0.0 No repository field.

D:\xyz\fruits>npm install express body-parser ejs mongojs --save
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\
node_modules\\npm\\bin\\npm-cli.js" "install" "express" "body-parser" "ejs" "mon
gojs" "--save"
npm ERR! node v7.9.0
npm ERR! npm  v4.2.0
npm ERR! code ECONNRESET

npm ERR! network tunneling socket could not be established, cause=getaddrinfo EN
OTFOUND itl itl:80
npm ERR! network This is most likely not a problem with npm itself
npm ERR! network and is related to network connectivity.
npm ERR! network In most cases you are behind a proxy or have bad network settin
gs.
npm ERR! network
npm ERR! network If you are behind a proxy, please make sure that the
npm ERR! network 'proxy' config is set properly.  See: 'npm help config'

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\tejaswi.sombhatla\AppData\Roaming\npm-cache\_logs\2017-05-
12T11_33_44_301Z-debug.log

D:\xyz\fruits>

**Comment by saisaraswathi** [comment]
can you please tell me how to eradicate this error

**Comment by 50Wliu** [comment]
Not sure what this has to do with APM.  I'm afraid we won't be able to help you.
