### ISSUE TITLE
apm develop always clones into ~/github  

### ISSUE THREAD

**Issue by simonmeusel** [atom/apm#721]
### Prerequisites

* [ X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description
When developing packages the git repos get cloned into ~/github instead of atom's project home config option

### Steps to Reproduce

0. Set custom clone folder in atom config: Core -> Project home; For example `/Users/simonmeusel/repos`
1. (any package possible)
> apm develop atom-material-ui
2. Go to home dir
3. See that repo got cloned to `~/github/atom-material-ui` instead of `~/repos/atom-material-ui`

**Expected behavior:** [What you expect to happen]

Repository should get cloned to project home config option

**Actual behavior:** [What actually happens]

Repository gets cloned to ~/github

**Reproduces how often:** [What percentage of the time does it reproduce?]

100%

### Versions

MacOS 10.12.4

> atom --version
> Atom    : 1.17.0
> Electron: 1.3.15
> Chrome  : 52.0.2743.82
> Node    : 6.5.0

> apm --version
> apm  1.17.0
> npm  3.10.5
> node 6.9.5 x64
> python 2.7.10
> git 2.11.0

**Comment by 50Wliu** [comment]
Atom is separate from apm - to set the location for apm to clone repos, set the `ATOM_REPOS_HOME` environment variable.

**Comment by simonmeusel** [comment]
Ok, thanks.
