### ISSUE TITLE
Unable to authenticate to github when using yubikey with SSH_AUTH_SOCK

### ISSUE THREAD

**Issue by mlaferrera** [atom/apm#723]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Unable to authenticate to github repo when using Yubikey as ssh key token and SSH_AUTH_SOCK

### Steps to Reproduce

1. Configure yubikey as ssh key token and SSH_AUTH_SOCK with gpg-agent
2. Modify a file in a github repo
3. Commit, then push modifications to github.

**Expected behavior:** Authentication to github repo is successful

**Actual behavior:** Permission is denied. Error message is displayed
```
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

**Reproduces how often:** 100%

### Versions

Atom    : 1.18.0-beta0
Electron: 1.3.15
Chrome  : 52.0.2743.82
Node    : 6.5.0

apm  1.16.1
npm  3.10.5
node 6.9.5 x64
python 2.7.13
git 2.13.0

### Additional Information

This functionality works fine in git-control and git-plus, just not the beta build of Atom supporting Git.

**Comment by 50Wliu** [comment]
Please reopen this on the [atom/github](https://github.com/atom/github) repository.
