### ISSUE TITLE
Renaming packages

### ISSUE THREAD

**Issue by benogle** [atom/apm#73]
Do we have a nice way to rename a package so that it doesnt break for current installs? I really want to tell people to rename their syntax themes (and rename a couple of ours, mac-ui, base16-tomorrow-dark, monokai). Also if folks want to rename for any other reason, it seems they cant. 

`apm mv`? `apm rename`??

**Comment by thedaniel** [comment]
@erikdahlstrom oh my, I'm so sorry that I let this sit for months - I think I missed it because the issue was closed. Since your last comment some changes were made to the backend that either should a) make it just work or b) make it easy for me to fix it up for you

**Comment by erikdahlstrom** [comment]
@thedaniel no worries, it seems to work now, just published an updated package, thank you.
