### ISSUE TITLE
Packages with apmInstallSource in package.json causes update packages to fail with undefined

### ISSUE THREAD

**Issue by ungb** [atom/apm#741]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Packages with apmInstallSource in package.json causes update packages to fail.
### Steps to Reproduce

1. Install a package that has `apmInstallSource` defined in package.json (example `apm install one-black-syntax`) see https://github.com/Adimote/one-black-syntax/blob/master/package.json#L16
2. Open Atom and go to update page.  
3. Go to updates page on settings view or run apm update on terminal.

**Expected behavior:** [What you expect to happen]
Updates still work

**Actual behavior:** [What actually happens]
Update fails to fetch with undefined:
screenshot:
![image](https://user-images.githubusercontent.com/5624870/30084758-8d50e1b8-9248-11e7-8826-6cdbd9f878f2.png)

**Reproduces how often:** [What percentage of the time does it reproduce?]
100%

### Versions

```
Atom    : 1.19.5
Electron: 1.6.9
Chrome  : 56.0.2924.87
Node    : 7.4.0

apm  1.18.4
npm  3.10.10
node 6.9.5 x64
python 2.7.10
git 2.11.0

```
### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

Related to: https://github.com/jesseweed/seti-syntax/pull/146 https://github.com/atom/apm/issues/620#issuecomment-326748409

**Comment by as-cii** [comment]
/cc: @iolsen we should put this higher on our list of prioritized items. Updates for _all_ the packages stop working when at least one package defines `apmInstallSource`.

**Comment by leroix** [comment]
fixed by https://github.com/atom/apm/pull/758
