### ISSUE TITLE
Unable to find remote helper for 'git+https'

### ISSUE THREAD

**Issue by idleberg** [atom/apm#753]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

I've been away over the weekend, meaning that I been able to actively change my Atom setup on any of my computers. As of Monday, I'm no longer able to publish any package updates.

```
Preparing and tagging a new version ✓
Pushing v1.10.3 tag ✗
fatal: Unable to find remote helper for 'git+https'
```

I’ve experienced this on several computers (each running the latest macOS), both with an existing local repo and a fresh clone. Also, I would've loved to test this using the latest beta, but it seems my `apm` isn't updated, even after manually running the command to install shell tools. 

PS: I'm aware of [this post](https://discuss.atom.io/t/windows-fix-fatal-unable-to-find-remote-helper-for-https/18434), but it's of no help at all.

### Steps to Reproduce

(not sure how useful these steps really are)

1. `git clone https://github.com/idleberg/atom-browse`
2. `cd atom-browse`
3. `apm publish patch`

**Expected behavior:** Publish package

**Actual behavior:** See error message above

**Reproduces how often:**  100%

### Versions

You can get this information from copy and pasting the output of `atom --version` and `apm --version` from the command line. Also, please include the OS and what version of the OS you're running.

```sh
$ system_profiler SPSoftwareDataType
Software:

    System Software Overview:

      System Version: macOS 10.13 (17A365)
      Kernel Version: Darwin 17.0.0

$ atom --version
Atom    : 1.22.0
Electron: 1.6.15
Chrome  : 56.0.2924.87
Node    : 7.4.0

$ apm --version
apm  1.18.8
npm  3.10.10
node 6.9.5 x64
python 2.7.10
git 2.13.5
```

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by idleberg** [comment]
In the meantime I was able to test publishing on Window 10 and the same error pops up. I've done some additional reseach and followed some tips given from the npm repository (e.g. update Git version, after all there was an update for the XCode Command Line Tools). However, none of this helped.

More importantly, I have noticed that I could publish other packages! After some more trial & error, I finally managed to publish the package with `apm publish --tag v1.10.3`. Hopefully, I can use `apm publish <major|minor|patch>` from now on. Otherwise, I will come back to this.

I realize finding a workaround is likely not satisfactory for you developers. If I can provide any more information, please let me know!

**Comment by 50Wliu** [comment]
What's the output of `git remote -v`?

**Comment by idleberg** [comment]
> What's the output of git remote -v?

```
origin	https://github.com/idleberg/atom-browse.git (fetch)
origin	https://github.com/idleberg/atom-browse.git (push)
```

In the meantime I also tried publishing using `apm publish patch`, but I get the same problem as before while publishing with `--tag` still works.

Another new oddity is that with every `apm publish`, I have to speciy my token. Contrary to the output message, the token is not saved to the keychain:

```
Saving token to Keychain ✓
(node:19196) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: The user name or passphrase you entered is not correct.
```

**Comment by skaraman** [comment]
I'm having the same issue when trying to update a syntax theme:

```
> apm publish minor
Preparing and tagging a new version ✓
Pushing v0.3.0 tag ✗
fatal: Unable to find remote helper for 'git+https'

> git remove -v
origin	https://github.com/skaraman/atom-tinacious-design-syntax.git (fetch)
origin	https://github.com/skaraman/atom-tinacious-design-syntax.git (push)
```

**Comment by idleberg** [comment]
> I was able to avoid this issue by removing git+ from my package.json:

That solved it for me as well, cheers!

**Comment by lee-dohm** [comment]
Looks like things are working for you now. Let us know if the problem reoccurs :+1:

**Comment by almic** [comment]
I just thought I'd come here and let you all know this problem still persists. I had `git+` in my repo link after using NPM to regenerate the package.json at some point. It would be really great if you could fix this because it really wasn't obvious that this was causing the problem, yet it should be trivial to detect that in apm.

**Comment by danielbayley** [comment]
I just ran into this also… I don't think the issue should be closed. 😕

**Comment by skaraman** [comment]
> I just ran into this also… I don't think the issue should be closed. 😕

Consider Atom dead, the support for it practically is. Just swap over to VSC, it’s much better than Atom and basically everything atom wanted to become.

**Comment by jayvastani** [comment]
I also ran into the same issue. When I run the command- 
`git remote -v`
I get response
`fatal: not a git repository (or any of the parent directories): .git`
