### ISSUE TITLE
Publishing is incredibly confusing

### ISSUE THREAD

**Issue by JoshCheek** [atom/apm#756]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Publishing is incredibly confusing, I've clearly done it before, but I'm on a new computer now and ultimately failed.

<img width="418" alt="screen shot 2017-11-18 at 4 18 07 pm" src="https://user-images.githubusercontent.com/77495/32985291-2538246e-cc7d-11e7-9275-8093bb7e51f0.png">

It needs an API token. Fair enough, but then I realized it was going to open Chrome, and I very explicitly killed Chrome and am using Safari for the moment, because Chrome destroys my battery life. I had already opened the link in Safari, but there is no option to skip and provide the token.

<img width="556" alt="screen shot 2017-11-18 at 4 18 26 pm" src="https://user-images.githubusercontent.com/77495/32985305-61a545da-cc7d-11e7-8c5e-edcc36eefc65.png">

Maybe I can pass it directly to config? Maybe, but if so, I need to know the name to set.

<img width="426" alt="screen shot 2017-11-18 at 4 18 45 pm" src="https://user-images.githubusercontent.com/77495/32985313-954adea4-cc7d-11e7-802d-355674546dd5.png">

Fine, let it open Chrome, immediately kill Chrome and paste the token... But now it wants to know my GH credentials? That's a security risk. Also, what if I'm not using git or github? Also, I already pushed to GitHub, so there's nothing for it to do.

<img width="1002" alt="screen shot 2017-11-18 at 4 33 03 pm" src="https://user-images.githubusercontent.com/77495/32985338-478391ce-cc7e-11e7-9b7d-862edc057cb8.png">

At this point, I go to the site, trying to skip the command-line tool and make a new version manually. I make the version (apparently via the GH API).

<img width="741" alt="screen shot 2017-11-18 at 4 34 46 pm" src="https://user-images.githubusercontent.com/77495/32985346-6f06c216-cc7e-11e7-94d7-858147a9e149.png">

But I get the old version when I install it with Atom. So now I go back to the command-line and try to tell it to tell Atom packages about the already published version.

<img width="1423" alt="screen shot 2017-11-18 at 4 16 32 pm" src="https://user-images.githubusercontent.com/77495/32985352-81282eb2-cc7e-11e7-8fc8-7149e272fcec.png">

I legitimately can't figure it out, so now I have no idea how to publish.

<img width="383" alt="screen shot 2017-11-18 at 4 36 59 pm" src="https://user-images.githubusercontent.com/77495/32985357-ba8c68d0-cc7e-11e7-9db0-af3295fee275.png">

As an aside, I experience a lot of confusion every time I go to publish, but historically I've eventually succeeded. I just wanted to point this UX issue out, it feels like the tool is trying to do too much, I just need the most basic abilities.

Cheers, and I appreciate all the good work, despite my issue :)

**Comment by JoshCheek** [comment]
Oh, also note that in the error messages, it told me to log the issue at npm's GH, not apm's. And that bit "You specified a tag with the version number '.3.0'" is clearly a bug, you can see just above it, I passed "2.3.0"

**Comment by 50Wliu** [comment]
It looks like you jumped to a lot of conclusions here :).

`apm help` reveals that `apm login` exists, and `apm help login` demonstrates the usage of the `apm login --token <token>` command.

`apm` needs your GH credentials to, quite simply, push your changes to GitHub.  There is no way to skip this if supplying a version number or semver type.  You may want to look into a [credential manager for Git](https://help.github.com/articles/caching-your-github-password-in-git/) to handle storing your credentials for you.

`apm` [does not, and will not, support](https://github.com/atom/apm/issues/754#issuecomment-344399754) publishing packages to the https://atom.io registry if they are not available on GitHub.  It also does not, and will not, support installing packages that are not using the Git version control system.

Also, the standard way is to let apm do all the work for you by simply supplying `apm publish major|minor|patch`, which will update your package.json with the new semver-compliant version number, create the tag, create a new commit, push to GitHub, and update the https://atom.io registry.
To do everything manually the tag name should have worked but it looks like there might be a bug with tag parsing, as it's returning `.3.0` instead of `2.3.0`.  If you still can't get that to work it may be worth it to file a new bug.

**Comment by JoshCheek** [comment]
> apm does not, and will not, support publishing packages to the https://atom.io registry if they are not available on GitHub. It also does not, and will not, support installing packages that are not using the Git version control system.

I had completely forgotten that this was a GitHub project. Look, I love GitHub, I pay for private repos just so I can give GitHub money, but it makes Atom worse to introduce a hard dependency on GitHub. It feels coercive and makes me want to use GitHub less.

---

Anyway, the code is currently tagged and on GitHub [here](https://github.com/JoshCheek/atom-seeing-is-believing/releases/tag/2.3.0), I assume if I `apm publish major|minor|patch` that it will incorrectly change the version.

Actually, I bet that's how I've dealt with it before...

---

Okay, just looked through the commit history, there's three places where this has happened in the past, just one version bump right after the other with gaps in published versions because the interface completely confused me.

<img width="871" alt="screen shot 2017-11-18 at 7 53 26 pm" src="https://user-images.githubusercontent.com/77495/32986551-3177eefe-cc9a-11e7-8f2f-386100037192.png">

I guess this will be the fourth time now that I double-bump the version due to this issue. Looks like that first time I bumped the patch level by hand, and then when I eventually figured out that the tool wouldn't publish it, I was like "fine, apm, go ahead and bump it again, then" but I put "minor" instead of "patch", just throwing the whole thing into disarray.

Apparently I tried to leave myself a note so I wouldn't hit that again:

<img width="976" alt="screen shot 2017-11-18 at 7 33 01 pm" src="https://user-images.githubusercontent.com/77495/32986456-5df7bb1a-cc97-11e7-80c4-3aed21f37c01.png">

But, that didn't work >.<

<img width="975" alt="screen shot 2017-11-18 at 7 33 13 pm" src="https://user-images.githubusercontent.com/77495/32986460-6c7bc884-cc97-11e7-9ab6-0135778ac57b.png">

I guess we're at the "write a wrapper binary" stage :(

**Comment by JoshCheek** [comment]
Update: the reason it wants me to enter my GitHub credentials is b/c it's using the wrong protocol. It's pushing to `https://github.com/JoshCheek/atom-seeing-is-believing` instead of `git@github.com:JoshCheek/atom-seeing-is-believing`. It got this value from `Packages.getRemote(pack)`, I didn't bother trying to figure out how that code got it.

I've already thought through the reason that problem comes up, and what to do about it (remove the dep on GH, at least for this step), I can explain the chain of thought if anyone wants, but I'll leave it at that so I don't browbeat y'all.

I got my thing published and have a wrapper program for the future, so I'll let y'all decide to leave it open or close it based on whether you think there's a UX issue.

**Comment by 50Wliu** [comment]
I'm going to close this as we have an existing Flight Manual page for publishing at http://flight-manual.atom.io/hacking-atom/sections/publishing/.

**However**, if you'd like to open issues regarding the incorrect protocol and incorrect tag checking, that would be appreciated (just make sure they haven't been reported already!).
