### ISSUE TITLE
Publishing a new Package fails

### ISSUE THREAD

**Issue by philschatz** [atom/apm#759]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * ~~Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode~~
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Publishing a _new_ Package (`sourcemap`) does not work for me. [Source Repository](https://github.com/philschatz/atom-sourcemap)

### Steps to Reproduce

1. `git clone https://github.com/philschatz/atom-sourcemap`
1. `npm install`
1. `apm publish minor`

**Expected behavior:** A new package is uploaded to https://atom.io/packages/sourcemap

**Actual behavior:**

```
$ apm publish minor
Registering sourcemap ✗
Registering package in philschatz/atom-sourcemap repository failed: That repo does not exist, isn’t an atom package, or you do not have access
$
```

**Reproduces how often:** 100% (I tried about 10 times over the last couple of days)

I also tried the following:

- publishing a new version of an existing package **worked**: https://atom.io/packages/pull-requests
- creating a new package via https://flight-manual.atom.io/hacking-atom/sections/package-word-count/#package-generator **did not work** (same error) [link to repo](https://github.com/philschatz/test-philschatz)

### Versions

I am running macOS 10.11.6

```
$ atom --version
Atom    : 1.22.1
Electron: 1.6.15
Chrome  : 56.0.2924.87
Node    : 7.4.0
$ apm --version
apm  1.18.8
npm  3.10.10
node 6.9.5 x64
python 2.7.10
git 2.10.1
```

### Additional Information

I raised the issue in the `#atom` Slack channel and was sent here. Also, I tried changing the name of the package to `sourcemap-viewer` but received the same error.

**Comment by lee-dohm** [comment]
What happens if you use `apm install` in the second step instead of `npm install`? You shouldn't be using `npm install` in any of this process ... npm != apm.

**Comment by philschatz** [comment]
Unfortunately, that yielded the same error.

```
$ pwd
/Users/me/github/atom-sourcemap
$ rm -rf ./node_modules/
$ apm install
Installing modules ✓
$ apm publish minor
Registering sourcemap ✗
Registering package in philschatz/atom-sourcemap repository failed: That repo does not exist, isn't an atom package, or you do not have access
```

"You raised my hopes and dashed them quite expertly, sir. Bravo!" -- Futurama

**Comment by jasonrudolph** [comment]
@philschatz: I _think_ this issue might be due to atom.io using a stale/no-longer-valid GitHub OAuth token for you. When apm asks the atom.io API to verify that you have access to [philschatz/atom-sourcemap](https://github.com/philschatz/atom-sourcemap), atom.io uses your GitHub OAuth token to ask the GitHub API to verify your permissions. If that OAuth token is invalid (e.g., if revoked atom.io's access to your GitHub account), then the GitHub API rejects the request due to invalid credentials. (If this is indeed the root cause, it likely means that we should enhance the atom.io API to provide a better error message.)

Would you mind running through these steps and letting us know the results?

1. Revoke any remaining access that you've previously granted to atom.io
    1. Visit https://github.com/settings/connections/applications/e2c0e43b4a123468e341
    2. If you see a page that looks like [this](https://user-images.githubusercontent.com/2988/33582624-268026e2-d924-11e7-9cfb-fcf9a459cdcc.png), then click "Revoke access". If you don't see a page that looks like [this](https://user-images.githubusercontent.com/2988/33582624-268026e2-d924-11e7-9cfb-fcf9a459cdcc.png), it means you've previously revoked access, and you can move on to the next step.
2. Re-authorize atom.io
    1. Visit https://atom.io/login
    2. Review the permissions it's requesting and click "Authorize atom"
3. Try publishing again (`apm publish minor`)

Please let us know how it goes. :bow:

**Comment by philschatz** [comment]
Yay, that worked! I had the screen that you mentioned and I think I first authorized atom back in 2015. Thanks @ jasonrudolph  and @lee-dohm for the help and 👍  on returning a more-detailed 400 message.

```
$ apm publish minor
Registering sourcemap ✓
Preparing and tagging a new version ✓
Pushing v0.1.0 tag ✓
Publishing sourcemap@v0.1.0 ✓
Congrats on publishing a new package! 👍  📦  🎉
Check it out at https://atom.io/packages/sourcemap
```
