### ISSUE TITLE
Better error message when OAuth fails

### ISSUE THREAD

**Issue by lee-dohm** [atom/apm#760]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Attempting to publish a new package fails with a cryptic error message:

```
$ apm publish minor
Registering new-package ✗
Registering package in some-user/new-package repository failed: That repo does not exist, isn’t an atom package, or you do not have access
```

See #759 for an example.

### Steps to Reproduce

I believe this will reproduce the problem but I haven't tested them yet.

1. Create a package by following the instructions in the Flight Manual
1. Execute `apm login`
1. Visit https://github.com/settings/connections/applications/e2c0e43b4a123468e341 and click "Revoke access"
1. Execute `apm publish minor`

**Expected behavior:** An error message that suggests you need to visit https://atom.io/login

**Actual behavior:** An error message that just says something mysteriously failed

### Versions

Atom    : 1.24.0-dev-c4b38c615
Electron: 1.6.15
Chrome  : 56.0.2924.87
Node    : 7.4.0

apm  1.18.10
npm  3.10.10
node 6.9.5 x64
atom 1.24.0-dev-c4b38c615
python 2.7.10
git 2.15.0

**Comment by leroix** [comment]
@lee-dohm @jasonrudolph I'm having trouble reproducing this error message, but that may be because apm always requires me to enter my username and password. Oauth never seems to work for me for some reason.

In any case, the error message that this issue is referring to is coming from the response of the post to https://atom.io/api/packages request here: https://github.com/atom/apm/blob/master/src/publish.coffee#L162. Perhaps, we should add a note about trying to re-authorize in that error message? Note: I don't have access to the code running on that server.

**Comment by jasonrudolph** [comment]
> the error message that this issue is referring to is coming from the response of the post to https://atom.io/api/packages request here: https://github.com/atom/apm/blob/master/src/publish.coffee#L162. Perhaps, we should add a note about trying to re-authorize in that error message?

I think that would be a good approach.

**Comment by jasonrudolph** [comment]
We've rolled out an update to atom.io to provide a more useful error message:

#### Before

```
$ apm publish minor
Registering bug-free-palm-tree ✗
Registering package in jasonrudolph/atom-test-package repository failed: That repo does not exist, isn't an atom package, or you do not have access
```

#### After

```
$ apm publish minor
Registering bug-free-palm-tree ✗
Registering package in jasonrudolph/atom-test-package repository failed: Please visit https://atom.io/login to reconnect atom.io to your GitHub account, and then try again.
```
