### ISSUE TITLE
Unable to Publish

### ISSUE THREAD

**Issue by daylerees** [atom/apm#765]
Hi there,

I'm currently trying to publish an Atom plugin, and it's failing on an error that I believe is related to the Apple Keychain. Here's the output:

```
~/P/r/atom ❯❯❯ apm publish patch
Welcome to Atom!

Before you can publish packages, you'll need an API token.

Visit your account page on Atom.io https://atom.io/account,
copy the token and paste it below when prompted.

Press [Enter] to open your account page on Atom.io.
Token> _pe_0ICENSORED_TOKENiBBtw
Saving token to Keychain ✓
(node:72630) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): Error: The user name or passphrase you entered is not correct.
Preparing and tagging a new version ✓
Pushing v1.5.6 tag Username for 'https://github.com': daylerees
Password for 'https://daylerees@github.com':
✓
Publishing rainglow-atom@v1.5.6 Welcome to Atom!

Before you can publish packages, you'll need an API token.

Visit your account page on Atom.io https://atom.io/account,
copy the token and paste it below when prompted.

Press [Enter] to open your account page on Atom.io. ✗
```

at which point it seems to go around in a loop.

Interestingly enough, after attempting to use apm, docker stopped working with similar keychain-related issues. I had to disable keychain credentials to get docker able to push/pull from dockerhub once again.

I'd be grateful for any help, thank you!

```
~/P/r/atom ❯❯❯ apm -v                                                                                                                                       ⏎
apm  1.18.12
npm  3.10.10
node 6.9.5 x64
atom 1.23.2
python 2.7.10
git 2.7.0
```

**Comment by 50Wliu** [comment]
Hmm, did the v1.5.6 tag get pushed to your package's GitHub repository?

**Comment by daylerees** [comment]
I don't think so. But it updated the package.json a few times through failed attempts.

**Comment by mostafa6765** [comment]
May be this is node problem or your apm token issue 

https://github.com/nodejs/node/issues/9242

**Comment by mostafa6765** [comment]
@50Wliu yah v1.5.6 is pushing by apm but apm package does not publish for token issue . may me token mismatch.

**Comment by daylerees** [comment]
I managed to resolve this issue by emptying my OSX key chain. APM worked perfectly afterwards. Will close the issue. Thanks for reading anyway!
