### ISSUE TITLE
Support packages with scoped names

### ISSUE THREAD

**Issue by szeck87** [atom/apm#766]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: https://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

npm supports scoped package naming, for example `@scopename/packagename`, in package.json as a way of grouping similar packages together.  When installed, they are placed in `node_modules/@scopename/packagename`.

When Atom installs these packages, they are not recognized since the actual package(s) is in `.atom/packages/@scopename/package`.  It would be nice for Atom to support packages named this way.

### Steps to Reproduce

1. Create a new package and name it `@scopedname/packagename`
2. apm link the package (if not already), and reload Atom
3. Go to the installed packages

**Expected behavior:** Show the package in the packages view

**Actual behavior:** Shows the scoped name in the packages view, which does nothing, and package is installed to `.atom/packages/@scopename/package`

**Reproduces how often:** 100%

### Versions

1.23.3, MacOS

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by szeck87** [comment]
Any feedback on this request?

**Comment by rsese** [comment]
Sorry for the delay @szeck87 - I asked the team to take a look and though there's interest, it's not something that would get attention in the foreseeable future so we'll close for now and re-open if it's it's picked up in the future.
