### ISSUE TITLE
apm publish cannot be used with 2FA

### ISSUE THREAD

**Issue by tgandrews** [atom/apm#768]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

When publishing the a package it requests github username and password which always fails when 2FA is enabled.

It seems to be doing this because it is trying to push the tag and then using the https defined repo url in the package.json file. Instead it should be using the origin defined on the 

### Steps to Reproduce

1. Move to repo of atom package with https repo url defined in package.json
1. Set up 2FA for your github account
1. Run `apm publish [patch|major|minor]`

**Expected behavior:** [What you expect to happen]

- It would use the origin defined in the git repo.
- Or, it would support 2FA and allow for github login

**Actual behavior:** [What actually happens]

- It reads the repository in package.json over the origin
- Authentication to github always fails

**Reproduces how often:** [What percentage of the time does it reproduce?]

100% of the time.

### Versions

You can get this information from copy and pasting the output of `atom --version` and `apm --version` from the command line. Also, please include the OS and what version of the OS you're running.

```
apm  1.18.12
npm  3.10.10
node 6.9.5 x64
atom 1.23.3
python 2.7.10
git 2.16.1
```

### Additional Information

An example repository in package.json:
```json
"repository": {
  "type": "git",
  "url": "https://github.com/foo/bar"
}
```

**Comment by jesseweed** [comment]
👍 I had to disable my 2fa in Github in order to publish an update, would love to see a fix for this!

**Comment by smashwilson** [comment]
It isn't particularly graceful, but you can provide a [personal access token](https://help.github.com/articles/creating-a-personal-access-token-for-the-command-line/) in place of your password to publish while 2fa is enabled. (Note that this is the same solution you use to `git push` to https remotes with 2fa, which is what `apm` is doing for you here :smile:)

**Comment by smashwilson** [comment]
For now, I'm just adding a note to the README about this.

A "Real Solution" here would be a git credential helper that interacts with GitHub 2fa properly. wincred already does this on Windows; I'm looking around to see if anyone else has already done this? In any case, it's something that we should address within git, not hack in with apm 😄
