### ISSUE TITLE
apm publish: npm error / git tag not found

### ISSUE THREAD

**Issue by jaredallard** [atom/apm#770]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Can't publish a forked repo's package.

### Steps to Reproduce

1. Forked `language-mustache`
2. `git tag v1.0.1`
3. Tried to run `apm publish -t v1.0.1`
3. error

**Expected behavior:** It publishes as expected

**Actual behavior:** It errors.

**Reproduces how often:** 100%

### Versions

```bash
atom --version

Atom    : 1.23.3
Electron: 1.6.15
Chrome  : 56.0.2924.87
Node    : 7.4.0

apm --version

apm  1.18.12
npm  3.10.10
node 6.9.5 x64
atom 1.23.3
python 2.7.10
git 2.16.1

npm --version

5.6.0

node (system) --version

v9.4.0
```

### Additional Information

Error log:

```bash
➜  language-forge git:(master) apm unpublish
Are you sure you want to unpublish ALL VERSIONS of 'language-forge'? This will remove it from the apm registry, including download counts and stars, and this action is irreversible. (no)yes
Unpublishing language-forge ✓

➜  language-forge git:(master) apm publish -t v1.0.1
Registering language-forge ✓
Publishing language-forge@v1.0.1 ✗
Creating new version failed: Git tag not found

➜  language-forge git:(master) apm publish language-forge
Preparing and tagging a new version ✗
npm ERR! npm version [<newversion> | major | minor | patch | premajor | preminor | prepatch | prerelease | from-git]
npm ERR! (run in package dir)
npm ERR! 'npm -v' or 'npm --version' to print npm version (3.10.10)
npm ERR! 'npm view <pkg> version' to view a package's published version
npm ERR! 'npm ls' to inspect current package/dependency versions
```

Package is: `language-forge` at https://github.com/jaredallard/language-forge, it's not different from `language-mustache` much, but it will be later.

**Comment by lkashef** [comment]
Hey @jaredallard, can you verify if the issue persists?

**Comment by jaredallard** [comment]
I can't, this was a private project for a company I no longer work for and was no longer used. Sorry!

**Comment by lkashef** [comment]
No worries @jaredallard, I wanted to know if you still need help on that since it was an old report.

Thanks for the update , I will go ahead and close this issue then.
