### ISSUE TITLE
apm not responding on windows, even though its listed in path

### ISSUE THREAD

**Issue by aronlmin** [atom/apm#771]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

I added have added all of the following folders to my PATH, atom responds in my command line, but not apm, I cannot download or install packages in atom

C:\Users\ALilland\AppData\Local\atom\bin\
C:\Users\ALilland\AppData\Local\atom\app-1.23.3\resources\cli\
C:\Users\ALilland\AppData\Local\atom\app-1.23.2\resources\cli\

### Steps to Reproduce

after adding it, I can run where apm and get it to respond, but it wont respond on its own.
```
C:\Users\ALilland\AppData\Local\atom>where apm
C:\Windows\System32\apm.cmd
C:\Users\ALilland\AppData\Local\atom\bin\apm
C:\Users\ALilland\AppData\Local\atom\bin\apm.cmd
C:\Users\ALilland\AppData\Local\atom\app-1.23.3\resources\cli\apm.cmd
C:\Users\ALilland\AppData\Local\atom\app-1.23.2\resources\cli\apm.cmd

C:\Users\ALilland\AppData\Local\atom>
```

**Expected behavior:** [What you expect to happen]
Expected APM to work

**Actual behavior:** [What actually happens]
When not in the folder and I run apm -v it responds with 
```
The system cannot find the path specified.
```

**Reproduces how often:** [What percentage of the time does it reproduce?]
100%
### Versions
if I am inside the bin directory apm responds....
```
C:\Users\ALilland\AppData\Local\atom\bin>apm -v
apm  1.18.12
npm  3.10.10
node 6.9.5 x64
atom 1.23.3
python
git 2.8.0.windows.1
visual studio 2015

C:\Users\ALilland\AppData\Local\atom\bin>
```

You can get this information from copy and pasting the output of `atom --version` and `apm --version` from the command line. Also, please include the OS and what version of the OS you're running.

### Additional Information

several versions ago (like sometime in 2016) atom was working with apm, but I moved over to dev on mac, after returning to windows its been nothing but headaches

I attempted using a %USERPROFILE% and that did not work either, in fact, when I did atom no longer worked either. At this time, atom responds from the CLI

I am using windows 10 Pro, version 1709, OS Build 16299.125

**Comment by rsese** [comment]
Hmmm I wonder if there's an issue with your PATH?  What do you get in `cmd` when you run `PATH`?   Also, I'm not sure what the `C:\Windows\System32\apm.cmd` is, did `apm.cd` from your Atom install get copied over there somehow?

**Comment by rsese** [comment]
Since `C:\Windows\System32\` is likely pretty early in your path it looks like that `apm.cd` in there was messing things up.  Not sure how that got there, but I'm glad we have things sorted out.
