### ISSUE TITLE
NPM out of space errors cause logs to be deleted on failed addon installs

### ISSUE THREAD

**Issue by S0AndS0** [atom/apm#783]
### NPM out of space errors cause logs to be deleted on failed addon installs

This maybe a bug within `npm` but on systems with a tiny temp mount, install logs are removed upon out of space errors; see issue [Atom Beautify - 2101](https://github.com/Glavin001/atom-beautify/issues/2101) for recovered log samples.

### Steps to Reproduce

1. Modify the `fstab` file and mount temp to a small amount of memory

```
    nano /etc/fstab
    ## ...
    tmpfs /tmp tmpfs defaults,noatime,nosuid,nodev,noexec,mode=1777,size56M 0 0
    ## ...
```

2. Wait a few months and forget about the changes made
3. Then attempt to install Atom Beautify or any other addon that requires a bit of space to do it's install thing
4. Watch logs get made then removed when errors about things being to big pop
5. Run `df -h /` to convince yourself that the system does in fact have enough space
6. Spend an hour or two web searching and searching through Git issues
7. File an issue when it has become apparent that there are insufficient rubber duckies to talk to
8. Run `df -h /tmp` after looking closely at recovered logs with another helpful soul, and place palm on forehead
9. Modify the `fstab` line so addons have a bit more breathing room for installation and close previous issue upon groovy install

**Expected behavior:**

- Downloads and compressed files should be removed
- Log file of failure should remain in temp directory that was made during installation or moved to parent directory

**Actual behavior:**

- Everything is removed, temp directory, it's continence, including the log file of failures

**Reproduces how often:** 

- Unlikely to be reproduced by many users, however, there maybe opportunity for abuse.

### Versions

    atom --version
    Atom    : 1.25.1
    Electron: 1.7.11
    Chrome  : 58.0.3029.110
    Node    : 7.9.0

    apm --version
    apm  1.19.0
    npm  3.10.10
    node 6.9.5 x64
    atom 1.25.1
    python 2.7.12
    git 2.7.4

### Additional Information

See the previously mentioned Git issue for Atom Beautify for blow-by-blow of debugging and resolving fringe-case installation errors.

**Comment by Arcanemagus** [comment]
This particular aspect of `apm` is handled by `npm`. I _believe_ I remember seeing something related to this around the NPM 5 updates, so hopefully we should inherit the fix for this when it is updated here.

I'm going to close this issue as there isn't anything that we can do to fix this on our end, other than updating the version of `npm` that is bundled.

Thanks for taking the time to file an issue!
