### ISSUE TITLE
fatal: Unable to find remote helper for 'https'

### ISSUE THREAD

**Issue by ajojothepineapple** [atom/apm#789]
### Prerequisites

* [ ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

[Description of the issue]

### Steps to Reproduce

1. Make change to file
2. Save File
3.Press Push

**Expected behavior:** [Push to master branch]

**Actual behavior:** [fatal: Unable to find remote helper for 'https']

**Reproduces how often:** [100%]

### Versions

You can get this information from copy and pasting the output of `atom --version` and `apm --version` from the command line. Also, please include the OS and what version of the OS you're running.

### Additional Information
- Windows 10 - Git bash works fine 
Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by kolyaventuri** [comment]
@ajojothepineapple I would be willing to look into this, but I can't seem to reproduce it. Can you provide your atom/apm versions (`atom --version` and `apm --version`) as well as more steps to reproduce the error? (I.e., is your repo using the https github remote url or the ssh one)
