### ISSUE TITLE
connect ETIMEDOUT 54.221.212.171:443

### ISSUE THREAD

**Issue by ricpelo** [atom/apm#790]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

When I try `$ apm update` I get the following error after a minute or so:

```
Request for package information failed: connect ETIMEDOUT 54.221.212.171:443
```

The IP address changes on subsequent runs (for instance, I got the same error message with IP addresses 23.23.171.5 and 54.173.32.212, always with 443 port).

### Steps to Reproduce

1. `apm update`

**Expected behavior:** [What you expect to happen]

`apm` connects to the server and checks if there're updates available.

**Actual behavior:** [What actually happens]

`apm` can't connect to the server and shows an error message.

**Reproduces how often:** [What percentage of the time does it reproduce?]

Always.

### Versions

```sh
$ atom --version
Atom    : 1.26.1
Electron: 1.7.11
Chrome  : 58.0.3029.110
Node    : 7.9.0
$ apm --version
apm  1.19.0
npm  3.10.10
node 6.9.5 x64
atom 1.26.1
python 2.7.15rc1
git 2.17.0
```

**Comment by ricpelo** [comment]
Sorry, it seems to be a personal network problem.

**Comment by yifengyou** [comment]
Just happen in China. Need proxy
