### ISSUE TITLE
Publishing a brand new package via HTTPS fails

### ISSUE THREAD

**Issue by calebmeyer** [atom/apm#792]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

I cannot publish any version of my new [skittles](https://github.com/calebmeyer/skittles) package.

### Steps to Reproduce

1. `git clone https://github.com/calebmeyer/skittles.git`
2. `apm publish --tag v1.0.1` (you can also try `apm publish patch`)

**Expected behavior:** The package is published to atom.io/packages

**Actual behavior:**
![image](https://user-images.githubusercontent.com/3342777/40499239-0055c2fc-5f47-11e8-8f70-04e747219f60.png)

**Reproduces how often:** 100% of the time

### Versions
```
$ apm --version
apm  1.19.0
npm  3.10.10
node 6.9.5 x64
atom 1.27.1
python 3.6.5
git 2.16.2.windows.1
visual studio

$ atom --version

Atom    : 1.27.1
Electron: 1.7.15
Chrome  : 58.0.3029.110
Node    : 7.9.0
```

Windows version: 
![image](https://user-images.githubusercontent.com/3342777/40499350-4a2d1d6c-5f47-11e8-950a-e741964495a1.png)

### Additional Information
Originally, I tried `apm publish major` once I was happy with the code in my package. It successfully tagged v1.0.0, but failed at the publish step. I tried publishing the v1.0.0 tag (`apm publish --tag v1.0.0`) and that also failed with the error you see above.

I then made some changes, committed and pushed them, then did `apm publish patch` to get to v1.0.1

I have been stuck here ever since, unable to push the package. I have tried re-logging in (getting a new token) and that has not worked. The error message seems to be coming from the remote, based on https://github.com/atom/apm/blob/master/src/publish.coffee#L190

I can see both tags on the skittles repo itself, so they've definitely been pushed successfully. Here's the output of some git commands:
```
$ git remote -v
origin  https://github.com/calebmeyer/skittles.git (fetch)
origin  https://github.com/calebmeyer/skittles.git (push)
$ git tag
v1.0.0
v1.0.1
$ git lg # git log --pretty=oneline and some other flags from my alias
* b1a4ca7 - (HEAD -> master, origin/master, origin/HEAD) Cropped image to be easier to see (6 days ago)<Caleb Meyer>
* adc2581 - (tag: v1.0.1) Prepare 1.0.1 release (6 days ago)<Caleb Meyer>
* 06840f1 - Updated readme (6 days ago)<Caleb Meyer>
* 2a9c67d - (tag: v1.0.0) Prepare 1.0.0 release (6 days ago)<Caleb Meyer>
* 4d8cf10 - Added semicolon (6 days ago)<Caleb Meyer>
* 7ee53f5 - Basic functionality all here (6 days ago)<Caleb Meyer>
* 3c54398 - And the other bit (6 days ago)<Caleb Meyer>
* d0dbd46 - Removed unnecessary content styles (6 days ago)<Caleb Meyer>
* decdce1 - Fixed toggling off (6 days ago)<Caleb Meyer>
* d1ec279 - Cleaned up colorize (6 days ago)<Caleb Meyer>
* c4f3785 - It works! Mostly (7 days ago)<Caleb Meyer>
* 81d986f - Testing highlighting using markers (9 months ago)<Caleb Meyer>
* 1488618 - Initial Commit (9 months ago)<Caleb Meyer>
```

cc @lee-dohm per his request

**Comment by thomasjo** [comment]
The problem turned out to be something super obvious; there's already a package registered using the name _skittles_; https://atom.io/packages/skittles. It was originally published under that name, although it was subsequently changed to _AtomicSkittles_, but since it was first published using under the other name, that is still owned by the package.

Since this is not really a bug/problem on our end, I'm going to close this issue. We should perhaps improve the backend logic such that we provide a better error message. Ideally we should detect that a package is using a name that has already been registered by someone else.

To fix your issue, choose another name for your package.
