### ISSUE TITLE
Packages download issue

### ISSUE THREAD

**Issue by Niteshiya** [atom/apm#794]
### Prerequisites

* [ X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

[cant download packages it shows an error every time]

### Steps to Reproduce

1. [goto install packages]
2. [find your package]
3. [after a while it says error]

**Expected behavior:** [i wanted to download the package]

**Actual behavior:** [Unable to download https://www.atom.io/api/packages/atom-beautify/versions/0.32.5/tarball: self signed certificate in certificate chain]

**Reproduces how often:** [100%]

### Versions

atom version=1.27.2
os=win10-64x

### Additional Information
i get this message every time:
Unable to download https://www.atom.io/api/packages/hydrogen/versions/2.5.0/tarball: self signed certificate in certificate chain

**Comment by thomasjo** [comment]
This should be fixed by running `apm config set strict-ssl false` from a terminal. 
See https://github.com/atom/atom/issues/4122 for more details.

**Comment by EvanWang2015** [comment]
This didn't work for me. I am running on windows 7 (don't ask me why windows 7).

**Comment by adjenks** [comment]
@thomasjo You suggest disabling security? That is not a solution, that is a security risk. https://github.com/atom/atom/issues/4122#issuecomment-427450720

**Comment by Jagdish-Ahir** [comment]
> This should be fixed by running `apm config set strict-ssl false` from a terminal.
> See [atom/atom#4122](https://github.com/atom/atom/issues/4122) for more details.

This works 
thanks
