### ISSUE TITLE
Fix 'apm disable'

### ISSUE THREAD

**Issue by JBallin** [atom/apm#801]
### Issue

```
$ apm install teletype
$ apm disable teletype
$ apm list
teletype@0.13.3
```

### Expected

1. `apm list` should output `teletype@0.13.3 (disabled)`
2. Package should not work
3. Package should show as disabled in Atom Package Settings (UI)
4. Package should be in `*.core.disabledPackages` Array in `~/.atom/config.cson`.

NOTE: Package UI enable/disable works, as does `apm enable`.

### Versions

[Discussion](https://discuss.atom.io/t/apm-disable-doesnt-work-on-my-machine/57133) with @rsese and @Aerijo: 
**Works**: 1.28.1 & 1.29.0-beta2
**Fails**: 1.28.2 & 1.30 (on master/nightly)

MacOS 10.13.5
apm 1.19.0

**Comment by JBallin** [comment]
Upon further review, this is related to atom and not apm specifically. The latest change to this repo was 1/19 and Atom worked fine up until the [1.28.2](https://atom.io/releases) came out on 7/13.
https://github.com/atom/atom/issues/17741

**Comment by JBallin** [comment]
Works in 1.29.0! 🎉

**Comment by rsese** [comment]
Going to go ahead and re-open, still an issue on the latest nightly I tried (`1.31.0-nightly0`) - we can just wait till https://github.com/atom/apm/pull/802 is merged, which will then auto-close this issue.  I think we noted that disable worked in the 1.29 beta so I think it makes sense that it worked for you in 1.29.
