### ISSUE TITLE
"Package must be in a Git repository before publishing"

### ISSUE THREAD

**Issue by dutartre** [atom/apm#826]
Hi,
When I try to publish my package, this message appear http://prntscr.com/mdang8
"Package must be in a Git repository before publishing: https://help.github.com/articles/create-a-repo"
But I already created a repertory, I don't understand.

Can someone help me?

**Comment by 50Wliu** [comment]
What is the output of `git status`?

**Comment by dutartre** [comment]
apparently I don't have the 'git' command. How can I get it? http://prntscr.com/mdltid
