### ISSUE TITLE
apm init --theme --convert doesn't work for files with spaces in name

### ISSUE THREAD

**Issue by izuzak** [atom/apm#83]
Halp ticket:
- support/9f3a7a7ebebb11e383c173e0a61e0839

> Apm command cannot convert a TextMate theme which has a space in its file name like "Classic Modified.tmTheme" even if it is escaped or quoted.

```
% apm init --theme ~/.atom/packages/ClassicModified --convert ~/Desktop/Classic\ Modified.tmTheme
TextMate theme file not found: /Users/xxxxxx/Desktop/Classic
% apm init --theme ~/.atom/packages/ClassicModified --convert ~/Desktop/"Classic Modified.tmTheme" 
TextMate theme file not found: /Users/xxxxxx/Desktop/Classic
```

Just gave this a try and got the same error.

**Comment by Fractal2017** [comment]
Try this:
apm init --theme ~/.atom/packages/ClassicModified --convert 'Desktop/Classic Modified.tmTheme'

I had a similar issue and got it resolved by adding quotes around the whole path and determining the right path for the theme file to be found.
