### ISSUE TITLE
apm list --bare > pkg incompatible with apm install --packages-file pkg

### ISSUE THREAD

**Issue by oomathias** [atom/apm#833]
### Description

I guess `--bare` was designed to be compatible with `apm install --packages-file` which isn't the case if you have git packages installed.
In other words, each line produced by `apm list -b` should be compatible with `apm install`

Common use case:
```sh
apm list -bi > pkg
apm install --packages-files pkg
```

### Steps to Reproduce

1. Have a least one package installed
2. Have a least one git package installed

**Fake test case**
```sh
apm install my-package
apm install org/repo  # Package name: other-package-name
```

**Expected behavior:** 

```
$ apm list -bi
my-package@0.0.1
org/repo
```

`org/repo` because `apm install` isn't compatible with `org/repo@something` or `org/repo#aabbccdd`

**Actual behavior:**

```
$ apm list -bi
my-package@0.0.1

other-package-name@0.0.1
```
- Notice the empty line, I think it would be cleaner to remove them.
- `other-package-name@0.0.1` is not compatible with `apm install`

**Comment by rsese** [comment]
Thanks for the report!  I see what you describe in your Expected/Actual behavior but can you clarify what you mean when you say:

> other-package-name@0.0.1 is not compatible with apm install

Just want to make sure I'm on the same page - for example, what I tried:

```
$ apm install hyperclick
Installing hyperclick to /Users/rsese/.atom/packages ✓
$ apm install defunkt/zen
Cloning https://github.com/defunkt/zen.git ✓
Installing modules ✓
Moving Zen to /Users/rsese/.atom/packages/Zen ✓
$ apm list -bi > pkg
$ cat pkg 
hyperclick@0.1.5

Zen@0.18.0
$ apm uninstall hyperclick
Uninstalling hyperclick ✓
$ apm uninstall Zen
Uninstalling Zen ✓
$ apm install --packages-file ./pkg
Installing hyperclick@0.1.5 to /Users/rsese/.atom/packages ✓
Installing Zen@0.18.0 to /Users/rsese/.atom/packages ✓
```

**Comment by oomathias** [comment]
Sorry for the delay.

I think it worked because `Zen@0.18.0` exist here https://atom.io/packages/zen

Doing `apm install defunkt/zen@0.18.0` does not work.

**Comment by rsese** [comment]
No problem :+1:

> I think it worked because `Zen@0.18.0` exist here https://atom.io/packages/zen
> 
> Doing `apm install defunkt/zen@0.18.0` does not work.

Just so I'm on the same page, can you share exact steps to reproduce the issue you described like the steps I shared [above](https://github.com/atom/apm/issues/833#issuecomment-488556826)?
