### ISSUE TITLE
What permissions does need a github's access token to run apm publish? (dual authentication enabled)

### ISSUE THREAD

**Issue by Zeioth** [atom/apm#834]
As described in the readme, I've followed [this guide](https://help.github.com/en/articles/creating-a-personal-access-token-for-the-command-line) to create an access token.

I gave to my access key the permissions:

    admin:repo_hook
    write:repo_hook 
    read:repo_hook 

But When I run apm publish minor I get the next error:

    ✗
    remote: Permission to Zeioth/atom-visual-studio-code-ui.git denied to Zeioth.
    fatal: unable to access 'https://github.com/Zeioth/atom-visual-studio-code-ui/': The requested URL returned error: 403

Also on my Github's security history i don't see any failed session attempt, which means the access token is accepted, it just don't have enough permissions. **So my question is**: What permissions should I give to an access token to be able to run apm publish?

**Comment by rsese** [comment]
The Flight Manual mentions that among other things, publishing will commit changes to your repository:

https://flight-manual.atom.io/hacking-atom/sections/publishing/#publish-your-package

In that case, I think you would need `public_repo` scope to publish.  

I just tested and this works for me - if you have any trouble, feel free to reach out on the [message board](https://discuss.atom.io/) and ping me there.
