### ISSUE TITLE
Unable to install platformio-ide-terminal package

### ISSUE THREAD

**Issue by noemitotos** [atom/apm#861]
OS: macOS Mojave
OS version: 10.14.5
Atom version: 1.39.0

Unable to install Platformio-ide-terminal (see error report below). I've tried clearing Atom's cache, reset configuration, reboot.

Installing “platformio-ide-terminal@2.9.1” failed.

node-pty-prebuilt@0.7.6 install /private/var/folders/nn/70tsyh815z50qs3md30yb7_40000gn/T/apm-install-dir-119624-4376-796xnv.qtz6e/node_modules/platformio-ide-terminal/node_modules/node-pty-prebuilt
prebuild-install || node scripts/install.js

prebuild-install WARN install No prebuilt binaries found (target=3.1.10 runtime=electron arch=x64 libc= platform=darwin)
No receipt for 'com.apple.pkg.CLTools_Executables' found at '/'.

No receipt for 'com.apple.pkg.DeveloperToolsCLILeo' found at '/'.

No receipt for 'com.apple.pkg.DeveloperToolsCLI' found at '/'.

gyp: No Xcode or CLT version detected!
gyp ERR! configure error
gyp ERR! stack Error: gyp failed with exit code: 1
gyp ERR! stack at ChildProcess.onCpExit (/private/var/folders/nn/70tsyh815z50qs3md30yb7_40000gn/T/AppTranslocation/4B0C2630-5797-40E9-8162-6F6EA878C7B5/d/Atom.app/Contents/Resources/app/apm/node_modules/npm/node_modules/node-gyp/lib/configure.js:345:16)
gyp ERR! stack at emitTwo (events.js:126:13)
gyp ERR! stack at ChildProcess.emit (events.js:214:7)
gyp ERR! stack at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Darwin 18.6.0
gyp ERR! command "/private/var/folders/nn/70tsyh815z50qs3md30yb7_40000gn/T/AppTranslocation/4B0C2630-5797-40E9-8162-6F6EA878C7B5/d/Atom.app/Contents/Resources/app/apm/bin/node" "/private/var/folders/nn/70tsyh815z50qs3md30yb7_40000gn/T/AppTranslocation/4B0C2630-5797-40E9-8162-6F6EA878C7B5/d/Atom.app/Contents/Resources/app/apm/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--build_v8_with_gn=false"
gyp ERR! cwd /private/var/folders/nn/70tsyh815z50qs3md30yb7_40000gn/T/apm-install-dir-119624-4376-796xnv.qtz6e/node_modules/platformio-ide-terminal/node_modules/node-pty-prebuilt
gyp ERR! node -v v8.9.3
gyp ERR! node-gyp -v v3.7.0
gyp ERR! not ok
npm WARN enoent ENOENT: no such file or directory, open '/private/var/folders/nn/70tsyh815z50qs3md30yb7_40000gn/T/apm-install-dir-119624-4376-796xnv.qtz6e/package.json'
npm WARN apm-install-dir-119624-4376-796xnv.qtz6e No description
npm WARN apm-install-dir-119624-4376-796xnv.qtz6e No repository field.
npm WARN apm-install-dir-119624-4376-796xnv.qtz6e No README data
npm WARN apm-install-dir-119624-4376-796xnv.qtz6e No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-pty-prebuilt@0.7.6 install: prebuild-install || node scripts/install.js
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-pty-prebuilt@0.7.6 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by noemitotos** [comment]
The issue has definitely been caused by the latest version release 1.39.0. I've installed Atom 1.38.1 and managed to install and run the terminal package.

**Comment by rsese** [comment]
Thanks for the report - based on the discussions in https://github.com/platformio/platformio-atom-ide-terminal/issues/700 and https://github.com/platformio/platformio-atom-ide-terminal/issues/707, this looks like an issue that needs to be resolved in https://github.com/daviwil/node-pty-prebuilt.  I see https://github.com/daviwil/node-pty-prebuilt/issues/14 has been opened on that repository already if you want to subscribe there.
