### ISSUE TITLE
Cannot Install packages behind proxy - "tunneling socket could not be established"

### ISSUE THREAD

**Issue by Knochi** [atom/apm#865]
atom/atom#18654 # Prerequisites

* [ X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: <https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode>
    * Followed all applicable steps in the debugging guide: <https://flight-manual.atom.io/hacking-atom/sections/debugging/>
    * Checked the FAQs on the message board for common solutions: <https://discuss.atom.io/c/faq>
    * Checked that your issue isn't already filed: <https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom>
    * Checked that there is not already an Atom package that provides the described functionality: <https://atom.io/packages>

set proxy via 
`apm config set https-proxy https://username:passwd@ipadress:port `
set SSL strict mode via
`apm config set strict-ssl false`

### Description
Can search and see packages but not install

### Steps to Reproduce

1. start atom
2. goto settings
3. install package (e.g. P5js-toolbar)

**Expected behavior:**
should install

**Actual behavior:**
button returns to "install"
shows error message:
`Request for package information failed: tunneling socket could not be established, cause=write EPROTO 16716:error:1408F10B:SSL routines:ssl3_get_record:wrong version number:openssl\ssl\record\ssl3_record.c:252: (5 attempts) (ECONNRESET) `

**Reproduces how often:**
every time

### Versions
Atom    : 1.40.0
Electron: 3.1.10
Chrome  : 66.0.3359.181
Node    : 10.2.0

### Additional Information
auto update works

**Comment by rsese** [comment]
Do you have the same issue using `apm` directly from the command line (`apm install P5js-toolbar`)?

**Comment by Knochi** [comment]
Yes exactly the same behaviour

**Comment by raoniz** [comment]
Kindly check here: #772

**Comment by rsese** [comment]
Thanks for confirming @Knochi :+1:  Going to close in favor of https://github.com/atom/apm/issues/772, see Lee's comment here: https://github.com/atom/apm/issues/772#issuecomment-445298119.  We're basically not in a place where we can prioritize investigating different proxy setups and why they may not work with Atom right now.  If anyone from the community is interested in helping however, there's a pointer to the network connection code in https://github.com/atom/apm/issues/772#issuecomment-445554199.

**Comment by Firzum** [comment]
I'm facing the same issue, I think
tunneling socket could not be established, cause=write EPROTO 140192657000256:error:1408F10B:SSL routines:ssl3_get_record:wrong version number:../deps/openssl/openssl/ssl/record/ssl3_record.c:252:

**Comment by Firzum** [comment]
I was wrong : It was due to an invalid configuration : https_proxy URL was set to HTTPS:// in place of HTTP:// (my proxy didn't require ssl for connection)
