### ISSUE TITLE
SVG images in package description are not shown on https://atom.io/packages

### ISSUE THREAD

**Issue by allefeld** [atom/apm#878]
### Prerequisites

* [X ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: <https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode>
    * Followed all applicable steps in the debugging guide: <https://flight-manual.atom.io/hacking-atom/sections/debugging/>
    * Checked the FAQs on the message board for common solutions: <https://discuss.atom.io/c/faq>
    * Checked that your issue isn't already filed: <https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom>
    * Checked that there is not already an Atom package that provides the described functionality: <https://atom.io/packages>

### Description

I have an Atom package whose README.md uses images in SVG format, e.g.

    ![](img/reversed-pilcrow.svg)

The images display correctly when the README is viewed on GitHub, see https://github.com/allefeld/atom-pandoc-pdf#toolbar-buttons

They do not display when the package description generated from the README is view on atom.io, see https://atom.io/packages/pandoc-pdf

Looking at the HTML

    <img src="https://i.github-camo.com/e313c5176d8175003eed882d265669186cdf3aa8/68747470733a2f2f7261772e67697468756275736572636f6e74656e742e636f6d2f616c6c6566656c642f61746f6d2d70616e646f632d7064662f76302e312e302f696d672f72657665727365642d70696c63726f772e737667" alt="" data-canonical-src="https://raw.githubusercontent.com/allefeld/atom-pandoc-pdf/v0.1.0/img/reversed-pilcrow.svg">

it appears like the svg file has been recognized as an embedded image and copied over to github-camo.com. However, opening the link leads to the message "not found".

By contrast, an embedded animated GIF does appear on atom.io.

### Steps to Reproduce

1. Link to SVG files as embedded images (`![](image.svg)`) in the README.md of an Atom package.
2. Push the files to GitHub. The SVG images appear embedded in the README.
3. Publish the package to atom.io.

**Expected behavior:**

The SVG images appear embedded in the package description, like on GitHub.

**Actual behavior:**

The SVG images do not appear embedded in the package description.
**Reproduces how often:**

Holds for all 7 SVG files used in this particular package README.

### Versions

Atom    : 1.43.0
Electron: 4.2.7
Chrome  : 69.0.3497.128
Node    : 10.11.0
apm  2.4.3
npm  6.2.0
node 10.2.1 x64
atom 1.43.0
python 2.7.16
git 2.20.1

**Comment by lee-dohm** [comment]
If you use an absolute URL rather than a relative one, including `https` as the protocol, this should prevent the use of `camo` and resolve this issue.

**Comment by allefeld** [comment]
Ehm....

Thanks for the tip, but that there's a workaround doesn't change the fact that there's a bug.

Are Atom developers interested in fixing bug?
