### ISSUE TITLE
MacOS 10.15.3 Package Install Failed

### ISSUE THREAD

**Issue by JRuss99** [atom/apm#879]
### Prerequisites

* [ X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: <https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode>
    * Followed all applicable steps in the debugging guide: <https://flight-manual.atom.io/hacking-atom/sections/debugging/>
    * Checked the FAQs on the message board for common solutions: <https://discuss.atom.io/c/faq>
    * Checked that your issue isn't already filed: <https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom>
    * Checked that there is not already an Atom package that provides the described functionality: <https://atom.io/packages>

### Description

I get the following error when I try to install a package on MacOS. I have tried this with the Atom-beautify and Language EJS packages:

npm ERR! code EPROTO
npm ERR! errno EPROTO
npm ERR! request to https://codeload.github.com/darron/language-ejs/legacy.tar.gz/v0.4.0 failed, reason: write EPROTO 4419333568:error:14094410:SSL routines:ssl3_read_bytes:sslv3 alert handshake failure:../deps/openssl/openssl/ssl/record/rec_layer_s3.c:1407:SSL alert number 40
npm ERR! 

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/joe/.atom/.apm/_logs/2020-02-02T13_46_06_144Z-debug.log

### Steps to Reproduce

1. Click Settings
2. Try to install the package under "install".
3. Error appears

**Expected behavior:**

Package installs.

**Actual behavior:**

Package fails to install.

**Reproduces how often:**

All the time,

### Versions

1.43

### Additional Information

I have also installed NodeJS and I am using my home WiFi which is secured.

**Comment by darangi** [comment]
Have you tried installing the package using another wifi network?
