### ISSUE TITLE
Cannot unpublish theme because GitHub repository is deleted

### ISSUE THREAD

**Issue by consciousatom** [atom/apm#904]
My atom theme https://atom.io/themes/eschillus-syntax cannot be deleted because I deleted it's repository. Is there someway  I can still delete it or will it have to be done by someone with access?

**Comment by darangi** [comment]
Hi @eschillus , you want to take this project off APM?

**Comment by eschillus** [comment]
> Hi @eschillus , you want to take this project off APM?

Correct.
