### ISSUE TITLE
downloading hydrogen in atom error

### ISSUE THREAD

**Issue by gophila** [atom/apm#921]
This is my first week downloading an atom application for purpose of practicing programming codes. At first, the hydrogen 
was working fine until I got a bug that didn't allow me from using the hydrogen application. So I tried to download and update
new one but I got this error instead below.  Any help would be appreciated. 

Installing “Hydrogen@2.14.7” failed.Hide output…

> zeromq@5.2.0 install C:\Users\money\AppData\Local\Temp\apm-install-dir-2021314-1728-1xz3stg.7e91\node_modules\Hydrogen\node_modules\zeromq
> node scripts/prebuild-install.js || (node scripts/preinstall.js && node-gyp rebuild)

prebuild-install WARN install No prebuilt binaries found (target=9.4.4 runtime=electron arch=x64 libc= platform=win32)

Downloading libzmq for Windows
Download finished

C:\Users\money\AppData\Local\Temp\apm-install-dir-2021314-1728-1xz3stg.7e91\node_modules\Hydrogen\node_modules\zeromq>if not defined npm_config_node_gyp (node "C:\Users\money\AppData\Local\atom\app-1.56.0\resources\app\apm\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Users\money\AppData\Local\atom\app-1.56.0\resources\app\apm\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild ) 

npm WARN deprecated core-js@2.6.12: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
npm WARN deprecated json-parser@1.1.5: `json-parser` is deprecated. Please use `comment-json` instead
npm WARN deprecated popper.js@1.16.1: You can find the new Popper v2 at @popperjs/core, this package is dedicated to the legacy v1
npm WARN deprecated highlight.js@9.15.10: Version no longer supported. Upgrade to @latest
gyp ERR! find VS 
gyp ERR! find VS msvs_version not set from command line or npm config
gyp ERR! find VS VCINSTALLDIR not set, not running in VS Command Prompt
gyp ERR! find VS could not use PowerShell to find Visual Studio 2017 or newer
gyp ERR! find VS looking for Visual Studio 2015
gyp ERR! find VS - not found
gyp ERR! find VS not looking for VS2013 as it is only supported up to Node.js 8
gyp ERR! find VS 
gyp ERR! find VS **************************************************************
gyp ERR! find VS You need to install the latest version of Visual Studio
gyp ERR! find VS including the "Desktop development with C++" workload.
gyp ERR! find VS For more information consult the documentation at:
gyp ERR! find VS https://github.com/nodejs/node-gyp#on-windows
gyp ERR! find VS **************************************************************
gyp ERR! find VS 
gyp ERR! configure error 
gyp ERR! stack Error: Could not find any Visual Studio installation to use
gyp ERR! stack     at VisualStudioFinder.fail (C:\Users\money\AppData\Local\atom\app-1.56.0\resources\app\apm\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:121:47)
gyp ERR! stack     at C:\Users\money\AppData\Local\atom\app-1.56.0\resources\app\apm\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:74:16
gyp ERR! stack     at VisualStudioFinder.findVisualStudio2013 (C:\Users\money\AppData\Local\atom\app-1.56.0\resources\app\apm\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:351:14)
gyp ERR! stack     at C:\Users\money\AppData\Local\atom\app-1.56.0\resources\app\apm\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:70:14
gyp ERR! stack     at C:\Users\money\AppData\Local\atom\app-1.56.0\resources\app\apm\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:372:16
gyp ERR! stack     at C:\Users\money\AppData\Local\atom\app-1.56.0\resources\app\apm\node_modules\npm\node_modules\node-gyp\lib\util.js:54:7
gyp ERR! stack     at C:\Users\money\AppData\Local\atom\app-1.56.0\resources\app\apm\node_modules\npm\node_modules\node-gyp\lib\util.js:33:16
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:297:5)
gyp ERR! stack     at ChildProcess.emit (events.js:200:13)
gyp ERR! stack     at maybeClose (internal/child_process.js:1021:16)
gyp ERR! System Windows_NT 10.0.19042
gyp ERR! command "C:\\Users\\money\\AppData\\Local\\atom\\app-1.56.0\\resources\\app\\apm\\bin\\node.exe" "C:\\Users\\money\\AppData\\Local\\atom\\app-1.56.0\\resources\\app\\apm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\money\AppData\Local\Temp\apm-install-dir-2021314-1728-1xz3stg.7e91\node_modules\Hydrogen\node_modules\zeromq
gyp ERR! node -v v12.4.0
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok 
npm WARN enoent ENOENT: no such file or directory, open 'C:\Users\money\AppData\Local\Temp\apm-install-dir-2021314-1728-1xz3stg.7e91\package.json'
npm WARN apm-install-dir-2021314-1728-1xz3stg.7e91 No description
npm WARN apm-install-dir-2021314-1728-1xz3stg.7e91 No repository field.
npm WARN apm-install-dir-2021314-1728-1xz3stg.7e91 No README data
npm WARN apm-install-dir-2021314-1728-1xz3stg.7e91 No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! zeromq@5.2.0 install: `node scripts/prebuild-install.js || (node scripts/preinstall.js && node-gyp rebuild)`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the zeromq@5.2.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\money\.atom\.apm\_logs\2021-04-14T04_01_17_309Z-debug.log

**Comment by aminya** [comment]
Duplicate of https://github.com/nteract/hydrogen/issues/2034

Please downgrade to Atom 1.55 for now.

**Comment by gophila** [comment]
I just downgraded Atom to 1.55.0 from 1.56.0 and tried to activate hydrogen kernel but it's still not responding.  Further help would be appreciated

**Comment by gophila** [comment]
> Duplicate of [nteract/hydrogen#2034](https://github.com/nteract/hydrogen/issues/2034)
> 
> Please downgrade to Atom 1.55 for now.

I just downgraded Atom to 1.55.0 from 1.56.0 and tried to activate hydrogen kernel but it's still not responding. Further help would be appreciated

**Comment by aminya** [comment]
Hydrogen 2.15.2 is released. Now you can use Hydrogen on the latest Atom 🎉

**Comment by gophila** [comment]
it's working perfectly fine now! Wow! Thank you so much!

> Hydrogen 2.15.2 is released. Now you can use Hydrogen on the latest Atom 🎉

It's working perfectly fine now! Wow! Thank you so much!
